
drop table eloflatbookkeys
create table eloflatbookkeys (bookkey int null)
grant all on eloflatbookkeys to public
go

if exists (select * from sysobjects where id = object_id(N'dbo.eloflatfeed') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table dbo.eloflatfeed
GO

CREATE TABLE dbo.eloflatfeed (
	bookkey int NOT NULL,
	isbn13 varchar (13) NULL ,
	isbn10 varchar (10) NULL ,	
	ean varchar (50) NULL,
	titleprefix varchar (25) NULL ,
	titlewithoutprefix varchar (80) NULL ,
	titlewithprefix varchar (105) NULL ,
	subtitle varchar (255) NULL ,
	publishername varchar (40) NULL ,
	imprintname varchar (40) NULL ,
	authorlastname1 varchar (50) NULL ,
	authorfirstname1 varchar (50) NULL ,
	authorsuffix1 varchar (75) NULL,
	authordisplayname1 varchar (80) NULL ,
	authorprimaryflag1 varchar (3) NULL ,
	authortype1 varchar (50) NULL ,
	authorlastname2 varchar (50) NULL ,
	authorfirstname2 varchar (50) NULL ,
	authorsuffix2 varchar (75) NULL,
	authordisplayname2 varchar (80) NULL ,
	authorprimaryflag2 varchar (3) NULL ,
	authortype2 varchar (50) NULL ,
	authorlastname3 varchar (50) NULL ,
	authorfirstname3 varchar (50) NULL ,
	authorsuffix3 varchar (75) NULL,
	authordisplayname3 varchar (80) NULL ,
	authorprimaryflag3 varchar (3) NULL ,
	authortype3 varchar (50) NULL ,
	authorlastname4 varchar (50) NULL ,
	authorfirstname4 varchar (50) NULL ,
	authorsuffix4 varchar (75) NULL,
	authordisplayname4 varchar (80) NULL ,
	authorprimaryflag4 varchar (3) NULL ,
	authortype4 varchar (15) NULL ,
	fullauthordisplayname varchar (255) NULL ,
	usretailprice decimal (10,2) NULL ,
	canadaretailprice decimal (10,2) NULL ,
	ukretailprice decimal (10,2) NULL ,
	mediatypedesc varchar (25) NULL ,
	mediabisaccode varchar (10) NULL,
	formatdesc varchar (25) NULL ,
	formatbisaccode varchar (10) NULL,
	pagecount smallint NULL ,
	trimsizewidth varchar (10) NULL ,
	trimsizelength varchar (10) NULL ,
	pubdateYYYYMMDD varchar (8) NULL ,
	pubmonth varchar (25) NULL ,
	bisaccategorymajorcode1 varchar (15) NULL ,
	bisaccategorymajordesc1 varchar (50) NULL ,	
	bisaccategoryminorcode1 varchar (15) NULL ,
	bisaccategoryminordesc1 varchar (50) NULL ,	
	bisaccategorymajorcode2 varchar (15) NULL ,
	bisaccategorymajordesc2 varchar (50) NULL ,
	bisaccategoryminorcode2 varchar (15) NULL ,
	bisaccategoryminordesc2 varchar (50) NULL ,	
	bisaccategorymajorcode3 varchar (15) NULL ,
	bisaccategorymajordesc3 varchar (50) NULL ,
	bisaccategoryminorcode3 varchar (15) NULL ,
	bisaccategoryminordesc3 varchar (50) NULL ,
	bisaccategorymajorcode4 varchar (15) NULL ,
	bisaccategorymajordesc4 varchar (50) NULL ,
	bisaccategoryminorcode4 varchar (15) NULL ,
	bisaccategoryminordesc4 varchar (50) NULL ,	
	bisaccategorymajorcode5 varchar (15) NULL ,
	bisaccategorymajordesc5 varchar (50) NULL ,
	bisaccategoryminorcode5 varchar (15) NULL ,
	bisaccategoryminordesc5 varchar (50) NULL ,		
	series varchar (100) NULL ,
	territories varchar (40) NULL ,
	edition varchar (40) NULL ,
	editionnumber decimal (10,2) NULL,
	editiondesc varchar (40) NULL,
	bisacstatuscode varchar (5) NULL ,
	bisacstatusdesc varchar (50) NULL,
	briefdescription text NULL,
	description text NULL,
	authorbio text NULL,
	tableofcontents text NULL,
	excerpt text NULL,
	cartonqty int null,
	insertillusdesc varchar (100) null,
	ages varchar (25) null,
	agelow varchar (25) null,
	agehigh varchar (25) null,
	keynote text NULL,
	subrightnotes text NULL,
	subrightsales text NULL,
	copyrightyear text NULL,
	catalogquotes text NULL,
	quote1 text NULL,
	quote2 text NULL,
	quote3 text NULL,
	adultchildrensflag varchar (25) null,
	discountcode varchar(25),
     	 audiencecode1 varchar(25),
	audiencecode2 varchar(25)
)
GO
grant all on eloflatfeed to public
go
