ALTER TABLE taqproject
ADD proposedterritorycode INT NULL, 
    titletypecode INT NULL, 
    canadianrestrictioncode INT NULL, 
    returncode INT NULL, 
    restrictioncode INT NULL, 
    origincode INT NULL, 
    copyrightyear VARCHAR(4), 
    languagecode INT NULL, 
    languagecode2 INT NULL, 
    allagesind TINYINT NULL, 
    agelowupind TINYINT NULL, 
    agelow FLOAT NULL, 
    agehighupind TINYINT NULL, 
    agehigh FLOAT NULL, 
    gradelowupind TINYINT NULL, 
    gradelow VARCHAR(4), 
    gradehighupind TINYINT NULL, 
    gradehigh VARCHAR(4) NULL
