call set_connection.bat

osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AssocTitleAuthor.sql >run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AssocTitleISBN.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AssocTitlePrice.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AssocTitlePubDate.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AssocTitleTitle.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AssocTitleType.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Audience.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Author.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AuthorBio.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AuthorBioUnique.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AuthorCorpInd.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AuthorKey.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AuthorNameBorders.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AuthorPrimaryInd.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AuthorPrimaryKey.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Authortype.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_AuthorTypeBorders.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BackPanelCopy.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestAnncd1stPrint.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestDate.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestInsertIllus.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestPageCount.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestPubDate.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestPubDateBorders.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestReleaseDate.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestReleaseQty.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestShipDate.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestStockDueDate.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestTrimDimension.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestTrimSize.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestUSPrice.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestUSPriceAndType.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BestUSPrice_EffDate.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BisacStatus.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BisacSubject.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BNAuthor.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_book_lastmaintdate.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BordersTitle.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_BriefDescription.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CanadianRestriction.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CartonQty.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Comment_TitleError.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode01.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode02.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode03.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode04.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode05.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode06.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode07.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode08.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode09.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomCode10.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat01.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat02.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat03.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat04.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat05.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat06.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat07.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat08.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat09.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomFloat10.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd01.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd02.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd03.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd04.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd05.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd06.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd07.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd08.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd09.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInd10.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt01.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt02.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt03.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt04.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt05.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt06.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt07.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt08.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt09.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_CustomInt10.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Description.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Discount.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Edition.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_estmessage_errorseverity.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Format.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_FormatBorders.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_FullAuthorDisplayName.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_GentableFilterkey.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_gentables_desc.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_GroupLevel1.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_GroupLevel2.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_GroupLevel3.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_InsideFlapCopy.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Isbn.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Language.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_LastKeyDateChanged.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_LastTitleFieldChanged.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Media.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_MktStrategy.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_namepart.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_NULLPlaceholder.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_PreviousEditionBookkey.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_PreviousEditionIsbn.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iProper_Case.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Publicity.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_PubMonth.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Quote1.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Quote2.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Quote3.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Quote4.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Quote5.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_ReturnInd.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_ReturnRestriction.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_SalesHandle.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_SendToEloquenceInd.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Series.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_SeriesVolume.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_ShortTitle.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_statuscode.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_subgentables_desc.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Subjects.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_SubTitle.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Territory.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_Title.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_TitlePrefix.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_TitleVerifyStatus.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_TOC.sql >>run_funcs.log

osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_titleinfo.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_titlesubjects.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_titlecontributors.sql >>run_funcs.log
osql -U%userid% -P%password% -S%server% -d%database% -n -iqweb_get_titlecomments.sql >>run_funcs.log