

/******************************************************************************************
**  Executes the qutl_insert_bookmiscitems  procedure
*******************************************************************************************/

BEGIN

  DECLARE
   @v_datacode			integer,
   @v_misckey			integer,
   @v_error_code		Integer,
   @v_error_desc		varchar(2000) 
    
  
   SET @v_datacode = NULL
   SET @v_misckey = 0
   SET @v_error_code = 0
   SET @v_error_desc = ''    
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Project Original',  2, @v_datacode, NULL, 133, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Original Cost' WHERE misckey = @v_misckey	 	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Project Revised',  2, @v_datacode, NULL, 134, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Revised Cost' WHERE misckey = @v_misckey	 	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Advertising Revised Calculated',  6, @v_datacode, NULL, 102, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Advertising' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Advertising Revised Calculated','EXEC calc_cost_actual_by_project_type @projectkey, 52, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Advertising Original',  6, @v_datacode, NULL, 60, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Advertising' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Advertising Original','EXEC calc_cost_budget_by_project_type @projectkey, 52, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Advertising Variance',  6, @v_datacode, NULL, 68, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Advertising' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Advertising Variance','EXEC calc_cost_variance_by_project_type @projectkey, 60, 52, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Author Tours Revised Calculated',  6, @v_datacode, NULL, 93, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Author Tours' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Author Tours Revised Calculated','EXEC calc_cost_actual_by_project_type @projectkey, 51, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Author Tours Original',  6, @v_datacode, NULL, 59, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Author Tours' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Author Tours Original','EXEC calc_cost_budget_by_project_type @projectkey, 51, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Author Tours Variance',  6, @v_datacode, NULL, 67, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Author Tours' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Author Tours Variance','EXEC calc_cost_variance_by_project_type @projectkey, 59, 51, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Coop Advertising Revised Calculated',  6, @v_datacode, NULL, 103, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Coop Advertising' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Coop Advertising Revised Calculated','EXEC calc_cost_actual_by_project_type @projectkey, 53, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Coop Advertising Original',  6, @v_datacode, NULL, 61, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Coop Advertising' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Coop Advertising Original','EXEC calc_cost_budget_by_project_type @projectkey, 53, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Coop Advertising Variance',  6, @v_datacode, NULL, 69, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Coop Advertising' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Coop Advertising Variance','EXEC calc_cost_variance_by_project_type @projectkey, 61, 53, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Galleys Revised Calculated',  6, @v_datacode, NULL, 81, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Galleys' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Galleys Revised Calculated','EXEC calc_cost_actual_by_project_type @projectkey, 49, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Galleys Original',  6, @v_datacode, NULL, 57, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Galleys' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Galleys Original','EXEC calc_cost_budget_by_project_type @projectkey,49 , @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Galleys Variance',  6, @v_datacode, NULL, 65, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Galleys' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Galleys Variance','EXEC calc_cost_variance_by_project_type @projectkey, 57, 49, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Original',  7, @v_datacode, NULL, 73, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	 	 	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Press Materials Revised Calculated',  6, @v_datacode, NULL, 87, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Press Materials' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Press Materials Revised Calculated','EXEC calc_cost_actual_by_project_type @projectkey, 50, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Press Materials Original',  6, @v_datacode, NULL, 58, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Press Materials' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Press Materials Original','EXEC calc_cost_budget_by_project_type @projectkey, 50, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Press Materials Variance',  6, @v_datacode, NULL, 66, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Press Materials' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Press Materials Variance','EXEC calc_cost_variance_by_project_type @projectkey, 58, 50, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Promotion Revised Calculated',  6, @v_datacode, NULL, 104, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Promotion' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Promotion Revised Calculated','EXEC calc_cost_actual_by_project_type @projectkey, 54, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Promotion Original',  6, @v_datacode, NULL, 62, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Promotion' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Promotion Original','EXEC calc_cost_budget_by_project_type @projectkey, 54, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Promotion Variance',  6, @v_datacode, NULL, 70, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Promotion' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Promotion Variance','EXEC calc_cost_variance_by_project_type @projectkey, 62, 54, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Revised',  7, @v_datacode, NULL, 74, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	 	 	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Total Revised',  6, @v_datacode, NULL, 56, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Revised Total' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Total Revised','EXEC calc_total_cost_actual @projectkey, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Total Original',  6, @v_datacode, NULL, 64, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Original Total' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Total Original','EXEC calc_total_cost_budget_related_projects @projectkey, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Total Variance',  6, @v_datacode, NULL, 72, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Variance Total' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Total Variance','EXEC calc_total_cost_variance @projectkey, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'TotalPlan Variance',  6, @v_datacode, NULL, 72, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Variance Total' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Total Variance','EXEC calc_total_cost_variance_related_projects @projectkey, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Variance',  7, @v_datacode, NULL, 75, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	 	 	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Display Revised Calculated',  6, @v_datacode, NULL, 116, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Display' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Display Revised Calculated','EXEC calc_cost_actual_by_project_type @projectkey, 55, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Display Original',  6, @v_datacode, NULL, 63, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Display' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Display Original','EXEC calc_cost_budget_by_project_type @projectkey, 55, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Dislay Variance',  6, @v_datacode, NULL, 71, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Display' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Display Variance','EXEC calc_cost_variance_by_project_type @projectkey, 63, 55, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Campaign Budget',  2, @v_datacode, NULL, 135, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Campaign Budget ' WHERE misckey = @v_misckey	 	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Campaign Project Original Total',  6, @v_datacode, NULL, 136, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Original Total' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Total Project Original','EXEC calc_total_cost_budget_related_projects @projectkey, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc
SET @v_datacode = NULL	exec  qutl_insert_bookmiscitems  'Campaign Project Variance Total',  6, @v_datacode, NULL, 137, @v_misckey OUTPUT, @v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc	UPDATE bookmiscitems SET fieldformat = '$###,##0.##', misclabel = 'Variance Total' WHERE misckey = @v_misckey	exec qutl_insert_miscitemcalc   @v_misckey,'Total Project Variance','EXEC calc_total_cost_variance_related_projects @projectkey, @result OUTPUT',@v_error_code  OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'misckey = ' + CAST(@v_misckey AS varchar)+ ', error message =' + @v_error_desc

END  
  
 GO