IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = Object_id('temp_sgt_bisaccodes_2015') AND type = 'U')
  BEGIN
    DROP table temp_sgt_bisaccodes_2015
  END
go

CREATE TABLE temp_sgt_bisaccodes_2015 (
	Code char(255),
	Literal char(255))
go


INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'ARC025000', N'Vernacular')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'ART019000', N'Asian / General')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'ART019010', N'Asian / Chinese')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'ART019020', N'Asian / Indian & South Asian')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'ART019030', N'Asian / Japanese')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'ART061000', N'Glass')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'ART062000', N'Public Art')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'BUS070160', N'Industries / Construction')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'CGN007000', N'Nonfiction / General')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'CGN007010', N'Nonfiction / Biography & Memoir')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'CKB122000', N'Courses & Dishes / Ice Cream, Ices, etc.')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'CKB097000', N'Regional & Ethnic / Australian & Oceanian')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'CKB123000', N'Regional & Ethnic / Korean')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'CKB124000', N'Regional & Ethnic / Southeast Asian')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'CKB125000', N'Vegan')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'CKB086000', N'Vegetarian')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'DES005000', N'Fashion & Accessories')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'DES014000', N'Jewelry')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC064000', N'Absurdist')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC065000', N'Epistolary')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC009090', N'Fantasy / Romantic')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC016000', N'Humorous / General                                                                                                                                                                                                                                             ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC060000', N'Humorous / Black Humor')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027280', N'Romance / Historical / Tudor')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027290', N'Romance / Holiday')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027300', N'Romance / LGBT / General')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027190', N'Romance / LGBT / Gay')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027210', N'Romance / LGBT / Lesbian')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027120', N'Romance / Paranormal / General')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027310', N'Romance / Paranormal / Shifters')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027320', N'Romance / Paranormal / Vampires')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC027330', N'Romance / Sports')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'FIC066000', N'Small Town & Rural')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'GAM019000', N'Activity Books (incl. Coloring Books)')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'GAR030000', N'Pictorial')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'HEA050000', N'Vaccinations')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'HIS027220', N'Military / Ancient')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'HIS027230', N'Military / Medieval')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'HIS027240', N'Military / Vehicles')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'HIS027130', N'Military / Wars & Conflicts (Other)')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'HOM023000', N'Small Spaces')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV004050', N'Biographical / Africa')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV004060', N'Biographical / Asia')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV004010', N'Biographical / Europe')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV004070', N'Biographical / Latin America')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV049000', N'Computers & Digital Media ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV013000', N'Family / General (see also headings under Social Themes) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV069000', N'Ghost Stories')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV018000', N'Horror')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV070000', N'Poetry (see also Stories in Verse)')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV033250', N'Religious / Buddhist                                                                                                                                                                                                                                           ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV033260', N'Religious / Hindu                                                                                                                                                                                                                                              ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV033270', N'Religious / Muslim                                                                                                                                                                                                                                             ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039000', N'Social Themes / General (see also headings under Family) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039020', N'Social Themes / Adolescence ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039230', N'Social Themes / Bullying ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039190', N'Social Themes / Dating & Relationships ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039030', N'Social Themes / Death & Dying ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039240', N'Social Themes / Depression & Mental Illness ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039040', N'Social Themes / Drugs, Alcohol, Substance Abuse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039250', N'Social Themes / Emigration & Immigration ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039050', N'Social Themes / Emotions & Feelings ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039060', N'Social Themes / Friendship ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039070', N'Social Themes / Homelessness & Poverty ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039200', N'Social Themes / Manners & Etiquette ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039090', N'Social Themes / New Experience ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039100', N'Social Themes / Peer Pressure ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039010', N'Social Themes / Physical & Emotional Abuse (see also Social Themes / Sexual Abuse) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039120', N'Social Themes / Prejudice & Racism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039280', N'Social Themes / Religion & Faith ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039130', N'Social Themes / Runaways ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039140', N'Social Themes / Self-Esteem & Self-Reliance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039210', N'Social Themes / Sexual Abuse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039150', N'Social Themes / Special Needs ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039270', N'Social Themes / Strangers ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039160', N'Social Themes / Suicide ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039220', N'Social Themes / Values & Virtues ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV039180', N'Social Themes / Violence ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV032200', N'Sports & Recreation / Gymnastics ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV032210', N'Sports & Recreation / Track & Field ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV057000', N'Stories in Verse (see also Poetry) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JUV071000', N'Superheroes ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF019000', N'Family / General (see also headings under Social Topics) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053080', N'LGBT ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF049320', N'Religion / Buddhism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF049330', N'Religion / Hinduism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053000', N'Social Topics / General (see also headings under Family) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053010', N'Social Topics / Adolescence ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053220', N'Social Topics / Bullying ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053020', N'Social Topics / Dating & Relationships ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053030', N'Social Topics / Death & Dying ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053230', N'Social Topics / Depression & Mental Illness ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053040', N'Social Topics / Drugs, Alcohol, Substance Abuse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053240', N'Social Topics / Emigration & Immigration ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053050', N'Social Topics / Emotions & Feelings ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053060', N'Social Topics / Friendship ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053070', N'Social Topics / Homelessness & Poverty ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053090', N'Social Topics / Manners & Etiquette ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053100', N'Social Topics / New Experience ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053110', N'Social Topics / Peer Pressure ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053120', N'Social Topics / Physical & Emotional Abuse (see also Social Topics / Sexual Abuse) ')
GO
print 'Processed 100 total records'
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053140 ', N'Social Topics / Prejudice & Racism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053160 ', N'Social Topics / Self-Esteem & Self-Reliance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053170 ', N'Social Topics / Sexual Abuse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053180 ', N'Social Topics / Special Needs ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'SPO077000 ', N'Children''s & Youth Sports ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'STU004000 ', N'Book Notes (see also JUVENILE NONFICTION/Study Aids/Book Notes or YOUNG ADULT NONFICTION / Study Aids / Book Notes) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'STU028000 ', N'TOEFL (Test of English as a Foreign Language) & IELTS (International English Language Testing System) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'TEC009160 ', N'Civil / Transportation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'TEC069000 ', N'Welding ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'TRA006040 ', N'Ships & Shipbuilding / Submarines ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF000000 ', N'General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'SOC002010 ', N'Anthropology / Cultural & Social ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'SOC064000 ', N'LGBT Studies / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'SOC012000 ', N'LGBT Studies / Gay Studies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'SOC017000 ', N'LGBT Studies / Lesbian Studies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'SOC026040 ', N'Sociology / Social Theory ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF001000 ', N'Action & Adventure / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF001010 ', N'Action & Adventure / Pirates ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF001020 ', N'Action & Adventure / Survival Stories ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053260 ', N'Social Topics / Strangers ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF002000 ', N'Animals / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF002010 ', N'Animals / Horses ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF002020 ', N'Animals / Marine Life ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF002030 ', N'Animals / Mythical Creatures ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF002040 ', N'Animals / Pets ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF003000 ', N'Apocalyptic & Post-Apocalyptic ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF004000 ', N'Art ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF005000 ', N'Biographical ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF006000 ', N'Books & Libraries ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF007000 ', N'Boys & Men ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF008000 ', N'Careers, Occupations, Internships ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF009000 ', N'Classics ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF010000 ', N'Comics & Graphic Novels / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF010010 ', N'Comics & Graphic Novels / Manga ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053190 ', N'Social Topics / Suicide ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF010020 ', N'Comics & Graphic Novels / Media Tie-In ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF010030 ', N'Comics & Graphic Novels / Science Fiction & Fantasy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF010040 ', N'Comics & Graphic Novels / Superheroes ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF011000 ', N'Coming of Age ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF012000 ', N'Computers & Digital Media ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF013000 ', N'Cooking & Food ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF014000 ', N'Diversity & Multicultural ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF015000 ', N'Dystopian ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF016000 ', N'Epistolary (Letters & Diaries) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF017000 ', N'Fairy Tales & Folklore / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF017010 ', N'Fairy Tales & Folklore / Adaptations ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF017020 ', N'Fairy Tales & Folklore / Anthologies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF017030 ', N'Fairy Tales & Folklore / Country & Ethnic ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018000 ', N'Family / General (see also headings under Social Themes) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053200 ', N'Social Topics / Values & Virtues ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018010 ', N'Family / Adoption ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018020 ', N'Family / Alternative Family ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018030 ', N'Family / Marriage & Divorce ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018040 ', N'Family / Multigenerational ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018050 ', N'Family / Orphans & Foster Homes ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018060 ', N'Family / Parents ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018070 ', N'Family / Siblings ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF018080 ', N'Family / Stepfamilies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF019000 ', N'Fantasy / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF019010 ', N'Fantasy / Contemporary ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF019020 ', N'Fantasy / Dark Fantasy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF019030 ', N'Fantasy / Epic ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF019040 ', N'Fantasy / Historical ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF019050 ', N'Fantasy / Wizards & Witches ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'JNF053210 ', N'Social Topics / Violence ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF020000 ', N'Fashion & Beauty ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF021000 ', N'Ghost Stories ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF022000 ', N'Girls & Women ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF023000 ', N'Health & Daily Living / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF023010 ', N'Health & Daily Living / Diseases, Illnesses & Injuries ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024000 ', N'Historical / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024010 ', N'Historical / Africa ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024020 ', N'Historical / Ancient Civilizations ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024030 ', N'Historical / Asia ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024040 ', N'Historical / Canada ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024050 ', N'Historical / Europe ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024060 ', N'Historical / Exploration & Discovery ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024070 ', N'Historical / Holocaust ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024080 ', N'Historical / Medieval ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'MED003100 ', N'Allied Health Services / Medical Coding & Billing ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024090 ', N'Historical / Middle East ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024100 ', N'Historical / Military & Wars ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024110 ', N'Historical / Prehistory ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024120 ', N'Historical / Renaissance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024130 ', N'Historical / United States / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024140 ', N'Historical / United States / Colonial & Revolutionary Periods ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024150 ', N'Historical / United States / 19th Century ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024160 ', N'Historical / United States / Civil War Period (1850-1877) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024170 ', N'Historical / United States / 20th Century ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF024180 ', N'Historical / United States / 21st Century ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF025000 ', N'Holidays & Celebrations ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF026000 ', N'Horror ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF027000 ', N'Humorous / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF027010 ', N'Humorous / Black Comedy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'MED058230 ', N'Nursing / Palliative Care ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF027020 ', N'Humorous / Satire ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF028000 ', N'Interactive Adventures ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF029000 ', N'Law & Crime ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF030000 ', N'Legends, Myths, Fables / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF030010 ', N'Legends, Myths, Fables / Arthurian ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF030020 ', N'Legends, Myths, Fables / Greek & Roman ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF031000 ', N'LGBT ')
GO
print 'Processed 200 total records'
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF032000 ', N'Lifestyles / City & Town Life ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF033000 ', N'Lifestyles / Country Life ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF034000 ', N'Lifestyles / Farm & Ranch Life ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF035000 ', N'Light Novel (Ranobe) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF036000 ', N'Literary ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF037000 ', N'Loners & Outcasts ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF038000 ', N'Magical Realism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'MED058180 ', N'Nursing / Psychiatric & Mental Health ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF039000 ', N'Media Tie-In ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF040000 ', N'Mermaids ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF041000 ', N'Monsters ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF042000 ', N'Mysteries & Detective Stories ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF043000 ', N'Nature & the Natural World / General (see also headings under Animals) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF043010 ', N'Nature & the Natural World / Environment ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF044000 ', N'Novels in Verse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF045000 ', N'Paranormal, Occult & Supernatural ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046000 ', N'People & Places / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046010 ', N'People & Places / Aboriginal & Indigenous ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046020 ', N'People & Places / Africa ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046030 ', N'People & Places / Asia ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046040 ', N'People & Places / Australia & Oceania ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046050 ', N'People & Places / Canada ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'MED058090 ', N'Nursing / Social, Ethical & Legal Issues ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'MUS054000 ', N'Philosophy & Social Aspects ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PER021000 ', N'Dance / Regional & Ethnic ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PER013000 ', N'Theater / Broadway & Musicals ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PER011040 ', N'Theater / Stagecraft & Scenography ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PET013000 ', N'Insects & Spiders ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PHI046000 ', N'Individual Philosophers ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PHO026000 ', N'Astrophotography ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PHO027000 ', N'Forensic ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PHO023110 ', N'Subjects & Themes / Food ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PHO016000 ', N'Subjects & Themes / Portraits & Selfies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PHO023120 ', N'Subjects & Themes / Street Photography ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PHO023130 ', N'Subjects & Themes / Underwater ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'POE025000 ', N'Haiku ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'POL068000 ', N'Public Policy / Energy Policy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'POL069000 ', N'Public Policy / Military Policy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'PSY053000 ', N'Evolutionary Psychology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'REF032000 ', N'Event Planning ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'SCI013100 ', N'Chemistry / Electrochemistry ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046060 ', N'People & Places / Caribbean & Latin America ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046070 ', N'People & Places / Europe ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046080 ', N'People & Places / Mexico ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046090 ', N'People & Places / Middle East ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046100 ', N'People & Places / Polar Regions ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046110 ', N'People & Places / United States / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046120 ', N'People & Places / United States / African American                                                                                                                                                                                                             ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046130 ', N'People & Places / United States / Asian American                                                                                                                                                                                                               ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046140 ', N'People & Places / United States / Hispanic & Latino                                                                                                                                                                                                            ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF046150 ', N'People & Places / United States / Native American                                                                                                                                                                                                              ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF047000 ', N'Performing Arts / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF047010 ', N'Performing Arts / Dance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF047020 ', N'Performing Arts / Film ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF047030 ', N'Performing Arts / Music ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF047040 ', N'Performing Arts / Television & Radio ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF047050 ', N'Performing Arts / Theater & Musicals ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF048000 ', N'Poetry ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF049000 ', N'Politics & Government ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF050000 ', N'Recycling & Green Living ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051000 ', N'Religious / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051010 ', N'Religious / Agnostic & Atheist ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051020 ', N'Religious / Buddhist ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051030 ', N'Religious / Christian / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051040 ', N'Religious / Christian / Action & Adventure ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051050 ', N'Religious / Christian / Comics & Graphic Novels ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051060 ', N'Religious / Christian / Fantasy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051070 ', N'Religious / Christian / Historical ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051080 ', N'Religious / Christian / Mysteries & Detective Stories                                                                                                                                                                                                          ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051090 ', N'Religious / Christian / Relationships                                                                                                                                                                                                                          ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051100 ', N'Religious / Christian / Science Fiction ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051110 ', N'Religious / Christian / Social Issues ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051120 ', N'Religious / Hindu ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051130 ', N'Religious / Jewish ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF051140 ', N'Religious / Muslim ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF052000 ', N'Romance / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF052010 ', N'Romance / Clean & Wholesome ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF052020 ', N'Romance / Contemporary ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF052030 ', N'Romance / Historical ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF052040 ', N'Romance / LGBT ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF052050 ', N'Romance / Paranormal ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF052060 ', N'Romance / Romantic Comedy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF053000 ', N'Royalty ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF054000 ', N'School & Education / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF054010 ', N'School & Education / Boarding School & Prep School ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF054020 ', N'School & Education / College & University ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF055000 ', N'Science & Technology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF056000 ', N'Science Fiction / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF056010 ', N'Science Fiction / Alien Contact ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF056020 ', N'Science Fiction / Space Opera ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF057000 ', N'Short Stories ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058000 ', N'Social Themes / General (see also headings under Family) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058010 ', N'Social Themes / Assimilation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058020 ', N'Social Themes / Bullying ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058030 ', N'Social Themes / Class Differences ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058040 ', N'Social Themes / Dating & Sex ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058050 ', N'Social Themes / Death & Dying ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058060 ', N'Social Themes / Depression ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058070 ', N'Social Themes / Disabilities & Special Needs ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058080 ', N'Social Themes / Drugs, Alcohol, Substance Abuse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058090 ', N'Social Themes / Eating Disorders & Body Image ')
GO
print 'Processed 300 total records'
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058100 ', N'Social Themes / Emigration & Immigration ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058110 ', N'Social Themes / Emotions & Feelings ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058120 ', N'Social Themes / Friendship ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058130 ', N'Social Themes / Homelessness & Poverty ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058140 ', N'Social Themes / Mental Illness ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058150 ', N'Social Themes / New Experience ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058160 ', N'Social Themes / Peer Pressure ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058170 ', N'Social Themes / Physical & Emotional Abuse (see also Social Themes / Sexual Abuse) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058180 ', N'Social Themes / Pregnancy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058190 ', N'Social Themes / Prejudice & Racism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058200 ', N'Social Themes / Religion & Faith ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058210 ', N'Social Themes / Runaways ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058220 ', N'Social Themes / Self-Esteem & Self-Reliance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058230 ', N'Social Themes / Self-Mutilation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058240 ', N'Social Themes / Sexual Abuse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058250 ', N'Social Themes / Suicide ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058260 ', N'Social Themes / Values & Virtues ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF058270 ', N'Social Themes / Violence ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059000 ', N'Sports & Recreation / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059010 ', N'Sports & Recreation / Baseball & Softball ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059020 ', N'Sports & Recreation / Basketball ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059030 ', N'Sports & Recreation / Camping & Outdoor Activities ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059040 ', N'Sports & Recreation / Equestrian ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059050 ', N'Sports & Recreation / Extreme Sports ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059060 ', N'Sports & Recreation / Football ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059070 ', N'Sports & Recreation / Gymnastics ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059080 ', N'Sports & Recreation / Hockey ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059090 ', N'Sports & Recreation / Martial Arts ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059100 ', N'Sports & Recreation / Skateboarding ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059110 ', N'Sports & Recreation / Soccer ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059120 ', N'Sports & Recreation / Track & Field ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059130 ', N'Sports & Recreation / Water Sports ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF059140 ', N'Sports & Recreation / Winter Sports ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF060000 ', N'Steampunk ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF061000 ', N'Superheroes ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF062000 ', N'Thrillers & Suspense ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF063000 ', N'Time Travel ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF064000 ', N'Travel & Transportation / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF064010 ', N'Travel & Transportation / Car & Road Trips ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF065000 ', N'Vampires ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF066000 ', N'Visionary & Metaphysical ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF067000 ', N'War & Military ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF068000 ', N'Werewolves & Shifters ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF069000 ', N'Westerns ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAF070000 ', N'Zombies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN000000 ', N'General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN001000 ', N'Activity Books ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN002000 ', N'Adventure & Adventurers ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN003000 ', N'Animals / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN003010 ', N'Animals / Animal Welfare ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN003020 ', N'Animals / Birds ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN003030 ', N'Animals / Marine Life ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN004000 ', N'Architecture ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN005000 ', N'Art / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN005010 ', N'Art / Cartooning ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN005020 ', N'Art / Drawing ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN005030 ', N'Art / Fashion ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN005040 ', N'Art / History ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN005050 ', N'Art / Painting ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN005060 ', N'Art / Sculpture ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN005070 ', N'Art / Techniques ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006000 ', N'Biography & Autobiography / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006010 ', N'Biography & Autobiography / Art ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006020 ', N'Biography & Autobiography / Cultural Heritage ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006030 ', N'Biography & Autobiography / Historical ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006040 ', N'Biography & Autobiography / Literary ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006050 ', N'Biography & Autobiography / Music ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006060 ', N'Biography & Autobiography / Performing Arts ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006070 ', N'Biography & Autobiography / Political ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006080 ', N'Biography & Autobiography / Presidents & First Families (U.S.) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006090 ', N'Biography & Autobiography / Religious ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006100 ', N'Biography & Autobiography / Royalty ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006110 ', N'Biography & Autobiography / Science & Technology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006120 ', N'Biography & Autobiography / Social Activists ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006130 ', N'Biography & Autobiography / Sports & Recreation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN006140 ', N'Biography & Autobiography / Women ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN007000 ', N'Body, Mind & Spirit ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN008000 ', N'Books & Libraries ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN009000 ', N'Boys & Men ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN010000 ', N'Business & Economics ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN011000 ', N'Careers ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN012000 ', N'Comics & Graphic Novels / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN012010 ', N'Comics & Graphic Novels / Biography ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN012020 ', N'Comics & Graphic Novels / History ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN013000 ', N'Computers / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN013010 ', N'Computers / Entertainment & Games ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN013020 ', N'Computers / Internet ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN013030 ', N'Computers / Programming ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN013040 ', N'Computers / Software ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN014000 ', N'Cooking & Food ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN015000 ', N'Crafts & Hobbies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN016000 ', N'Curiosities & Wonders ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN017000 ', N'Drama ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018000 ', N'Family / General (see also headings under Social Topics) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018010 ', N'Family / Adoption ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018020 ', N'Family / Alternative Family ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018030 ', N'Family / Marriage & Divorce ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018040 ', N'Family / Multigenerational ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018050 ', N'Family / Orphans & Foster Homes ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018060 ', N'Family / Parents ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018070 ', N'Family / Siblings ')
GO
print 'Processed 400 total records'
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN018080 ', N'Family / Stepfamilies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN019000 ', N'Fashion ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN020000 ', N'Foreign Language Study / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN020010 ', N'Foreign Language Study / English as a Second Language ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN020020 ', N'Foreign Language Study / French ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN020030 ', N'Foreign Language Study / Spanish ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN021000 ', N'Games & Activities / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN021010 ', N'Games & Activities / Puzzles & Word Games ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN021020 ', N'Games & Activities / Questions & Answers ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN022000 ', N'Gardening ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN023000 ', N'Girls & Women ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN024000 ', N'Health & Daily Living / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN024010 ', N'Health & Daily Living / Beauty & Grooming ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN024020 ', N'Health & Daily Living / Diet & Nutrition ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN024030 ', N'Health & Daily Living / Diseases, Illnesses & Injuries ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN024040 ', N'Health & Daily Living / Fitness & Exercise ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN024050 ', N'Health & Daily Living / Maturing ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN024060 ', N'Health & Daily Living / Physical Impairments ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN024070 ', N'Health & Daily Living / Safety ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025000 ', N'History / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025010 ', N'History / Africa ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025020 ', N'History / Ancient ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025030 ', N'History / Asia ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025040 ', N'History / Australia & Oceania ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025050 ', N'History / Canada ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025060 ', N'History / Central & South America ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025070 ', N'History / Europe ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025080 ', N'History / Exploration & Discovery ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025090 ', N'History / Holocaust ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025100 ', N'History / Medieval ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025110 ', N'History / Mexico ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025120 ', N'History / Middle East ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025130 ', N'History / Military & Wars ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025140 ', N'History / Modern ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025150 ', N'History / Prehistoric ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025160 ', N'History / Renaissance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025170 ', N'History / United States / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025180 ', N'History / United States / State & Local ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025190 ', N'History / United States / Colonial & Revolutionary Periods ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025200 ', N'History / United States / 19th Century ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025210 ', N'History / United States / Civil War Period (1850-1877) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025220 ', N'History / United States / 20th Century ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN025230 ', N'History / United States / 21st Century ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN026000 ', N'Holidays & Celebrations ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN027000 ', N'House & Home ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN028000 ', N'Humor ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN029000 ', N'Inspirational & Personal Growth ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN030000 ', N'Language Arts / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN030010 ', N'Language Arts / Communication ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN030020 ', N'Language Arts / Composition & Creative Writing ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN030030 ', N'Language Arts / Grammar ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN030040 ', N'Language Arts / Journal Writing ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN030050 ', N'Language Arts / Vocabulary & Spelling ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN031000 ', N'Law & Crime ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN032000 ', N'LGBT ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN033000 ', N'Literary Criticism & Collections ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN034000 ', N'Mathematics / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN034010 ', N'Mathematics / Algebra ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN034020 ', N'Mathematics / Geometry ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN035000 ', N'Media Studies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN036000 ', N'Media Tie-In ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN037000 ', N'Music / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN037010 ', N'Music / History ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN037020 ', N'Music / Instruction & Study ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN037030 ', N'Music / Popular ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN037040 ', N'Music / Rap & Hip Hop ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN037050 ', N'Music / Rock ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038000 ', N'People & Places / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038010 ', N'People & Places / Aboriginal & Indigenous ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038020 ', N'People & Places / Africa ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038030 ', N'People & Places / Asia ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038040 ', N'People & Places / Australia & Oceania ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038050 ', N'People & Places / Canada ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038060 ', N'People & Places / Caribbean & Latin America ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038070 ', N'People & Places / Europe ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038080 ', N'People & Places / Mexico ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038090 ', N'People & Places / Middle East ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038100 ', N'People & Places / United States / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038110 ', N'People & Places / United States / African American ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038120 ', N'People & Places / United States / Asian American ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038130 ', N'People & Places / United States / Hispanic & Latino ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN038140 ', N'People & Places / United States / Native American ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN039000 ', N'Performing Arts / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN039010 ', N'Performing Arts / Dance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN039020 ', N'Performing Arts / Film ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN039030 ', N'Performing Arts / Television & Radio ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN039040 ', N'Performing Arts / Theater & Musicals ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN040000 ', N'Personal Finance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN041000 ', N'Philosophy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN042000 ', N'Photography ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN043000 ', N'Poetry ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN044000 ', N'Public Speaking & Presentation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN045000 ', N'Recycling & Green Living ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN046000 ', N'Reference ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047000 ', N'Religion / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047010 ', N'Religion / Agnosticism & Atheism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047020 ', N'Religion / Biblical Stories & Studies ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047030 ', N'Religion / Buddhism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047040 ', N'Religion / Christianity ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047050 ', N'Religion / Eastern ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047060 ', N'Religion / Hinduism ')
GO
print 'Processed 500 total records'
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047070 ', N'Religion / Islam ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN047080 ', N'Religion / Judaism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN048000 ', N'Religious / Christian / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN048010 ', N'Religious / Christian / Dating ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN048020 ', N'Religious / Christian / Devotional & Prayer ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN048030 ', N'Religious / Christian / Family & Relationships ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN048040 ', N'Religious / Christian / Inspirational ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN049000 ', N'School & Education ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050000 ', N'Science & Nature / General (see also headings under Animals or Technology) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050010 ', N'Science & Nature / Anatomy & Physiology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050020 ', N'Science & Nature / Astronomy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050030 ', N'Science & Nature / Biology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050040 ', N'Science & Nature / Botany ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050050 ', N'Science & Nature / Chemistry ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050060 ', N'Science & Nature / Disasters ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050070 ', N'Science & Nature / Earth Sciences ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050080 ', N'Science & Nature / Environmental Conservation & Protection ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050090 ', N'Science & Nature / Environmental Science & Ecosystems ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050100 ', N'Science & Nature / Experiments & Projects ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050110 ', N'Science & Nature / History of Science ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050120 ', N'Science & Nature / Physics ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN050130 ', N'Science & Nature / Zoology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051000 ', N'Social Topics / General (see also headings under Family) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051010 ', N'Social Topics / Assimilation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051020 ', N'Social Topics / Bullying ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051030 ', N'Social Topics / Class Differences ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051040 ', N'Social Topics / Dating & Sex ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051050 ', N'Social Topics / Death & Dying ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051060 ', N'Social Topics / Depression & Mental Illness ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051070 ', N'Social Topics / Drugs, Alcohol, Substance Abuse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051080 ', N'Social Topics / Eating Disorders & Body Image ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051090 ', N'Social Topics / Emigration & Immigration ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051100 ', N'Social Topics / Emotions & Feelings ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051110 ', N'Social Topics / Friendship ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051120 ', N'Social Topics / Homelessness & Poverty ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051140 ', N'Social Topics / Manners & Etiquette ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051150 ', N'Social Topics / Peer Pressure ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051160 ', N'Social Topics / Physical & Emotional Abuse (see also Social Topics / Sexual Abuse) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051170 ', N'Social Topics / Pregnancy ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051180 ', N'Social Topics / Prejudice & Racism ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051190 ', N'Social Topics / Runaways ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051200 ', N'Social Topics / Self-Esteem & Self-Reliance ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051210 ', N'Social Topics / Self-Mutilation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051220 ', N'Social Topics / Sexual Abuse ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051230 ', N'Social Topics / Special Needs ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051240 ', N'Social Topics / Suicide ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051250 ', N'Social Topics / Values & Virtues ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN051260 ', N'Social Topics / Violence ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN052000 ', N'Social Science / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN052010 ', N'Social Science / Archaeology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN052020 ', N'Social Science / Customs, Traditions, Anthropology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN052030 ', N'Social Science / Folklore & Mythology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN052040 ', N'Social Science / Politics & Government ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN052050 ', N'Social Science / Psychology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN052060 ', N'Social Science / Sociology ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053000 ', N'Sports & Recreation / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053010 ', N'Sports & Recreation / Baseball & Softball ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053020 ', N'Sports & Recreation / Basketball ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053030 ', N'Sports & Recreation / Camping & Outdoor Activities ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053040 ', N'Sports & Recreation / Extreme Sports ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053050 ', N'Sports & Recreation / Football ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053060 ', N'Sports & Recreation / Hockey ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053070 ', N'Sports & Recreation / Martial Arts ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053080 ', N'Sports & Recreation / Motor Sports ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053090 ', N'Sports & Recreation / Olympics & Paralympics ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053100 ', N'Sports & Recreation / Soccer ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053110 ', N'Sports & Recreation / Track & Field ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN053120 ', N'Sports & Recreation / Winter Sports ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN054000 ', N'Study Aids / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN054010 ', N'Study Aids / Book Notes (see also STUDY AIDS / Book Notes) ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN054020 ', N'Study Aids / Test Preparation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN055000 ', N'Technology / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN055010 ', N'Technology / Aeronautics, Astronautics & Space Science ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN055020 ', N'Technology / Agriculture ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN055030 ', N'Technology / Electricity & Electronics ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN055040 ', N'Technology / Inventions ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN055050 ', N'Technology / Machinery & Tools ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN056000 ', N'Transportation / General ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN056010 ', N'Transportation / Aviation ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN056020 ', N'Transportation / Boats, Ships & Underwater Craft ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN056030 ', N'Transportation / Cars & Trucks ')
INSERT [dbo].[temp_sgt_bisaccodes_2015] ([Code], [Literal]) VALUES (N'YAN057000 ', N'Travel ')
go

		





	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	


go