/******************************************************************************************
**  Configures columns for the particiant by role 1,2,3 sections for Titles
*******************************************************************************************/

BEGIN

  DECLARE
  @v_itemtype     INT,
  @v_usageclass   INT,
  @v_datacode INT,
  @v_datasubcode INT,
  @v_classcode INT,
  @v_error_code   INT ,
  @v_taqrelationshipconfigkey INT,
  @v_error_desc   VARCHAR(2000) 

SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  1, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2 where datacode= 6 AND datasubcode= 1 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  2, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1 where datacode= 6 AND datasubcode= 2 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  3, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  6 where datacode= 6 AND datasubcode= 3 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  4, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3 where datacode= 6 AND datasubcode= 4 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  5, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 5 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  6, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 6 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  7, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 7 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  8, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4 where datacode= 6 AND datasubcode= 8 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  9, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5 where datacode= 6 AND datasubcode= 9 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  10, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 10 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  11, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 11 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  12, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 12 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  13, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 13 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  14, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1 where datacode= 6 AND datasubcode= 14 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  15, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 15 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 6,  16, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 6 AND datasubcode= 16 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
				
				
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  1, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2 where datacode= 7 AND datasubcode= 1 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  2, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1 where datacode= 7 AND datasubcode= 2 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  3, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  6 where datacode= 7 AND datasubcode= 3 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  4, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3 where datacode= 7 AND datasubcode= 4 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  5, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 5 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  6, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 6 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  7, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 7 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  8, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4 where datacode= 7 AND datasubcode= 8 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  9, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5 where datacode= 7 AND datasubcode= 9 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  10, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 10 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  11, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 11 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  12, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 12 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  13, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 13 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  14, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1 where datacode= 7 AND datasubcode= 14 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  15, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 15 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 7,  16, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 7 AND datasubcode= 16 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
				
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  1, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2 where datacode= 8 AND datasubcode= 1 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  2, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1 where datacode= 8 AND datasubcode= 2 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  3, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  6 where datacode= 8 AND datasubcode= 3 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  4, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3 where datacode= 8 AND datasubcode= 4 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  5, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 5 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  6, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 6 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  7, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 7 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  8, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4 where datacode= 8 AND datasubcode= 8 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  9, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5 where datacode= 8 AND datasubcode= 9 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  10, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 10 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  11, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 11 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  12, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 12 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  13, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 13 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  14, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1 where datacode= 8 AND datasubcode= 14 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  15, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 15 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 26	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 8,  16, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0 where datacode= 8 AND datasubcode= 16 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode		IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc


END
GO