DECLARE @v_windowid int

select @v_windowid = windowid from qsiwindows where windowname = 'productsummary'

update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.AgeHigh'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'txtAgeHigh'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.AgeLow'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'txtAgeLow'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.AllAgesInd'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'cbxAllAges'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.CopyRightYear'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'txtCopyRightYear'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.DiscountCode'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'ddlbDiscount'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.GradeHigh'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'ddlbGradeHigh'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.GradeLow'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'ddlbGradeLow'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.PublishToWebInd'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'cbxPublishToWeb'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.RestrictionCode'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'ddlbRestrictions'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.ReturnCode'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'ddlbReturns'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Classification.CanadianRestrictionCode'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'ddlbCanadianRestrictionCode'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'TerritoriesCode'
where windowid = @v_windowid and availobjectid='shClassification' and availobjectname = 'ddlbLegacyTerritories'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[1].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat01'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[2].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat02'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[3].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat03'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[4].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat04'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[5].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat05'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[6].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat06'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[7].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat07'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[8].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat08'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[9].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat09'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[10].CustomFloatValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomFloat10'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[1].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom01'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[2].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom02'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[3].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom03'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[4].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom04'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[5].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom05'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[6].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom06'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[7].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom07'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[8].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom08'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[9].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom09'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[10].CustomCodeValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'ddlbCustom10'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[1].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom01'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[2].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom02'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[3].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom03'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[4].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom04'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[5].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom05'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[6].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom06'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[7].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom07'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[8].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom08'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[9].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom09'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[10].CustomIndValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'cbxCustom10'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[1].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt01'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[2].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt02'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[3].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt03'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[4].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt04'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[5].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt05'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[6].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt06'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[7].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt07'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[8].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt08'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[9].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt09'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CustomFields[10].CustomIntValue'
where windowid = @v_windowid and availobjectid='shCustomFields' and availobjectname = 'txtCustomInt10'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Eloquence.EloApprovalCode', availobjectdesc = 'Eloquence Approval'
where windowid = @v_windowid and availobjectid='shEloquenceInfo' and availobjectname = 'ddlbContentServices'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Eloquence.EloCustomerKey'
where windowid = @v_windowid and availobjectid='shEloquenceInfo' and availobjectname = 'ddCustList'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'AnnouncedFirstPrintingActualInd'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'cbxAnncdFirstPrtgInd'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'AnnouncedFirstPrintingQty'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'txtAnncdFirstPrtg'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'BisacStatusCode'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'ddlbBisacStatus'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'CartonQty'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'txtCartonQty'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'ExpectedShipDate'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'txtExpectedShipDate'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'TitleStatusCode'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'ddlbInternalStatus'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'ProdAvailability'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'ddlbProductAvail'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'ReleaseQty'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'txtReleaseQty'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'ReleaseQtyActualInd'
where windowid = @v_windowid and availobjectid='shInventory' and availobjectname = 'cbxReleaseQtyInd'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Prices[].CurrencyTypeCode'
where windowid = @v_windowid and availobjectid='shPrices' and availobjectname = 'ddlbCurrencyTypeCodeEdit'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Prices[].TypeCode'
where windowid = @v_windowid and availobjectid='shPrices' and availobjectname = 'ddlbPriceTypeCodeEdit'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'PriceValidationGroup'
where windowid = @v_windowid and availobjectid='shPrices' and availobjectname = 'ddlbPriceValidation'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Prices[].BudgetPrice'
where windowid = @v_windowid and availobjectid='shPrices' and availobjectname = 'txtBudgetPriceEdit'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Prices[].FinalPrice'
where windowid = @v_windowid and availobjectid='shPrices' and availobjectname = 'txtFinalPriceEdit'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Format'
where windowid = @v_windowid and availobjectid='shProdSpecs' and availobjectname = 'ddlbMediaTypeSubCode'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'MediaTypeCode'
where windowid = @v_windowid and availobjectid='shProdSpecs' and availobjectname = 'ddlbMediaTypeCode'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'SpecItem'
where windowid = @v_windowid and availobjectid='shProdSpecs' and availobjectname = 'Spec Item'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'EditionType'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'ddlbEditionType'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Org1'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'lblDivisionImprint'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'ProductNumber'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'lblISBN'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'PubMonthCode'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'ddlbPubMonthCode'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'PubYear'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'txtPubYear'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'SeasonCode'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'ddlbSeason'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'ActualSeason'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'cbxActualSeasonInd'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'SeriesCode'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'ddlbSeriesCode'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'ShortTitle'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'txtShortTitle'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Subtitle'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'txtSubTitle'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'Title'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'txtTitle'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'TitlePrefix'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'txtTitlePrefix'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'VolumeNumber'
where windowid = @v_windowid and availobjectid='shTitleInfo' and availobjectname = 'txtVol1'
update securityobjectsavailable set availobjectid = 'Product', availobjectname = 'VerificationStatuses[].TitleVerifyStatusCode'
where windowid = @v_windowid and availobjectid='shVerificationStatus' and availobjectname = 'ddlbVerifyStatus'


