IF exists (select * from dbo.sysobjects where id = object_id(N'feed_date_conv') and xtype in (N'FN', N'IF', N'TF'))
  DROP FUNCTION feed_date_conv

GO


  CREATE 
    FUNCTION feed_date_conv 
      (
        @feed_date_string varchar(8000)
      ) 
      RETURNS datetime
    AS
      /*
       -- Generated by SQL Server Migration Assistant for Oracle
       --  Please, contact SSMAHELP@microsoft.com or visit http://www.microsoft.com/sql/migration for more information.
       --*/
      BEGIN

        DECLARE 
          @feed_date datetime,
          @feed_date_string2 varchar(12),
          @ll_year varchar(4),
          @i_length int,
          @ll_month varchar(3),
          @ll_day varchar(3)        

        BEGIN

          SET @i_length = 0

          SET @i_length = len(rtrim(@feed_date_string))

          IF (@i_length > 0)
            SET @ll_year = substring(@feed_date_string, 1, 4)

          SET @feed_date_string2 = substring(@feed_date_string, 6, 5)

          SET @i_length = 0

         -- SET @i_length = instr(@feed_date_string2, '/')
			 SET @i_length = charindex('/',@feed_date_string2)


          IF (@i_length > 0)
            BEGIN

              SET @ll_month = substring(@feed_date_string2, 1, @i_length - 1)

              IF (len(rtrim(@ll_month)) = 1)
                SET @ll_month = ('0' + isnull(@ll_month, ''))

              SET @ll_day = substring(@feed_date_string2, (@i_length + 1), 2)

              IF (len(rtrim(@ll_day)) = 1)
                SET @ll_day = ('0' + isnull(@ll_day, ''))

            END

          IF (@ll_month = '01')
            SET @ll_month = 'JAN'

          IF (@ll_month = '02')
            SET @ll_month = 'FEB'

          IF (@ll_month = '03')
            SET @ll_month = 'MAR'

          IF (@ll_month = '04')
            SET @ll_month = 'APR'

          IF (@ll_month = '05')
            SET @ll_month = 'MAY'

          IF (@ll_month = '06')
            SET @ll_month = 'JUN'

          IF (@ll_month = '07')
            SET @ll_month = 'JUL'

          IF (@ll_month = '08')
            SET @ll_month = 'AUG'

          IF (@ll_month = '09')
            SET @ll_month = 'SEP'

          IF (@ll_month = '10')
            SET @ll_month = 'OCT'

          IF (@ll_month = '11')
            SET @ll_month = 'NOV'

          IF (@ll_month = '12')
            SET @ll_month = 'DEC'

          SET @feed_date = (isnull(@ll_day, '') + '-' + isnull(@ll_month, '') + '-' + isnull(@ll_year, ''))

          RETURN @feed_date

        END


        RETURN null
      END

GO

