-- Remove embedded javascript from title comments
-- ISBNs: 1-4336-8450-0 1-4336-1724-2 0-8054-9670-X 1-4336-1350-6 0-8054-9671-8 1-4336-1365-4 1-4336-8843-3 1-4336-8840-9

update bookcomments set commenthtml = '<DIV><I>Beat God to the Punch</I> is for anyone who has ever asked, &quot;What does it mean to follow Jesus?&quot; Believers and unbelievers alike will find both comfort and challenge on the pages of Mason&#39;s work.<BR /></DIV>' 
where bookkey=7676974	and commenttypesubcode=7

update bookcomments set commenthtml = '<DIV>62,74&ndash;75</DIV>' 
where bookkey=8144340 and commenttypesubcode=40

update bookcomments set commenthtml = '<DIV><B>Tony Merida</B> is lead pastor of Imago Dei Church in Raleigh, North Carolina. He earned a Ph.D. in preaching from New Orleans Baptist Theological Seminary and serves as associate professor of Preaching at Southeastern Baptist Theological Seminary. His books include <I>Faithful Preaching</I> and <I>Orphanology</I>.</DIV>' 
where bookkey=8370924 and commenttypesubcode=10

update bookcomments set commenthtml = '<DIV>The<I> KJV Study Bible</I> honors the beauty and majesty of the KJV by presenting the <B>ONLY full-color</B><B>KJV study Bible available</B>.&#160;All of the features and tools are designed to help you understand the Bible and be transformed by it.&#160;Our hope is that you will use this study Bible to deepen your walk with God who has graciously revealed Himself in the Bible.<BR /> &#160;<BR /><B>Inside its over 2,400 pages you&rsquo;ll find</B>:<BR /> &#160;<BR /> &bull; 15,000 study notes<BR /> &bull; 141 photos, 62 timelines, 59 maps, 16 illustrations &amp; reconstructions and 15 charts<BR /> &bull; A 40-page concordance<BR /> &bull; 20 articles and essays<BR /> &bull; A helpful glossary of 17th century expressions relative to the KJV&rsquo;s signature phrasing<BR /> &bull; A two-column Bible text setting with center-column cross references<BR /> &bull; The words of Jesus in red<BR /> &bull; A one and three-year Bible reading plan<BR /> The<I> KJV Study Bible</I> honors the beauty and majesty of the KJV by presenting the <B>ONLY full-color</B><B>KJV study Bible available</B>.&#160;All of the features and tools are designed to help you understand the Bible and be transformed by it.&#160;Our hope is that you will use this study Bible to deepen your walk with God who has graciously revealed Himself in the Bible.<BR /> &#160;<BR /><B>Inside its over 2,400 pages you&rsquo;ll find</B>:<BR /> &#160;<BR /> &bull; 15,000 study notes<BR /> &bull; 141 photos, 62 timelines, 59 maps, 16 illustrations &amp; reconstructions and 15 charts<BR /> &bull; A 40-page concordance<BR /> &bull; 20 articles and essays<BR /> &bull; A helpful glossary of 17th century expressions relative to the KJV&rsquo;s signature phrasing<BR /> &bull; A two-column Bible text setting with center-column cross references<BR /> &bull; The words of Jesus in red<BR /> &bull; A one and three-year Bible reading plan<BR /> &#160;</DIV>' 
where bookkey=8431678 and commenttypesubcode=8

update bookcomments set commenthtml = '<DIV><B>Tony Merida</B> is lead pastor of Imago Dei Church in Raleigh, North Carolina. He earned a Ph.D. in preaching from New Orleans Baptist Theological Seminary and serves as associate professor of Preaching at Southeastern Baptist Theological Seminary. His books include <I>Faithful Preaching</I> and <I>Orphanology</I>.</DIV>' 
where bookkey=8434644 and commenttypesubcode=10

update bookcomments set commenthtml = '<DIV>The<I> KJV Study Bible</I> honors the beauty and majesty of the KJV by presenting the <B>ONLY full-color</B><B>KJV study Bible available</B>.&#160;All of the features and tools are designed to help you understand the Bible and be transformed by it.&#160;Our hope is that you will use this study Bible to deepen your walk with God who has graciously revealed Himself in the Bible.<BR /> &#160;<BR /><B>Inside its over 2,300 pages you&rsquo;ll find</B>:<BR /> &#160;<BR /> &bull; 15,000 study notes<BR /> &bull; 141 photos, 62 timelines, 59 maps, 16 illustrations &amp; reconstructions and 15 charts<BR /> &bull; A 40-page concordance<BR /> &bull; 20 articles and essays<BR /> &bull; A helpful glossary of 17th century expressions relative to the KJV&rsquo;s signature phrasing<BR /> &bull; A two-column Bible text setting with center-column cross references<BR /> &bull; The words of Jesus in red<BR /> &bull; A one and three-year Bible reading plan<BR /> &#160;</DIV>'
where bookkey=8466782	and commenttypesubcode=8

update bookcomments set commenthtml = '<DIV>En la serie <I>Heroes de la Fe</I>, Pablo Owen hace cobrar vida algunas figuras historicas de las Escrituras. Estos personajes nos cuentan sus propias historias y nos permiten verles en su contexto cultural e historico. En este volumen, el joven rey David nos cuenta de sus altas y bajas y&#160;ayuda al lector a hallar en &eacute;l un admirable heroe de la vida real. &#160;<BR /><BR /> In the <I>Champions of the Faith</I> series, Paul Owen brings to life historical figures from Scriptures. These characters tell us their own stories and helps us see them in their historical and cultural context. In this volume, young king David tells us of his highs and lows and helps the reader find in him a real life hero he can look to.</DIV>' 
where bookkey=8488797	and commenttypesubcode=7

update bookcomments set commenthtml = '<DIV>En la serie <I>Heroes de la Fe</I>, Pablo Owen hace cobrar vida algunas figuras historicas de las Escrituras. Estos personajes nos cuentan sus propias historias y nos permiten verles en su contexto cultural e historico. En este volumen, el joven rey David nos cuenta de sus altas y bajas y&#160;ayuda al lector a hallar en &eacute;l un admirable heroe de la vida real. &#160;<BR /><BR /> In the <I>Champions of the Faith</I> series, Paul Owen brings to life historical figures from Scriptures. These characters tell us their own stories and helps us see them in their historical and cultural context. In this volume, young king David tells us of his highs and lows and helps the reader find in him a real life hero he can look to.</DIV>' 
where bookkey=8488976 and commenttypesubcode=7