IF exists (select * from dbo.sysobjects where id = object_id(N'feed_in_title_info2') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
  DROP PROCEDURE feed_in_title_info2

GO

  CREATE 
    PROCEDURE feed_in_title_info2
    AS
      /*
       -- Generated by SQL Server Migration Assistant for Oracle
       --  Please, contact SSMAHELP@microsoft.com or visit http://www.microsoft.com/sql/migration for more information.
       --*/
      BEGIN
          DECLARE 
            @err_msg char(200),
            @feed_system_date datetime,
            @feedin_bookkey INT,
            @feedin_authorkey INT,
            @feedin_bisactatus varchar(10),
            @feedin_bisacstatus_old INT,
            @feedin_count INT,
            @feedin_retailprice numeric(9, 2),
            @feedin_canadianprice numeric(9, 2),
            @feedin_pubstring varchar(11),
            @feedin_pubdate datetime,
            @feedin_reldate datetime,
            @feedin_categorycode numeric(7, 0),
            @feed_isbn varchar(13),
            @feed_isbn10 varchar(10),
            @feedin_title varchar(80),
            @feedin_shorttitle varchar(24),
            @feedin_subtitle varchar(255),
            @feedin_authorlast varchar(25),
            @feed_prepackind char(1),
            @feedin_temp_isbn varchar(8),
            @feedin_isbn_prefix numeric(7, 0),
            @feedin_pubmonthcode numeric(10, 0),
            @feedin_price_temp numeric(9, 2),
            @feedin_canadianrestriction numeric(10, 0),
            @feedin_pubtowebind numeric(3, 0),
            @feedin_year numeric(5, 0),
            @feedin_discount numeric(10, 0),
            @feed_pricekey numeric(10, 0),
            @feed_pricecount numeric(3, 0),
            @feed_pricefound numeric(1, 0),
            @feed_orgentry_college numeric(3, 0),
            @feedin_net numeric(9, 2),
            @cursor_row_isbn varchar(8000),
            @cursor_row_bisacstatuscode varchar(10),
            @cursor_row_retailprice varchar(20),
            @cursor_row_retailprice2 numeric(9,2),
            @cursor_row_canadianprice varchar(20),
            @cursor_row_canadianprice2 numeric(9,2),
            @cursor_row_categorycode varchar(12),
            @cursor_row_pubdate varchar(12),
            @cursor_row_reldate varchar(12),
            @cursor_row_cartonqty varchar(10),
            @cursor_row_projectisbn varchar(20),
            @cursor_row_canadianrestriction varchar(10),
            @cursor_row_discountcode varchar(10),
            @cursor_row_nextisbn varchar(8000),
            @cursor_row_pricekey INT,
            @cursor_row_activeind INT,
            @cursor_row_listprice INT,
            @cursor_row_pricekey2 INT,
            @cursor_row_activeind2 INT,
            @errordesc varchar(100),
            @feedin_cartonqty FLOAT,
            @v_newkey INT
     
          SET @feedin_count = 0
          SET @feed_prepackind = 'N'
          SET @feedin_isbn_prefix = 0
          SET @feedin_pubmonthcode = 0
          SET @feedin_price_temp = 0
          SET @feedin_canadianrestriction = 0
          SET @feedin_pubtowebind = 0
          SET @feedin_year = 0
          SET @feedin_discount = 0
          SET @feed_orgentry_college = 0
          BEGIN

            SELECT @feed_system_date = getdate()

            /*  run titles feed from here  */
				INSERT INTO feederror(batchnumber, processdate,errordesc,detailtype)
              VALUES ('3', @feed_system_date,'Feed Summary: Inserts', 0)

            INSERT INTO feederror(batchnumber, processdate,errordesc,detailtype)
				VALUES ('3', @feed_system_date,'Feed Summary: Updates', 0)

				INSERT INTO feederror(batchnumber, processdate,errordesc,detailtype)
					VALUES ('3', @feed_system_date,'Feed Summary: Rejected', 0)
      

            BEGIN
     
              DECLARE 
                feed_titles CURSOR LOCAL 
                 FOR 
                  SELECT DISTINCT 
                      t.ISBN, 
                      isnull(CASE (t.bisacstatuscode + '.') WHEN '.' THEN NULL ELSE t.bisacstatuscode END, '') AS bisacstatuscode, 
                      isnull(CASE (t.retailprice + '.') WHEN '.' THEN NULL ELSE t.retailprice END, '0') AS retailprice, 
                      isnull(CASE (t.canadianprice + '.') WHEN '.' THEN NULL ELSE t.canadianprice END, '0') AS canadianprice, 
                      isnull(CASE (t.categorycode + '.') WHEN '.' THEN NULL ELSE t.categorycode END, '0') AS categorycode, 
                      isnull(CASE (t.pubdate + '.') WHEN '.' THEN NULL ELSE t.pubdate END, '') AS pubdate, 
                      isnull(CASE (t.reldate + '.') WHEN '.' THEN NULL ELSE t.reldate END, '') AS reldate, 
                      isnull(CASE (t.cartonqty + '.') WHEN '.' THEN NULL ELSE t.cartonqty END, '0') AS cartonqty, 
                      isnull(CASE (t.projectisbn + '.') WHEN '.' THEN NULL ELSE t.projectisbn END, '') AS projectisbn, 
                      isnull(CASE (t.canadianrestriction + '.') WHEN '.' THEN NULL ELSE t.canadianrestriction END, '') AS canadianrestriction, 
                      isnull(CASE (t.discountcode + '.') WHEN '.' THEN NULL ELSE t.discountcode END, '') AS discountcode, 
                      isnull(CASE (t.nextisbn + '.') WHEN '.' THEN NULL ELSE t.nextisbn END, '') AS nextisbn
                    FROM feedin_titles2 t, isbn i
                    WHERE (i.isbn10 = t.isbn)
                  ORDER BY t.isbn
              

              OPEN feed_titles

              FETCH NEXT FROM feed_titles
                INTO @cursor_row_isbn, @cursor_row_bisacstatuscode, @cursor_row_retailprice, @cursor_row_canadianprice, 
                  @cursor_row_categorycode,@cursor_row_pubdate, @cursor_row_reldate, @cursor_row_cartonqty, 
                  @cursor_row_projectisbn, @cursor_row_canadianrestriction,@cursor_row_discountcode,@cursor_row_nextisbn

              WHILE  NOT(@@FETCH_STATUS = -1)
                BEGIN

						IF (@@FETCH_STATUS = -1)
					   BEGIN
	
						  INSERT INTO feederror(isbn,batchnumber, processdate,errordesc,detailtype)
							   VALUES (@cursor_row_isbn,'3', @feed_system_date,'NO ROWS to PROCESS', 0)
						  BREAK
					   END

                  

                  SET @feedin_bisactatus = 0
                  SET @feedin_count = 0
                  SET @feedin_isbn_prefix = 0
                  SET @feedin_price_temp = ''
                  SET @feedin_bookkey = 0
                  SET @feedin_authorkey = 0
                  SET @feedin_retailprice = 0
                  SET @feedin_canadianprice = 0
                  SET @feedin_pubstring = ''
                  SET @feedin_pubdate = ''
                  SET @feedin_reldate = ''
                  SET @feed_isbn = ''
                  SET @feedin_title = ''
                  SET @feedin_shorttitle = ''
                  SET @feedin_subtitle = ''
                  SET @feedin_authorlast = ''
                  SET @feedin_temp_isbn = ''
                  SET @feedin_price_temp = ''
                  SET @feedin_pubmonthcode = 0
                  SET @feedin_categorycode = 0
                  SET @feedin_canadianrestriction = 0
                  SET @feedin_bisacstatus_old = 0
                  SET @feedin_pubtowebind = 0
                  SET @feedin_net = 0
                  SET @feed_isbn = rtrim(@cursor_row_isbn)
                  SET @feed_isbn10 = rtrim(@cursor_row_isbn)
                  /* 11-05-02  THIS IS JUST TO INSERT ERROR ROWS INTO RERUN TABLE */
                  SET @feed_pricekey = 0
                  SET @feed_pricecount = 0

                  /*
                   -- ************  8-29-01    no not check if isbn good it should be  skip all of this
                   -- 	 if length(feed_isbn) = 0 then
                   -- 		feed_isbn := 'NO ISBN';
                   -- 		insert into qsidba.feederror
                   -- 			(isbn,batchnumber,processdate,errordesc)
                   -- 		values (rtrim(cursor_row.isbn,' '),'3',feed_system_date,('NO ISBN ENTERED ' || rtrim(cursor_row.isbn,' ')));
                   -- 		update qsidba.feederror
                   -- 			set detailtype = (detailtype + 1)
                   -- 				where batchnumber='3'
                   -- 					  and processdate LIKE feed_system_date ||'%'
                   -- 					 and errordesc='Feed Summary2: Rejected';
                   -- 			commit;
                   -- 	else
                   -- 		feed_isbn := qsidba.isbn_13(RTRIM(cursor_row.isbn,' '),'3');
                   -- 		if feed_isbn = 'NO ISBN' then
                   -- 			insert into qsidba.feederror
                   -- 				(isbn,batchnumber,processdate,errordesc)
                   -- 			values (rtrim(cursor_row.isbn,' '),'3',feed_system_date,('NO ISBN ENTERED ' || rtrim(cursor_row.isbn,' ')));
                   -- 			update qsidba.feederror
                   -- 				set detailtype = (detailtype + 1)
                   -- 					where batchnumber='3'
                   -- 						and processdate LIKE feed_system_date ||'%'
                   -- 						 and errordesc='Feed Summary2: Rejected';
                   -- 			commit;
                   -- 		end if;
                   -- 	end if;
                   -- 	select count(*)
                   -- 		into feedin_bookkey
                   -- 			from qsidba.isbn i, qsidba.book b
                   -- 				where i.bookkey= b.bookkey
                   -- 					and (b.reuseisbnind is null or reuseisbnind = 0)
                   -- 						and isbn10=rtrim(cursor_row.isbn,' ');
                   -- 	if feedin_bookkey = 0  then
                   -- 		feedin_bookkey := 0;
                   -- 		if feed_isbn <> 'NO ISBN' then
                   -- 			feedin_count := 0;
                   -- 			feedin_count := instr(feed_isbn,'-',1,2);
                   -- 			feedin_count := feedin_count -1;
                   -- 			feedin_temp_isbn:= substr(feed_isbn,1,feedin_count);
                   -- 			select datacode
                   -- 				into feedin_isbn_prefix
                   -- 					from qsidba.gentables
                   -- 						where datadesc = feedin_temp_isbn
                   -- 							and tableid=138;
                   -- 		end if;
                   -- 	else
                   -- end ******
                   --*/

                  /*  remove reissue isbn book keys */

                  /* 11-19-02  duplicate isbns are present so just get the first one entered */

						SET @feedin_count = 0

                  SELECT @feedin_count = count(*)
                    FROM isbn i, book b
                    WHERE i.bookkey = b.bookkey AND 
                          ((b.reuseisbnind IS NULL) OR (b.reuseisbnind = 0)) AND 
                           i.isbn10 = RTRIM(@cursor_row_isbn)

                  

                  IF @feedin_count > 1
                   BEGIN  -- duplicate get lowest isbn 
                      SELECT @feedin_bookkey = min(b.bookkey), 
                             @feed_isbn = min(i.isbn)
                        FROM isbn i, book b
                        WHERE i.bookkey = b.bookkey AND 
                                ((b.reuseisbnind IS NULL) OR (b.reuseisbnind = 0)) AND 
                                i.isbn10 = RTRIM(@cursor_row_isbn)

					       SET @errordesc = '(Duplicate isbn on isbn table isbn = ' + isnull(@err_msg,'') + isnull(@feed_isbn,'') + ')'
		
                      INSERT INTO feederror(batchnumber, processdate,errordesc)
					         VALUES ('3', @feed_system_date, @errordesc)
                    END
                    ELSE 
                    BEGIN
                      SELECT @feedin_bookkey = b.bookkey, @feed_isbn = i.isbn
                        FROM isbn i, book b
                        WHERE i.bookkey = b.bookkey AND 
                             ((b.reuseisbnind IS NULL) OR (b.reuseisbnind = 0)) AND 
                              i.isbn10 = RTRIM(@cursor_row_isbn)
                    END


                  IF datalength(@feed_isbn) = 13
                    BEGIN

                      /* ------------- intialize data for new or old ------- */

                      /* bisacstatus */

                      SET @feedin_count = 0

							 SELECT @feedin_count = count( * )
                        FROM gentables
                        WHERE gentables.externalcode = @cursor_row_bisacstatuscode AND gentables.tableid = 314

                      IF (@feedin_count > 0)
                      BEGIN
                          SELECT @feedin_bisactatus = gentables.datacode
                            FROM gentables
                            WHERE gentables.externalcode = @cursor_row_bisacstatuscode AND gentables.tableid = 314
                      END
							 ELSE 
							 BEGIN
								 SET @feedin_bisactatus = 0
								 INSERT INTO feederror(isbn,batchnumber, processdate,errordesc)
									 VALUES (@cursor_row_isbn,'3', @feed_system_date,('BISAC STATUS NOT ON gentables; BISAC STATUS NOT UPDATED ' + isnull(@cursor_row_bisacstatuscode, '')))
							 END
							
                     /*  11-26-02  force BSB to AS datacode; 16 to 1 */
							IF LTRIM(RTRIM(@cursor_row_bisacstatuscode)) = 'BSB'
							 BEGIN
                        SET @feedin_bisactatus = 1
 							   SELECT @feedin_count = count( * )
								  FROM bookdetail b, gentables g
								 WHERE b.bookkey = @feedin_bookkey AND bisacstatuscode = g.datacode AND g.tableid = 314

								 IF (@feedin_count > 0)
									BEGIN
									  SELECT @feedin_bisacstatus_old = g.datacode, @feedin_pubtowebind = isnull(b.publishtowebind, 0)
										 FROM bookdetail b, gentables g
										  WHERE b.bookkey = @feedin_bookkey AND bisacstatuscode = g.datacode AND g.tableid = 314
									END
                      END

                      /*  retail prices */

                       IF len(@cursor_row_retailprice) > 0
								BEGIN
									  SET @feedin_price_temp = convert(float,@cursor_row_retailprice)
									  
									  IF @feedin_price_temp > 0
									  BEGIN
										  SET @feedin_retailprice = @feedin_price_temp
									  END
									  ELSE 
									  BEGIN
										 SET @feedin_retailprice = 0
									  END
								 END

								 IF len(@cursor_row_canadianprice) > 0
								 BEGIN
									  SET @feedin_price_temp = convert(float,@cursor_row_canadianprice)
									  IF @feedin_price_temp > 0
										 BEGIN
											SET @feedin_canadianprice = @feedin_price_temp
										 END
									  ELSE 
									  BEGIN
										 SET @feedin_canadianprice = 0
									  END
								 END


                      /*
                       -- NET PRICE NOT ON FEED TABLE AS YET UNCOMMENT WHEN ADDED
                       -- 	feedin_price_temp := '';
                       -- 		if length(RTRIM(LTRIM(cursor_row.netprice,' '),' ')) > 0 then
                       -- 			feedin_price_temp := RTRIM(LTRIM(cursor_row.netprice,' '),' ');
                       -- 			if length(feedin_price_temp) >0 then
                       -- 				feedin_net   := to_number(feedin_price_temp);
                       -- 			else
                       -- 				feedin_net := 0;
                       -- 			end if;
                       -- 		end if;
                       --*/

                      /* dates  */
							 -- Publication Date
                      IF datalength(@cursor_row_pubdate) > 0
                        SET @feedin_pubdate = dbo.feed_date_conv(rtrim(ltrim(@cursor_row_pubdate)))
                      ELSE 
                        SET @feedin_pubdate = ''

                      -- Release Date
                      IF datalength(@cursor_row_reldate) > 0
                        SET @feedin_reldate = dbo.feed_date_conv(rtrim(ltrim(@cursor_row_reldate)))
                      ELSE 
                        SET @feedin_reldate = '' 

                      /*  4-1-04 comment */

                      /*
                       -- if length(feedin_pubdate) > 0 then
                       -- 		feedin_pubmonthcode := to_number(to_char(feedin_pubdate,'MM')) ;
                       -- 	end if;
                       --*/

                      /*  canadian restrictionrictions  getting datacode instead of description */
                      SELECT @feedin_count = 0

                      IF len(@cursor_row_canadianrestriction) > 0
                      BEGIN

                          SELECT @feedin_count = count(*)
                            FROM gentables
                            WHERE gentables.externalcode = convert(char,@cursor_row_canadianrestriction) AND 
                                  gentables.tableid = 428
									                          
                          IF @feedin_count > 0
                          BEGIN
                              SELECT @feedin_canadianrestriction = gentables.datacode
                                FROM gentables
                                WHERE gentables.externalcode = convert(char,@cursor_row_canadianrestriction) AND 
                                  gentables.tableid = 428
									END
									ELSE 
									BEGIN  
										 INSERT INTO feederror(isbn,batchnumber, processdate,errordesc)
									      VALUES (@cursor_row_isbn,'3', @feed_system_date,('CANADIANRESTRICTION NOT ON 			GENTABLES; CANADIANRESTRICTION NOT UPDATED ' + isnull(@cursor_row_canadianrestriction, '')))
									END
                       END
							 ELSE 
                        SET @feedin_canadianrestriction = 0
                   
                      /*  6-28-02 discount code  */
							 SELECT @feedin_count = 0

                      IF len(@cursor_row_discountcode) > 0
                      BEGIN

                          SELECT @feedin_count = count( * )
                            FROM gentables
                           WHERE gentables.externalcode = convert(char,(@cursor_row_discountcode)) AND 
                                 gentables.tableid = 459

                          IF (@feedin_count > 0)
                          BEGIN
                              SELECT @feedin_discount = gentables.datacode
                                FROM gentables
                               WHERE gentables.externalcode = convert(char,(@cursor_row_discountcode)) AND 
                                     gentables.tableid = 459

                          END
                          ELSE 
                          BEGIN
                             EXEC feed_insert_gentables 459, @cursor_row_discountcode, @feedin_discount OUTPUT
								  END
                      END
                      ELSE 
                        SET @feedin_discount = 0
       
                      /*  --------------start updating existing title  record ---------- */

                      IF (@feedin_bookkey > 0)
                        BEGIN

                          /*  ------------------start updating tables---------------- */

                          SET @feedin_count = 0

                          SELECT @feedin_count = count( * )
                            FROM bookdetail
                            WHERE (bookdetail.bookkey = @feedin_bookkey)

                          IF ((@@ROWCOUNT = 0) AND (@feedin_count = 0))
                            INSERT INTO bookdetail
                              (bookdetail.bookkey, bookdetail.lastuserid,bookdetail.lastmaintdate)
                              VALUES (@feedin_bookkey, 'VISTAFEED2', @feed_system_date)

                          IF (@feedin_bisactatus > 0)
                            BEGIN

                              UPDATE feederror
                                SET detailtype = (detailtype + 1)
                                WHERE ((batchnumber= '3') AND 
                                        (processdate LIKE (isnull(CAST( @feed_system_date AS varchar(8000)), '') + '%')) AND 
                                        (errordesc = 'Feed Summary2: Updates'))

                              EXEC dbo.TITLEHISTORY_INSERT 4, @feedin_bookkey, 0, '', @feedin_bisactatus

										UPDATE bookdetail
                                SET bisacstatuscode = @feedin_bisactatus, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                WHERE bookkey = @feedin_bookkey 
                              
                            END

                          /*
                           -- 9-4-03 update discountcode if pss5 value is null or 0 regardless of status
                           -- 8-4-04 update regardless if on pss5 or not
                           --*/

                          /*
                           -- feedin_count := 0;
                           -- 	select nvl(discountcode,0) into feedin_count from bookdetail where bookkey = feedin_bookkey;
                           -- 	if feedin_count = 0 and
                           --*/
          					  IF (@feedin_discount > 0)
                          BEGIN
                              EXEC TITLEHISTORY_INSERT 90, @feedin_bookkey, 0, '', @feedin_discount 
                              UPDATE bookdetail
                                  SET discountcode = @feedin_discount, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                  WHERE bookkey = @feedin_bookkey
                          END
									

                          /* ***********************update titles that are not NYP,PC, PP, NAB ************** */
								  IF @cursor_row_bisacstatuscode <> 'NYP' AND 
                             @cursor_row_bisacstatuscode <> 'NAB' AND 
                             @cursor_row_bisacstatuscode <> 'PC' AND 
                             @cursor_row_bisacstatuscode <> 'PP'
                            BEGIN
                              /* cartonqty */
										SELECT @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bindingspecs
                                WHERE bookkey = @feedin_bookkey AND printingkey = 1
                      

                              IF convert(float, @cursor_row_cartonqty ) > 0
                              BEGIN
                                IF @feedin_count > 0
                                  BEGIN
                                                                     
                                    SELECT @feedin_cartonqty = convert(float,@cursor_row_cartonqty)

                                    EXEC TITLEHISTORY_INSERT 89, @feedin_bookkey, 1, '', @feedin_cartonqty

                                    UPDATE bindingspecs
                                      SET cartonqty1 = @feedin_cartonqty, 
                                          lastuserid = 'VISTAFEED2', 
                                          lastmaintdate = @feed_system_date
                                    WHERE bookkey = @feedin_bookkey AND printingkey = 1
                                  END
											 END
											 ELSE 
											 BEGIN
													SELECT @feedin_cartonqty = convert(float,@cursor_row_cartonqty)
	
													EXEC TITLEHISTORY_INSERT 89, @feedin_bookkey, 1, '', @feedin_cartonqty
	
													INSERT INTO bindingspecs(bookkey,printingkey,vendorkey,cartonqty1)
													  VALUES (@feedin_bookkey, 1, 0, @feedin_cartonqty)
	
											 END
									   END



										-- retail price 
                              SELECT @feedin_count = 0
                              /*  list price code is datacode 11 */
                              SELECT @feedin_count = count( * )
                                FROM bookprice
                                WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11

                              IF @feedin_retailprice > 0
                                BEGIN
                                  --  8-27-03 update active row if more than 1 row present -
                                  IF @feedin_count > 0
                                  BEGIN
                                    IF @feedin_count > 1
                                    BEGIN

                                        SELECT @feed_pricecount = count( * )
                                          FROM bookprice
                                          WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11 AND activeind = 1


                                        IF (@feed_pricecount = 1)
                                        BEGIN
                                            EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '6', @feedin_retailprice
 
                                            UPDATE bookprice
                                              SET finalprice = @feedin_retailprice, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                              WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11 AND activeind = 1
                                        END
                                        ELSE 
                                        BEGIN
                                             -- no rows have activeind or all rows have activeind=1
                                             -- 4-1-04  a) if price in match one of bookprice rows finalprice; set that row to active=1  or
                                             --  			set all others to empty (this is the current selling price .. no need to do history
                                             --				since not updating value
                                             --  		b) if price in does not match any then send to error report
                                            
                                            SET @feed_pricefound = 0
                                              DECLARE feed_retailprice CURSOR 
                                              FOR 
                                              SELECT pricekey, activeind, CASE finalprice WHEN  NULL THEN BUDGETPRICE ELSE finalprice END AS LISTPRICE
                                                FROM bookprice
                                               WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11 
                                             
                                              OPEN feed_retailprice

                                              FETCH NEXT FROM feed_retailprice INTO @cursor_row_pricekey, @cursor_row_activeind, @cursor_row_retailprice2

                                              WHILE  NOT(@@FETCH_STATUS = -1)
                                                BEGIN
                                                  IF (@@FETCH_STATUS = 0)
                                                    IF (@cursor_row_retailprice2 = @feedin_retailprice)
                                                      BEGIN

                                                        UPDATE bookprice
                                                          SET activeind = 1, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                                          WHERE pricekey = @cursor_row_pricekey

                                                        /* make the rest activeind null */

                                                        UPDATE bookprice
                                                          SET activeind =  NULL, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                                          WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11 AND activeind = 1 AND 
                                                                pricekey = @cursor_row_pricekey

                                                        SET @feed_pricefound = 1

                                                      END
                                                  FETCH NEXT FROM feed_retailprice INTO @cursor_row_pricekey, @cursor_row_activeind, @cursor_row_retailprice2
                                                END
                                              CLOSE feed_retailprice
                                              DEALLOCATE feed_retailprice
                                            END
                                      END
                                    ELSE  -- feedin_count = 1
                                      BEGIN
                                        EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '6', @feedin_retailprice 

                                        UPDATE bookprice
                                          SET 
                                            finalprice = @feedin_retailprice, 
                                            activeind = 1, 
                                            lastuserid = 'VISTAFEED2', 
                                            lastmaintdate = @feed_system_date
                                          WHERE ((bookkey = @feedin_bookkey) AND (currencytypecode = 6) AND (pricetypecode = 11))
                                      END
                                  END
                                  ELSE  -- feedin_count = 0 
                                  BEGIN
                                      EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '6', @feedin_retailprice
									 			  select @v_newkey = generickey from keys
 
                                      INSERT INTO bookprice(pricekey,bookkey,pricetypecode,currencytypecode,activeind,finalprice, 
                                          effectivedate, lastuserid,lastmaintdate)
                                        VALUES (@v_newkey,@feedin_bookkey,11,6, 1,@feedin_retailprice, 
                                            @feed_system_date, 'VISTAFEED2',@feed_system_date)
                                    END
                                END
  										END

                              /* canada */

                              /* JS activited Canadian Price */

                              /* 7-27-04 do not update canada price for college titles */

                              SET @feed_orgentry_college = 0

                              SELECT @feed_orgentry_college = count( * )
                                FROM bookorgentry
                                WHERE orglevelkey = 1 AND orgentrykey = 1485 AND bookkey = @feedin_bookkey

                              IF (@feed_orgentry_college = 0)
                                BEGIN

                                  SET @feedin_count = 0

                                  SET @feed_pricecount = 0

                                  SELECT @feedin_count = count( * )
                                    FROM bookprice
                                    WHERE bookkey = @feedin_bookkey AND currencytypecode = 11 AND pricetypecode = 11

                                  IF (@feedin_canadianprice > 0)
                                    IF (@feedin_count > 0)
                                      IF (@feedin_count > 1)
                                        BEGIN
                                          SELECT @feed_pricecount = count( * )
                                            FROM bookprice
                                            WHERE bookkey = @feedin_bookkey AND currencytypecode = 11 AND pricetypecode = 11 AND
                                                    activeind = 1

                                          IF (@feed_pricecount = 1)
                                            BEGIN
                                              EXEC dbo.TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '11', @feedin_canadianprice 

                                              UPDATE bookprice
                                                SET finalprice = @feedin_canadianprice, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                                WHERE bookkey = @feedin_bookkey AND currencytypecode = 11 AND pricetypecode = 11 AND
                                                    activeind = 1
                                            END
                                          ELSE 
                                            BEGIN
                                              SET @feed_pricefound = 0
                                              BEGIN
                                                                                      

                                                DECLARE  feed_canadaprice CURSOR LOCAL 
                                                   FOR 
                                                    SELECT pricekey, activeind, CASE finalprice WHEN  NULL THEN budgetprice ELSE finalprice END AS canadaprice
                                                      FROM bookprice
                                                     WHERE bookkey = @feedin_bookkey AND currencytypecode = 11 AND pricetypecode = 11

                                                

                                                OPEN feed_canadaprice

                                                FETCH NEXT FROM feed_canadaprice INTO @cursor_row_pricekey, @cursor_row_activeind, @cursor_row_canadianprice2

                                                WHILE  NOT(@@FETCH_STATUS = -1)
                                                  BEGIN
                                                    IF (@@FETCH_STATUS = 0)
                                                      IF (@cursor_row_canadianprice2 = @feedin_canadianprice)
                                                        BEGIN

                                                          UPDATE bookprice
                                                          SET activeind = 1, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                                          WHERE pricekey = @cursor_row_pricekey

                                                          UPDATE bookprice
                                                          SET activeind =  NULL, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                                          WHERE bookkey = @feedin_bookkey AND currencytypecode = 11 AND pricetypecode = 11 AND activeind = 1 AND 
                                                                pricekey = @cursor_row_pricekey

                                                          SET @feed_pricefound = 1

                                                        END
                                                    FETCH NEXT FROM feed_canadaprice INTO @cursor_row_pricekey, @cursor_row_activeind, @cursor_row_canadianprice2
                                                  END

                                                CLOSE feed_canadaprice
                                                DEALLOCATE feed_canadaprice

                                              END
                                            END
                                        END
                                      ELSE 
                                        BEGIN
                                          EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '11', @feedin_canadianprice 
                                          UPDATE bookprice
                                             SET finalprice = @feedin_canadianprice,activeind = 1,lastuserid = 'VISTAFEED2',lastmaintdate = @feed_system_date
                                            WHERE bookkey = @feedin_bookkey AND currencytypecode = 11 AND pricetypecode = 11
                                        END
                                    ELSE 
                                      BEGIN
                                        EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '11', @feedin_canadianprice

													 select @v_newkey = generickey from keys
 
                                        INSERT INTO bookprice
                                          (pricekey,bookkey,pricetypecode,currencytypecode,activeind,finalprice,effectivedate,lastuserid,lastmaintdate)
                                            VALUES(@v_newkey,@feedin_bookkey,11,11,1,@feedin_canadianprice,@feed_system_date,'VISTAFEED2',@feed_system_date)
                                      END

                                END

                              /*
                               -- 8-4-04 net price not added as yet
                               -- feedin_count := 0;
                               -- feed_pricecount := 0;
                               -- 
                               -- 			select count(*)
                               -- 				into feedin_count
                               -- 					from qsidba.bookprice
                               -- 						where bookkey=feedin_bookkey
                               -- 							and currencytypecode=6
                               -- 							and pricetypecode=9;
                               -- 			if feedin_net > 0 then
                               -- 				if feedin_count>0  then
                               -- 				   if feedin_count > 1 then
                               -- 				    	select count(*) into feed_pricecount
                               -- 						from qsidba.bookprice
                               -- 							where bookkey=feedin_bookkey
                               -- 								and currencytypecode=6
                               -- 								and pricetypecode=9 and activeind= 1;
                               -- 
                               -- 			   		if feed_pricecount = 1 then
                               -- 						titlehistory_insert(9,feedin_bookkey,0,'9',feedin_net);
                               -- 						update qsidba.bookprice
                               -- 							set finalprice = feedin_net,
                               -- 								lastuserid='VISTAFEED',
                               -- 								lastmaintdate = feed_system_date
                               -- 									where bookkey=feedin_bookkey
                               -- 										and currencytypecode=6
                               -- 										and pricetypecode=9 										and activeind= 1;
                               -- 					else
                               -- 						feed_pricefound :=0;
                               -- 
                               -- 						FOR  cursor_row3 in feed_netprice loop
                               -- 							if feed_netprice%FOUND then
                               -- 								if cursor_row3.netprice = feedin_net  then
                               -- 									update qsidba.bookprice
                               -- 									  set activeind = 1,
                               -- 										lastuserid='VISTAFEED',
                               -- 										lastmaintdate =feed_system_date
                               -- 										  where pricekey = cursor_row3.pricekey;
                               -- 
                               -- 									update qsidba.bookprice
                               -- 									  set activeind = null,
                               -- 									    lastuserid='VISTAFEED',
                               -- 									    lastmaintdate= feed_system_date
                               -- 									      where bookkey=feedin_bookkey
                               -- 										and currencytypecode=6
                               -- 										and pricetypecode=9 and pricekey <> cursor_row3.pricekey;
                               -- 									commit;
                               -- 									feed_pricefound :=1;
                               -- 								end if;
                               -- 							end if;
                               -- 						end loop;
                               -- 						--if feed_pricefound = 0 then
                               -- 							--UTL_FILE.PUT_LINE(lv_file_id_num,('Multple
                               -- --Net Price on TMM and none match in coming price and more than 1 rows has activeind=1 or no rows
                               -- --have an activeind for isbn ' || feed_isbn));
                               -- 						--end if;
                               -- 
                               -- 					end if;
                               -- 				  else
                               -- 					titlehistory_insert(9,feedin_bookkey,0,'9',feedin_net);
                               -- 					update qsidba.bookprice
                               -- 					  set finalprice = feedin_net,
                               -- 					    activeind = 1,
                               -- 					    lastuserid='VISTAFEED',
                               -- 					    lastmaintdate = feed_system_date
                               -- 						where bookkey=feedin_bookkey
                               -- 						  and currencytypecode=6
                               -- 						  and pricetypecode=9;
                               -- 				  end if;
                               -- 				else
                               -- 					titlehistory_insert(9,feedin_bookkey,0,'9',feedin_net);
                               -- 					insert into qsidba.bookprice (pricekey,bookkey,pricetypecode,
                               -- 						currencytypecode,activeind,finalprice,
                               -- 						effectivedate,lastuserid,lastmaintdate)
                               -- 					values (QSIDBA.qsikeys_seq.nextval,feedin_bookkey,9,6,1,
                               -- 						feedin_net,feed_system_date,'VISTAFEED',feed_system_date);
                               -- 				end if;
                               -- 			end if;
                               -- 	commit;
                               -- 
                               -- end if;
                               --*/

                              /* pub date */
										 SELECT @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bookdates
                               WHERE bookkey = @feedin_bookkey AND printingkey = 1 AND datetypecode = 8
  
                              IF len(@feedin_pubdate) > 0
                                IF (@feedin_count > 0)
                                BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '8', @feedin_pubdate 

                                    UPDATE bookdates
                                       SET activedate = @feedin_pubdate, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                     WHERE bookkey = @feedin_bookkey AND 
                                           printingkey = 1 AND 
                                           datetypecode = 8
                                END
                                ELSE 
                                BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '8', @feedin_pubdate 

                                    INSERT INTO bookdates(bookkey,printingkey, datetypecode,activedate, 
                                        actualind, sortorder,lastuserid, lastmaintdate )
                                      VALUES (@feedin_bookkey, 1, 8, @feedin_pubdate, 
                                          0, 1, 'VISTAFEED2', @feed_system_date )
                                 END

                             

                              /* rel date */

                               SET @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bookdates
                               WHERE bookkey = @feedin_bookkey AND printingkey = 1 AND datetypecode = 32

                              IF len(@feedin_reldate) > 0
                              BEGIN
                                IF (@feedin_count > 0)
                                  BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '32', @feedin_reldate 

                                    UPDATE bookdates
                                       SET activedate = @feedin_reldate, lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                     WHERE bookkey = @feedin_bookkey AND printingkey = 1 AND datetypecode = 32
                                  END
                                ELSE 
                                BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '32', @feedin_reldate 

                                    INSERT INTO bookdates(bookkey,printingkey, datetypecode,activedate, 
                                        actualind, sortorder,lastuserid, lastmaintdate )
                                      VALUES (@feedin_bookkey, 1, 32, @feedin_reldate, 
                                          0, 2, 'VISTAFEED2', @feed_system_date )
                                 END
                               END

                              /*
                               -- projectisbn does it need validation of isbn prefix:1 nope per john s. bookdetail
                               -- 	vista_productnumber
                               --*/
										SET @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bookdetail
                                WHERE (bookkey = @feedin_bookkey)

                              IF LTRIM(RTRIM(@cursor_row_projectisbn)) > 0
                              BEGIN
										  IF (@feedin_count > 0)
                                BEGIN
                                  UPDATE bookdetail
                                     SET vistaprojectnumber = SUBSTRING(RTRIM(@cursor_row_projectisbn), 1, 13), 
                                         lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                   WHERE (bookkey = @feedin_bookkey)
                                END
                                ELSE 
                                BEGIN
                                  INSERT INTO bookdetail(bookkey, vistaprojectnumber,lastmaintdate,lastuserid)
                                    VALUES (@feedin_bookkey, 
                                        SUBSTRING(RTRIM(@cursor_row_projectisbn), 1, 13), 
                                        @feed_system_date,'VISTAFEED2')
                                END
                              END

                              

                              /* categorycode -- per john s./doug does not need to be a gentables book detail */

                               SET @feedin_count = 0

                              SELECT @feedin_count = count(*)
                                FROM bookdetail
                               WHERE bookkey = @feedin_bookkey
                             
                              IF LTRIM(RTRIM(@cursor_row_categorycode)) > 0
                              BEGIN
                                IF (@feedin_count > 0)
                                BEGIN
                                  UPDATE bookdetail
                                     SET vistacategorycode = SUBSTRING(RTRIM(@cursor_row_categorycode), 1, 6), lastuserid = 'VISTAFEED2', lastmaintdate = @feed_system_date
                                   WHERE bookkey = @feedin_bookkey
                                END
                                ELSE 
                                BEGIN
                                  INSERT INTO bookdetail
                                    (bookkey,vistacategorycode,lastmaintdate,lastuserid )
                                    VALUES 
                                      (@feedin_bookkey,SUBSTRING(RTRIM(@cursor_row_categorycode), 1, 6),
                                        @feed_system_date,'VISTAFEED2')
    						   		 END
                      END   /*  bookkey > 0  */

                      /*  new title -------------------------------------------------------- */

                      IF (@feedin_bookkey = 0)
                        BEGIN
                          IF @feedin_bookkey = 0
									 BEGIN
										  UPDATE feederror
											  SET detailtype = (detailtype + 1)
											WHERE batchnumber = '3' AND 
													processdate >=  @feed_system_date AND 
													errordesc LIKE 'Feed Summary: Rejected%'
									 END -- bookkey = 0 new title
                        END

                    END

                  FETCH NEXT FROM feed_titles
						 INTO @cursor_row_isbn, @cursor_row_bisacstatuscode, @cursor_row_retailprice, @cursor_row_canadianprice, 
							@cursor_row_categorycode,@cursor_row_pubdate, @cursor_row_reldate, @cursor_row_cartonqty, 
							@cursor_row_projectisbn, @cursor_row_canadianrestriction,@cursor_row_discountcode,@cursor_row_nextisbn

                END

              CLOSE feed_titles

              DEALLOCATE feed_titles

            END

            /*   delete when complete since looping through cursor no need delete since truncate before insert */

            /* DELETE FROM qsidba.feedin_titles2; */

            /* commit; */

            INSERT INTO feederror(batchnumber, processdate,errordesc)
					         VALUES ('3', @feed_system_date,'Titles Completed')

            IF (@@TRANCOUNT > 0)
                COMMIT WORK

            IF (cursor_status(N'local', N'feed_titles') = 1)
              BEGIN
                CLOSE feed_titles
                DEALLOCATE feed_titles
              END

          END
      END

GO




