if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[ALLAUTHLAST_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[ALLAUTHLAST_VIEW]
GO

create view dbo.ALLAUTHLAST_VIEW(BOOKKEY, ALLAUTHLAST)  AS 

  SELECT dbo.BOOK.BOOKKEY, CASE dbo.AUTHALL1_VIEW.LASTNAME WHEN  NULL THEN  NULL ELSE CASE dbo.AUTHALL2_VIEW.LASTNAME WHEN  NULL THEN dbo.AUTHALL1_VIEW.LASTNAME ELSE CASE dbo.AUTHALL3_VIEW.LASTNAME WHEN  NULL THEN (isnull(dbo.AUTHALL1_VIEW.LASTNAME, '') + ', ' + isnull(dbo.AUTHALL2_VIEW.LASTNAME, '')) ELSE CASE dbo.AUTHALL4_VIEW.LASTNAME WHEN  NULL THEN (isnull(dbo.AUTHALL1_VIEW.LASTNAME, '') + ', ' + isnull(dbo.AUTHALL2_VIEW.LASTNAME, '') + ', ' + isnull(dbo.AUTHALL3_VIEW.LASTNAME, '')) ELSE (isnull(dbo.AUTHALL1_VIEW.LASTNAME, '') + ', ' + isnull(dbo.AUTHALL2_VIEW.LASTNAME, '') + ', ' + isnull(dbo.AUTHALL3_VIEW.LASTNAME, '') + ', ' + isnull(dbo.AUTHALL4_VIEW.LASTNAME, '')) END END END END AS ALLAUTHLAST
    FROM dbo.BOOK
       LEFT JOIN dbo.AUTHALL1_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTHALL1_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTHALL2_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTHALL2_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTHALL3_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTHALL3_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTHALL4_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTHALL4_VIEW.BOOKKEY)
go
GRANT SELECT ON ALLAUTHLAST_VIEW TO public
go