if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BESTTRIM_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BESTTRIM_VIEW]
GO
create view dbo.BESTTRIM_VIEW(BOOKKEY, PRINTINGKEY, BESTTRIM)  AS 
  SELECT dbo.PRINTING.BOOKKEY, dbo.PRINTING.PRINTINGKEY, CASE dbo.PRINTING.TRIMSIZEWIDTH WHEN  NULL THEN CASE dbo.PRINTING.ESTTRIMSIZEWIDTH WHEN  NULL THEN  NULL ELSE (isnull(dbo.PRINTING.ESTTRIMSIZEWIDTH, '') + ' x ' + isnull(dbo.PRINTING.ESTTRIMSIZELENGTH, '')) END ELSE (isnull(dbo.PRINTING.TRIMSIZEWIDTH, '') + ' x ' + isnull(dbo.PRINTING.TRIMSIZELENGTH, '')) END AS BESTTRIM
    FROM dbo.PRINTING
    WHERE (dbo.PRINTING.PRINTINGKEY = 1)



go
GRANT SELECT ON BESTTRIM_VIEW TO public
go