if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CATALOGHEADING_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[CATALOGHEADING_VIEW]
GO
create view dbo.CATALOGHEADING_VIEW(TABLEID, DATACODE, DATADESC, DELETESTATUS, APPLID, SORTORDER, TABLEMNEMONIC, EXTERNALCODE, DATADESCSHORT, LASTUSERID, LASTMAINTDATE, NUMERICDESC1, NUMERICDESC2, BISACDATACODE, GEN1IND, GEN2IND, ACCEPTEDBYELOQUENCEIND, EXPORTELOQUENCEIND, LOCKBYQSIIND, LOCKBYELOQUENCEIND, ELOQUENCEFIELDTAG, ALTERNATEDESC1, ALTERNATEDESC2)  AS 
  SELECT 
      dbo.GENTABLES.TABLEID, 
      dbo.GENTABLES.DATACODE, 
      dbo.GENTABLES.DATADESC, 
      dbo.GENTABLES.DELETESTATUS, 
      dbo.GENTABLES.APPLID, 
      dbo.GENTABLES.SORTORDER, 
      dbo.GENTABLES.TABLEMNEMONIC, 
      dbo.GENTABLES.EXTERNALCODE, 
      dbo.GENTABLES.DATADESCSHORT, 
      dbo.GENTABLES.LASTUSERID, 
      dbo.GENTABLES.LASTMAINTDATE, 
      dbo.GENTABLES.NUMERICDESC1, 
      dbo.GENTABLES.NUMERICDESC2, 
      dbo.GENTABLES.BISACDATACODE, 
      dbo.GENTABLES.GEN1IND, 
      dbo.GENTABLES.GEN2IND, 
      dbo.GENTABLES.ACCEPTEDBYELOQUENCEIND, 
      dbo.GENTABLES.EXPORTELOQUENCEIND, 
      dbo.GENTABLES.LOCKBYQSIIND, 
      dbo.GENTABLES.LOCKBYELOQUENCEIND, 
      dbo.GENTABLES.ELOQUENCEFIELDTAG, 
      dbo.GENTABLES.ALTERNATEDESC1, 
      dbo.GENTABLES.ALTERNATEDESC2
    FROM dbo.GENTABLES
    WHERE (dbo.GENTABLES.TABLEID = 427)


go
GRANT SELECT ON CATALOGHEADING_VIEW TO public
go