if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CONSULTINGEDITOR_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[CONSULTINGEDITOR_VIEW]
GO
create view dbo.CONSULTINGEDITOR_VIEW(BOOKKEY, PRINTINGKEY, CONTRIBUTORKEY, ROLETYPECODE, DEPTTYPECODE, RESOURCEDESC, LASTUSERID, LASTMAINTDATE, DISPLAYNAME, SHORTNAME)  AS 
  SELECT 
      dbo.BOOKCONTRIBUTOR.BOOKKEY, 
      dbo.BOOKCONTRIBUTOR.PRINTINGKEY, 
      dbo.BOOKCONTRIBUTOR.CONTRIBUTORKEY, 
      dbo.BOOKCONTRIBUTOR.ROLETYPECODE, 
      dbo.BOOKCONTRIBUTOR.DEPTTYPECODE, 
      dbo.BOOKCONTRIBUTOR.RESOURCEDESC, 
      dbo.BOOKCONTRIBUTOR.LASTUSERID, 
      dbo.BOOKCONTRIBUTOR.LASTMAINTDATE, 
      dbo.PERSON.DISPLAYNAME, 
      dbo.PERSON.SHORTNAME
    FROM dbo.BOOKCONTRIBUTOR, dbo.PERSON
    WHERE ((dbo.BOOKCONTRIBUTOR.ROLETYPECODE = 26) AND 
            (dbo.PERSON.CONTRIBUTORKEY = dbo.BOOKCONTRIBUTOR.CONTRIBUTORKEY))


go
GRANT SELECT ON CONSULTINGEDITOR_VIEW TO public
go