/******************************************************************************************
**  Journal, volume, issue, content unit detail config
**  Executes the qutl_insert_gentable_value  procedure
*******************************************************************************************/

BEGIN

  DECLARE
  @v_itemtype     INT,
  @v_usageclass   INT,
  @v_datacode INT,
  @v_datasubcode INT,
  @v_classcode INT,
  @v_error_code   INT ,
  @v_error_desc   VARCHAR(2000) 

SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  1, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 1 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  2, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 2 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  3, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=3 where datacode= 13 AND datasubcode= 3 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  4, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 4 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  5, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 5 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  6, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 6 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  7, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 7 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  8, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=3 where datacode= 13 AND datasubcode= 8 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  9, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 9 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  10, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 10 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  11, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 11 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  12, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 12 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  13, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 13 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  14, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 14 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  15, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 15 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  16, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=4 where datacode= 13 AND datasubcode= 16 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  17, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 17 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  18, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 18 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  19, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 19 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 4	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  20, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 20 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc

SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  1, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 1 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  2, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 2 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  3, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=3 where datacode= 13 AND datasubcode= 3 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  4, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 4 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  5, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 5 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  6, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=4 where datacode= 13 AND datasubcode= 6 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  7, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 7 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  8, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=3 where datacode= 13 AND datasubcode= 8 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  9, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 9 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  10, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 10 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  11, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  6, text1 = '', numericdesc1=4 where datacode= 13 AND datasubcode= 11 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  12, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 12 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  13, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 13 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  14, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 14 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  15, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 15 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  16, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=4 where datacode= 13 AND datasubcode= 16 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  17, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 17 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  18, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 18 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  19, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 19 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 8	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  20, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 20 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc

SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  1, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 1 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  2, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 2 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  3, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=3 where datacode= 13 AND datasubcode= 3 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  4, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 4 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  5, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 5 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  6, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=4 where datacode= 13 AND datasubcode= 6 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  7, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 7 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  8, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=3 where datacode= 13 AND datasubcode= 8 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  9, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 9 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  10, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 10 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  11, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 11 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  12, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 12 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  13, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 13 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  14, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 14 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  15, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 15 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  16, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=4 where datacode= 13 AND datasubcode= 16 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  17, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 17 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  18, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 18 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  19, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 19 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 5	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  20, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 20 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc

SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  1, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 1 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  2, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 2 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  3, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=3 where datacode= 13 AND datasubcode= 3 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  4, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 4 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  5, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  5, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 5 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  6, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 6 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  7, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 7 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  8, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=3 where datacode= 13 AND datasubcode= 8 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  9, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 9 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  10, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 10 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  11, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 11 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  12, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 12 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  13, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  1, text1 = '', numericdesc1=2 where datacode= 13 AND datasubcode= 13 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  14, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 14 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  15, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  2, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 15 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  16, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  3, text1 = '', numericdesc1=4 where datacode= 13 AND datasubcode= 16 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  17, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  4, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 17 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  18, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 18 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  19, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 19 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
SELECT @v_classcode = datasubcode , @v_itemtype = datacode from subgentables where tableid = 550 and qsicode = 6	IF @v_classcode<> 0  BEGIN exec qutl_insert_gentablesitemtype 636, 13,  20, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	update gentablesitemtype set sortorder =  0, text1 = '', numericdesc1=NULL where datacode= 13 AND datasubcode= 20 AND itemtypecode =@v_itemtype AND itemtypesubcode = @v_classcode	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc

END
GO