SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FULFILLMENT_MM_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[FULFILLMENT_MM_VIEW]
GO

create view dbo.FULFILLMENT_MM_VIEW(BOOKKEY, FULFILLMENT)  AS 
  SELECT wb.BOOKKEY, (((wb.BOOKMISCLONG2 + wb.BOOKMISCLONG3) / 4 * CAST( .045 AS float)) + ((wb.BOOKMISCLONG2 + wb.BOOKMISCLONG3) * CAST( .03 AS float)) + ((wb.BOOKMISCLONG2 + wb.BOOKMISCLONG3) * CAST( .025 AS float) * (isnull(wt.PAGECOUNTBEST, 274) / 340))) AS FULFILLMENT
    FROM dbo.WHBOOKMISC wb, dbo.WHTITLEINFO wt
    WHERE (wb.BOOKKEY = wt.BOOKKEY)
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT  SELECT  ON [dbo].[FULFILLMENT_MM_VIEW]  TO [public]
GO
