IF EXISTS (
    SELECT *
    FROM dbo.sysobjects
    WHERE id = object_id(N'dbo.qproject_get_filtered_tabconfig_table')
      AND xtype IN (N'FN', N'IF', N'TF')
    )
  DROP FUNCTION dbo.qproject_get_filtered_tabconfig_table
GO

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS OFF
GO

CREATE FUNCTION qproject_get_filtered_tabconfig_table (
  @i_relationshiptabcode INT,
  @i_itemtype INT,
  @i_usageclass INT,
  @i_formtab_itemtype INT,
  @i_formtab_usageclass INT
  )
RETURNS @ConfigTable TABLE (
  taqrelationshiptabconfigkey INT,
  relationshiptabcode INT,
  itemtypecode INT,
  usageclass INT,
  quantity1label VARCHAR(100),
  quantity2label VARCHAR(100),
  quantity3label VARCHAR(100),
  quantity4label VARCHAR(100),
  indicator1label VARCHAR(100),
  indicator2label VARCHAR(100),
  miscitemkey1 INT,
  miscitem1label VARCHAR(100),
  miscitemkey2 INT,
  miscitem2label VARCHAR(100),
  datetypecode1 INT,
  date1label VARCHAR(100),
  datetypecode2 INT,
  date2label VARCHAR(100),
  formTabUsageClass INT,
  miscitemkey3 INT,
  miscitem3label VARCHAR(100),
  miscitemkey4 INT,
  miscitem4label VARCHAR(100),
  miscitemkey5 INT,
  miscitem5label VARCHAR(100),
  miscitemkey6 INT,
  miscitem6label VARCHAR(100),
  Datetypecode3 INT,
  Date3label VARCHAR(100),
  Datetypecode4 INT,
  Date4label VARCHAR(100),
  Datetypecode5 INT,
  Date5label VARCHAR(100),
  Datetypecode6 INT,
  Date6label VARCHAR(100),
  Productidcode1 INT,
  Productid1label VARCHAR(100),
  Productidcode2 INT,
  Productid2label VARCHAR(100),
  Roletypecode1 INT,
  Roletype1label VARCHAR(100),
  Roletypecode2 INT,
  Roletype2label VARCHAR(100),
  Pricetypecode1 INT,
  Price1label VARCHAR(100),
  Pricetypecode2 INT,
  Price2label VARCHAR(100),
  Pricetypecode3 INT,
  Price3label VARCHAR(100),
  Pricetypecode4 INT,
  Price4label VARCHAR(100),
  formTabItemType INT,
  tableid1 INT,
  tableidlabel1 VARCHAR(100),
  tableid2 INT,
  tableidlabel2 VARCHAR(100),
  tableid3 INT,
  tableidlabel3 VARCHAR(100),
  tableid4 INT,
  tableidlabel4 VARCHAR(100),
  createitemtypecode INT,
  createclasscode INT,
  createnewrelatecode INT,
  createexistrelatecode INT,
  createprojrolecode INT,
  createtitlerolecode INT,
  create2itemtypecode INT,
  create2classcode INT,
  create2newrelatecode INT,
  create2existrelatecode INT,
  create2projrolecode INT,
  create2titlerolecode INT,
  create3itemtypecode INT,
  create3classcode INT,
  create3newrelatecode INT,
  create3existrelatecode INT,
  create3projrolecode INT,
  create3titlerolecode INT,
  relateitemtypecode INT,
  relateclasscode INT,
  relate2itemtypecode INT,
  relate2classcode INT,
  relate3itemtypecode INT,
  relate3classcode INT,
  hidefiltersind TINYINT,
  hideclassind TINYINT,
  hidetypeind TINYINT,
  hidethisrelind TINYINT,
  hideotherrelind TINYINT,
  hidenotesind TINYINT,
  hideownerind TINYINT,
  addrelateditemind TINYINT,
  contactrelationship1label VARCHAR(100),
  contactrelationship1 INT,
  contactrelationship2label VARCHAR(100),
  contactrelationship2 INT,
  hideparticipantsind TINYINT,
  hidedeletebuttonind TINYINT,
  decimal1label VARCHAR(100),
  decimal1format VARCHAR(40),
  decimal2label VARCHAR(100),
  decimal2format VARCHAR(40),
  relatecurrentprojrelcode INT,
  relaterelatedprojrelcode INT,
  relateprojrolecode INT,
  relatetitlerolecode INT,
  relate2currentprojrelcode INT,
  relate2relatedprojrelcode INT,
  relate2projrolecode INT,
  relate2titlerolecode INT,
  relate3currentprojrelcode INT,
  relate3relatedprojrelcode INT,
  relate3projrolecode INT,
  relate3titlerolecode INT,
  sortdescendingind INT,
  hidestatusind TINYINT,
  hidekeyind TINYINT,
  defaultfilteritemtype INT,
  defaultfilterusageclass INT,
  defaultsortorder VARCHAR(2000),
  createastemplateind TINYINT,
  create2astemplateind TINYINT,
  create3astemplateind TINYINT,
  scrollbarheight INT,
  displaytemplatesonlyind TINYINT,
  alloweditablefieldsind TINYINT,
  lastmaintdate DATETIME,
  lastuserid VARCHAR(30)
  )
AS
/******************************************************************************
**  Name: qproject_get_filtered_tabconfig_table
**  Desc: 
**
**    Auth: Colman
**    Date: 06/25/2018
*******************************************************************************
**    Change History
*******************************************************************************
**    Date:        Author:    Case #:   Description:
**    ----------   --------   -------   ---------------------------------------
**
*******************************************************************************/

BEGIN
  -- Run three counts against tabrelationshiptabconfig, 
  -- 1. Matching relationshiptabcode, itemtypecode and usageclass
  -- 2. Matching relationshiptabcode and itemtype with NULL usageclass
  -- 3. Matching relationshiptabcode and NULL itemtype and usageclass
  -- This will satisfy the spec requirements as written: 
  /** "It will first check for the tab name using the item type/usage class of the current item 
		(for example. the Project Key of the Project you are on in Project Summary) on taqrelationshiptabconfig.  
		If nothing is found for the item type/usage class, check again using the item type with a null usage class; 
		this will find a default for the item type if there is any.  If nothing is selected still, check again with 
		both the item type and usage class set to null; this will find a default for the tab if there is any.
		If nothing is found at all, set all of the configurable columns to invisible. " **/
  IF EXISTS (
      SELECT 1
      FROM taqrelationshiptabconfig
      WHERE relationshiptabcode = @i_relationshiptabcode
        AND itemtypecode = @i_itemtype
        AND usageclass = @i_usageclass
        AND (
          @i_formtab_itemtype IS NULL
          OR formtabitemtype = @i_formtab_itemtype
          )
        AND (
          @i_formtab_usageclass IS NULL
          OR formtabusageclass = @i_formtab_usageclass
          )
      )
  BEGIN
    INSERT INTO @ConfigTable (
      taqrelationshiptabconfigkey,
      relationshiptabcode,
      itemtypecode,
      usageclass,
      quantity1label,
      quantity2label,
      quantity3label,
      quantity4label,
      indicator1label,
      indicator2label,
      miscitemkey1,
      miscitem1label,
      miscitemkey2,
      miscitem2label,
      datetypecode1,
      date1label,
      datetypecode2,
      date2label,
      formTabUsageClass,
      miscitemkey3,
      miscitem3label,
      miscitemkey4,
      miscitem4label,
      miscitemkey5,
      miscitem5label,
      miscitemkey6,
      miscitem6label,
      Datetypecode3,
      Date3label,
      Datetypecode4,
      Date4label,
      Datetypecode5,
      Date5label,
      Datetypecode6,
      Date6label,
      Productidcode1,
      Productid1label,
      Productidcode2,
      Productid2label,
      Roletypecode1,
      Roletype1label,
      Roletypecode2,
      Roletype2label,
      Pricetypecode1,
      Price1label,
      Pricetypecode2,
      Price2label,
      Pricetypecode3,
      Price3label,
      Pricetypecode4,
      Price4label,
      formTabItemType,
      tableid1,
      tableidlabel1,
      tableid2,
      tableidlabel2,
      tableid3,
      tableidlabel3,
      tableid4,
      tableidlabel4,
      createitemtypecode,
      createclasscode,
      createnewrelatecode,
      createexistrelatecode,
      createprojrolecode,
      createtitlerolecode,
      create2itemtypecode,
      create2classcode,
      create2newrelatecode,
      create2existrelatecode,
      create2projrolecode,
      create2titlerolecode,
      create3itemtypecode,
      create3classcode,
      create3newrelatecode,
      create3existrelatecode,
      create3projrolecode,
      create3titlerolecode,
      relateitemtypecode,
      relateclasscode,
      relate2itemtypecode,
      relate2classcode,
      relate3itemtypecode,
      relate3classcode,
      hidefiltersind,
      hideclassind,
      hidetypeind,
      hidethisrelind,
      hideotherrelind,
      hidenotesind,
      hideownerind,
      addrelateditemind,
      contactrelationship1label,
      contactrelationship1,
      contactrelationship2label,
      contactrelationship2,
      hideparticipantsind,
      hidedeletebuttonind,
      decimal1label,
      decimal1format,
      decimal2label,
      decimal2format,
      relatecurrentprojrelcode,
      relaterelatedprojrelcode,
      relateprojrolecode,
      relatetitlerolecode,
      relate2currentprojrelcode,
      relate2relatedprojrelcode,
      relate2projrolecode,
      relate2titlerolecode,
      relate3currentprojrelcode,
      relate3relatedprojrelcode,
      relate3projrolecode,
      relate3titlerolecode,
      sortdescendingind,
      hidestatusind,
      hidekeyind,
      defaultfilteritemtype,
      defaultfilterusageclass,
      defaultsortorder,
      createastemplateind,
      create2astemplateind,
      create3astemplateind,
      scrollbarheight,
      displaytemplatesonlyind,
      alloweditablefieldsind,
      lastmaintdate,
      lastuserid
      )
    SELECT
      taqrelationshiptabconfigkey,
      relationshiptabcode,
      itemtypecode,
      usageclass,
      quantity1label,
      quantity2label,
      quantity3label,
      quantity4label,
      indicator1label,
      indicator2label,
      miscitemkey1,
      miscitem1label,
      miscitemkey2,
      miscitem2label,
      datetypecode1,
      date1label,
      datetypecode2,
      date2label,
      formTabUsageClass,
      miscitemkey3,
      miscitem3label,
      miscitemkey4,
      miscitem4label,
      miscitemkey5,
      miscitem5label,
      miscitemkey6,
      miscitem6label,
      Datetypecode3,
      Date3label,
      Datetypecode4,
      Date4label,
      Datetypecode5,
      Date5label,
      Datetypecode6,
      Date6label,
      Productidcode1,
      Productid1label,
      Productidcode2,
      Productid2label,
      Roletypecode1,
      Roletype1label,
      Roletypecode2,
      Roletype2label,
      Pricetypecode1,
      Price1label,
      Pricetypecode2,
      Price2label,
      Pricetypecode3,
      Price3label,
      Pricetypecode4,
      Price4label,
      formTabItemType,
      tableid1,
      tableidlabel1,
      tableid2,
      tableidlabel2,
      tableid3,
      tableidlabel3,
      tableid4,
      tableidlabel4,
      createitemtypecode,
      createclasscode,
      createnewrelatecode,
      createexistrelatecode,
      createprojrolecode,
      createtitlerolecode,
      create2itemtypecode,
      create2classcode,
      create2newrelatecode,
      create2existrelatecode,
      create2projrolecode,
      create2titlerolecode,
      create3itemtypecode,
      create3classcode,
      create3newrelatecode,
      create3existrelatecode,
      create3projrolecode,
      create3titlerolecode,
      relateitemtypecode,
      relateclasscode,
      relate2itemtypecode,
      relate2classcode,
      relate3itemtypecode,
      relate3classcode,
      hidefiltersind,
      hideclassind,
      hidetypeind,
      hidethisrelind,
      hideotherrelind,
      hidenotesind,
      hideownerind,
      addrelateditemind,
      contactrelationship1label,
      contactrelationship1,
      contactrelationship2label,
      contactrelationship2,
      hideparticipantsind,
      hidedeletebuttonind,
      decimal1label,
      decimal1format,
      decimal2label,
      decimal2format,
      relatecurrentprojrelcode,
      relaterelatedprojrelcode,
      relateprojrolecode,
      relatetitlerolecode,
      relate2currentprojrelcode,
      relate2relatedprojrelcode,
      relate2projrolecode,
      relate2titlerolecode,
      relate3currentprojrelcode,
      relate3relatedprojrelcode,
      relate3projrolecode,
      relate3titlerolecode,
      sortdescendingind,
      hidestatusind,
      hidekeyind,
      defaultfilteritemtype,
      defaultfilterusageclass,
      defaultsortorder,
      createastemplateind,
      create2astemplateind,
      create3astemplateind,
      scrollbarheight,
      displaytemplatesonlyind,
      alloweditablefieldsind,
      lastmaintdate,
      lastuserid
    FROM taqrelationshiptabconfig
    WHERE relationshiptabcode = @i_relationshiptabcode
      AND itemtypecode = @i_itemtype
      AND usageclass = @i_usageclass
      AND (
        @i_formtab_itemtype IS NULL
        OR formtabitemtype = @i_formtab_itemtype
        )
      AND (
        @i_formtab_usageclass IS NULL
        OR formtabusageclass = @i_formtab_usageclass
        )
  END
  ELSE IF EXISTS (
      SELECT 1
      FROM taqrelationshiptabconfig
      WHERE relationshiptabcode = @i_relationshiptabcode
        AND itemtypecode = @i_itemtype
        AND usageclass IS NULL
        AND (
          @i_formtab_itemtype IS NULL
          OR formtabitemtype = @i_formtab_itemtype
          )
        AND (
          @i_formtab_usageclass IS NULL
          OR formtabusageclass = @i_formtab_usageclass
          )
      )
  BEGIN
    INSERT INTO @ConfigTable (
      taqrelationshiptabconfigkey,
      relationshiptabcode,
      itemtypecode,
      usageclass,
      quantity1label,
      quantity2label,
      quantity3label,
      quantity4label,
      indicator1label,
      indicator2label,
      miscitemkey1,
      miscitem1label,
      miscitemkey2,
      miscitem2label,
      datetypecode1,
      date1label,
      datetypecode2,
      date2label,
      formTabUsageClass,
      miscitemkey3,
      miscitem3label,
      miscitemkey4,
      miscitem4label,
      miscitemkey5,
      miscitem5label,
      miscitemkey6,
      miscitem6label,
      Datetypecode3,
      Date3label,
      Datetypecode4,
      Date4label,
      Datetypecode5,
      Date5label,
      Datetypecode6,
      Date6label,
      Productidcode1,
      Productid1label,
      Productidcode2,
      Productid2label,
      Roletypecode1,
      Roletype1label,
      Roletypecode2,
      Roletype2label,
      Pricetypecode1,
      Price1label,
      Pricetypecode2,
      Price2label,
      Pricetypecode3,
      Price3label,
      Pricetypecode4,
      Price4label,
      formTabItemType,
      tableid1,
      tableidlabel1,
      tableid2,
      tableidlabel2,
      tableid3,
      tableidlabel3,
      tableid4,
      tableidlabel4,
      createitemtypecode,
      createclasscode,
      createnewrelatecode,
      createexistrelatecode,
      createprojrolecode,
      createtitlerolecode,
      create2itemtypecode,
      create2classcode,
      create2newrelatecode,
      create2existrelatecode,
      create2projrolecode,
      create2titlerolecode,
      create3itemtypecode,
      create3classcode,
      create3newrelatecode,
      create3existrelatecode,
      create3projrolecode,
      create3titlerolecode,
      relateitemtypecode,
      relateclasscode,
      relate2itemtypecode,
      relate2classcode,
      relate3itemtypecode,
      relate3classcode,
      hidefiltersind,
      hideclassind,
      hidetypeind,
      hidethisrelind,
      hideotherrelind,
      hidenotesind,
      hideownerind,
      addrelateditemind,
      contactrelationship1label,
      contactrelationship1,
      contactrelationship2label,
      contactrelationship2,
      hideparticipantsind,
      hidedeletebuttonind,
      decimal1label,
      decimal1format,
      decimal2label,
      decimal2format,
      relatecurrentprojrelcode,
      relaterelatedprojrelcode,
      relateprojrolecode,
      relatetitlerolecode,
      relate2currentprojrelcode,
      relate2relatedprojrelcode,
      relate2projrolecode,
      relate2titlerolecode,
      relate3currentprojrelcode,
      relate3relatedprojrelcode,
      relate3projrolecode,
      relate3titlerolecode,
      sortdescendingind,
      hidestatusind,
      hidekeyind,
      defaultfilteritemtype,
      defaultfilterusageclass,
      defaultsortorder,
      createastemplateind,
      create2astemplateind,
      create3astemplateind,
      scrollbarheight,
      displaytemplatesonlyind,
      alloweditablefieldsind,
      lastmaintdate,
      lastuserid
      )
    SELECT 
      taqrelationshiptabconfigkey,
      relationshiptabcode,
      itemtypecode,
      usageclass,
      quantity1label,
      quantity2label,
      quantity3label,
      quantity4label,
      indicator1label,
      indicator2label,
      miscitemkey1,
      miscitem1label,
      miscitemkey2,
      miscitem2label,
      datetypecode1,
      date1label,
      datetypecode2,
      date2label,
      formTabUsageClass,
      miscitemkey3,
      miscitem3label,
      miscitemkey4,
      miscitem4label,
      miscitemkey5,
      miscitem5label,
      miscitemkey6,
      miscitem6label,
      Datetypecode3,
      Date3label,
      Datetypecode4,
      Date4label,
      Datetypecode5,
      Date5label,
      Datetypecode6,
      Date6label,
      Productidcode1,
      Productid1label,
      Productidcode2,
      Productid2label,
      Roletypecode1,
      Roletype1label,
      Roletypecode2,
      Roletype2label,
      Pricetypecode1,
      Price1label,
      Pricetypecode2,
      Price2label,
      Pricetypecode3,
      Price3label,
      Pricetypecode4,
      Price4label,
      formTabItemType,
      tableid1,
      tableidlabel1,
      tableid2,
      tableidlabel2,
      tableid3,
      tableidlabel3,
      tableid4,
      tableidlabel4,
      createitemtypecode,
      createclasscode,
      createnewrelatecode,
      createexistrelatecode,
      createprojrolecode,
      createtitlerolecode,
      create2itemtypecode,
      create2classcode,
      create2newrelatecode,
      create2existrelatecode,
      create2projrolecode,
      create2titlerolecode,
      create3itemtypecode,
      create3classcode,
      create3newrelatecode,
      create3existrelatecode,
      create3projrolecode,
      create3titlerolecode,
      relateitemtypecode,
      relateclasscode,
      relate2itemtypecode,
      relate2classcode,
      relate3itemtypecode,
      relate3classcode,
      hidefiltersind,
      hideclassind,
      hidetypeind,
      hidethisrelind,
      hideotherrelind,
      hidenotesind,
      hideownerind,
      addrelateditemind,
      contactrelationship1label,
      contactrelationship1,
      contactrelationship2label,
      contactrelationship2,
      hideparticipantsind,
      hidedeletebuttonind,
      decimal1label,
      decimal1format,
      decimal2label,
      decimal2format,
      relatecurrentprojrelcode,
      relaterelatedprojrelcode,
      relateprojrolecode,
      relatetitlerolecode,
      relate2currentprojrelcode,
      relate2relatedprojrelcode,
      relate2projrolecode,
      relate2titlerolecode,
      relate3currentprojrelcode,
      relate3relatedprojrelcode,
      relate3projrolecode,
      relate3titlerolecode,
      sortdescendingind,
      hidestatusind,
      hidekeyind,
      defaultfilteritemtype,
      defaultfilterusageclass,
      defaultsortorder,
      createastemplateind,
      create2astemplateind,
      create3astemplateind,
      scrollbarheight,
      displaytemplatesonlyind,
      alloweditablefieldsind,
      lastmaintdate,
      lastuserid
    FROM taqrelationshiptabconfig
    WHERE relationshiptabcode = @i_relationshiptabcode
      AND itemtypecode = @i_itemtype
      AND usageclass IS NULL
      AND (
        @i_formtab_itemtype IS NULL
        OR formtabitemtype = @i_formtab_itemtype
        )
      AND (
        @i_formtab_usageclass IS NULL
        OR formtabusageclass = @i_formtab_usageclass
        )
  END
  ELSE IF EXISTS (
      SELECT 1
      FROM taqrelationshiptabconfig
      WHERE relationshiptabcode = @i_relationshiptabcode
        AND itemtypecode IS NULL
        AND usageclass IS NULL
        AND (
          @i_formtab_itemtype IS NULL
          OR formtabitemtype = @i_formtab_itemtype
          )
        AND (
          @i_formtab_usageclass IS NULL
          OR formtabusageclass = @i_formtab_usageclass
          )
      )
  BEGIN
    INSERT INTO @ConfigTable (
      taqrelationshiptabconfigkey,
      relationshiptabcode,
      itemtypecode,
      usageclass,
      quantity1label,
      quantity2label,
      quantity3label,
      quantity4label,
      indicator1label,
      indicator2label,
      miscitemkey1,
      miscitem1label,
      miscitemkey2,
      miscitem2label,
      datetypecode1,
      date1label,
      datetypecode2,
      date2label,
      formTabUsageClass,
      miscitemkey3,
      miscitem3label,
      miscitemkey4,
      miscitem4label,
      miscitemkey5,
      miscitem5label,
      miscitemkey6,
      miscitem6label,
      Datetypecode3,
      Date3label,
      Datetypecode4,
      Date4label,
      Datetypecode5,
      Date5label,
      Datetypecode6,
      Date6label,
      Productidcode1,
      Productid1label,
      Productidcode2,
      Productid2label,
      Roletypecode1,
      Roletype1label,
      Roletypecode2,
      Roletype2label,
      Pricetypecode1,
      Price1label,
      Pricetypecode2,
      Price2label,
      Pricetypecode3,
      Price3label,
      Pricetypecode4,
      Price4label,
      formTabItemType,
      tableid1,
      tableidlabel1,
      tableid2,
      tableidlabel2,
      tableid3,
      tableidlabel3,
      tableid4,
      tableidlabel4,
      createitemtypecode,
      createclasscode,
      createnewrelatecode,
      createexistrelatecode,
      createprojrolecode,
      createtitlerolecode,
      create2itemtypecode,
      create2classcode,
      create2newrelatecode,
      create2existrelatecode,
      create2projrolecode,
      create2titlerolecode,
      create3itemtypecode,
      create3classcode,
      create3newrelatecode,
      create3existrelatecode,
      create3projrolecode,
      create3titlerolecode,
      relateitemtypecode,
      relateclasscode,
      relate2itemtypecode,
      relate2classcode,
      relate3itemtypecode,
      relate3classcode,
      hidefiltersind,
      hideclassind,
      hidetypeind,
      hidethisrelind,
      hideotherrelind,
      hidenotesind,
      hideownerind,
      addrelateditemind,
      contactrelationship1label,
      contactrelationship1,
      contactrelationship2label,
      contactrelationship2,
      hideparticipantsind,
      hidedeletebuttonind,
      decimal1label,
      decimal1format,
      decimal2label,
      decimal2format,
      relatecurrentprojrelcode,
      relaterelatedprojrelcode,
      relateprojrolecode,
      relatetitlerolecode,
      relate2currentprojrelcode,
      relate2relatedprojrelcode,
      relate2projrolecode,
      relate2titlerolecode,
      relate3currentprojrelcode,
      relate3relatedprojrelcode,
      relate3projrolecode,
      relate3titlerolecode,
      sortdescendingind,
      hidestatusind,
      hidekeyind,
      defaultfilteritemtype,
      defaultfilterusageclass,
      defaultsortorder,
      createastemplateind,
      create2astemplateind,
      create3astemplateind,
      scrollbarheight,
      displaytemplatesonlyind,
      alloweditablefieldsind,
      lastmaintdate,
      lastuserid
      )
    SELECT 
      taqrelationshiptabconfigkey,
      relationshiptabcode,
      itemtypecode,
      usageclass,
      quantity1label,
      quantity2label,
      quantity3label,
      quantity4label,
      indicator1label,
      indicator2label,
      miscitemkey1,
      miscitem1label,
      miscitemkey2,
      miscitem2label,
      datetypecode1,
      date1label,
      datetypecode2,
      date2label,
      formTabUsageClass,
      miscitemkey3,
      miscitem3label,
      miscitemkey4,
      miscitem4label,
      miscitemkey5,
      miscitem5label,
      miscitemkey6,
      miscitem6label,
      Datetypecode3,
      Date3label,
      Datetypecode4,
      Date4label,
      Datetypecode5,
      Date5label,
      Datetypecode6,
      Date6label,
      Productidcode1,
      Productid1label,
      Productidcode2,
      Productid2label,
      Roletypecode1,
      Roletype1label,
      Roletypecode2,
      Roletype2label,
      Pricetypecode1,
      Price1label,
      Pricetypecode2,
      Price2label,
      Pricetypecode3,
      Price3label,
      Pricetypecode4,
      Price4label,
      formTabItemType,
      tableid1,
      tableidlabel1,
      tableid2,
      tableidlabel2,
      tableid3,
      tableidlabel3,
      tableid4,
      tableidlabel4,
      createitemtypecode,
      createclasscode,
      createnewrelatecode,
      createexistrelatecode,
      createprojrolecode,
      createtitlerolecode,
      create2itemtypecode,
      create2classcode,
      create2newrelatecode,
      create2existrelatecode,
      create2projrolecode,
      create2titlerolecode,
      create3itemtypecode,
      create3classcode,
      create3newrelatecode,
      create3existrelatecode,
      create3projrolecode,
      create3titlerolecode,
      relateitemtypecode,
      relateclasscode,
      relate2itemtypecode,
      relate2classcode,
      relate3itemtypecode,
      relate3classcode,
      hidefiltersind,
      hideclassind,
      hidetypeind,
      hidethisrelind,
      hideotherrelind,
      hidenotesind,
      hideownerind,
      addrelateditemind,
      contactrelationship1label,
      contactrelationship1,
      contactrelationship2label,
      contactrelationship2,
      hideparticipantsind,
      hidedeletebuttonind,
      decimal1label,
      decimal1format,
      decimal2label,
      decimal2format,
      relatecurrentprojrelcode,
      relaterelatedprojrelcode,
      relateprojrolecode,
      relatetitlerolecode,
      relate2currentprojrelcode,
      relate2relatedprojrelcode,
      relate2projrolecode,
      relate2titlerolecode,
      relate3currentprojrelcode,
      relate3relatedprojrelcode,
      relate3projrolecode,
      relate3titlerolecode,
      sortdescendingind,
      hidestatusind,
      hidekeyind,
      defaultfilteritemtype,
      defaultfilterusageclass,
      defaultsortorder,
      createastemplateind,
      create2astemplateind,
      create3astemplateind,
      scrollbarheight,
      displaytemplatesonlyind,
      alloweditablefieldsind,
      lastmaintdate,
      lastuserid
    FROM taqrelationshiptabconfig
    WHERE relationshiptabcode = @i_relationshiptabcode
      AND itemtypecode IS NULL
      AND usageclass IS NULL
      AND (
        @i_formtab_itemtype IS NULL
        OR formtabitemtype = @i_formtab_itemtype
        )
      AND (
        @i_formtab_usageclass IS NULL
        OR formtabusageclass = @i_formtab_usageclass
        )
  END

  RETURN
END
GO

SET QUOTED_IDENTIFIER OFF
GO

SET ANSI_NULLS ON
GO


