IF exists (select * from dbo.sysobjects where id = object_id(N'dbo.FEED_IN_TITLE_INFO') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
  DROP PROCEDURE dbo.FEED_IN_TITLE_INFO

GO


CREATE PROCEDURE feed_in_title_info 
    AS
      /*
       -- Generated by SQL Server Migration Assistant for Oracle
       --  Please, contact SSMAHELP@microsoft.com or visit http://www.microsoft.com/sql/migration for more information.
       --*/
      BEGIN
          DECLARE 
            @err_msg varchar(255),
            @feed_system_date datetime,
            @feedin_bookkey INT,
            @feedin_authorkey INT,
            @feedin_bisactatus varchar(10),
            @feedin_bisacstatus_old INT,
            @feedin_count INT,
            @feedin_retailprice numeric(9, 2),
            @feedin_canadianprice numeric(9, 2),
            @feedin_pubstring varchar(11),
            @feedin_pubdate datetime,
            @feedin_reldate datetime,
            @feedin_delivdate datetime,
            @feedin_categorycode varchar(20),
            @feed_isbn varchar(13),
            @feed_isbn10 varchar(10),
            @feedin_title varchar(80),
            @feedin_shorttitle varchar(24),
            @feedin_subtitle varchar(255),
            @feedin_authorlast varchar(25),
            @feed_prepackind char(1),
            @feedin_temp_isbn varchar(8),
            @feedin_isbn_prefix INT,
            @feedin_pubmonthcode INT,
            @feedin_price_temp numeric(9,2),
            @feedin_canadianrestriction INT,
            @feedin_pubtowebind TINYINT,
            @feedin_year numeric(5, 0),
            @feedin_discount INT,
            @feed_pricekey INT,
            @feed_pricecount TINYINT,
            @feed_pricefound TINYINT,
            @feed_orgentry_college TINYINT,
            @feedin_net  numeric(9,2),
            @cursor_row_isbn varchar(10),
            @cursor_row_bisacstatuscode varchar(10),
            @cursor_row_retailprice varchar(20),
				@cursor_row_retailprice2 numeric(9,2),
            @cursor_row_canadianprice varchar(20),
				@cursor_row_canadianprice2 numeric(9,2),
            @cursor_row_categorycode varchar(12),
            @cursor_row_pubdate varchar(12),
            @cursor_row_reldate varchar(12),
            @cursor_row_cartonqty varchar(10),
            @cursor_row_projectisbn varchar(20),
            @cursor_row_canadianrestriction varchar(10),
            @cursor_row_discountcode varchar(10),
            @cursor_row_netprice varchar(20),
			   @cursor_row_netprice2 numeric(9,2),
            @cursor_row_delivery_date varchar(12),
            @cursor_row_pricekey INT,
            @cursor_row_activeind INT,
            @cursor_row_listprice INT,
            @cursor_row_canadaprice INT,
            @errordesc varchar(100),
				@v_newkey INT,
            @feedin_tableid INT,
            @feedin_cartonqty FLOAT,
            @titlehistory_newvalue varchar(100)
         
          SET @feedin_count = 0
          SET @feed_prepackind = 'N'
          SET @feedin_isbn_prefix = 0
          SET @feedin_pubmonthcode = 0
          SET @feedin_price_temp = 0
          SET @feedin_canadianrestriction = 0
          SET @feedin_pubtowebind = 0
          SET @feedin_year = 0
          SET @feedin_discount = 0
          SET @feed_orgentry_college = 0

          BEGIN TRY

            SELECT @feed_system_date = getdate()
            
            /*  run titles feed from here  */

            INSERT INTO feederror(batchnumber, processdate,errordesc,detailtype)
              VALUES ('3', @feed_system_date,'Feed Summary: Inserts', 0)

            INSERT INTO feederror(batchnumber, processdate,errordesc,detailtype)
				VALUES ('3', @feed_system_date,'Feed Summary: Updates', 0)

				INSERT INTO feederror(batchnumber, processdate,errordesc,detailtype)
					VALUES ('3', @feed_system_date,'Feed Summary: Rejected', 0)

            BEGIN

              DECLARE feed_titles CURSOR LOCAL FOR 
                  SELECT DISTINCT rtrim(ltrim (t.isbn)), 
                     rtrim(ltrim (t.bisacstatuscode)), 
                     rtrim(ltrim (t.retailprice)),
                     rtrim(ltrim (t.canadianprice)) ,
                      rtrim(ltrim (t.categorycode)), 
                      rtrim(ltrim (t.pubdate)), 
                      rtrim(ltrim (t.reldate)), 
                      rtrim(ltrim (t.cartonqty)), 
                      rtrim(ltrim (t.projectisbn)), 
                      rtrim(ltrim (t.canadianrestriction)),
                      rtrim(ltrim (t.discountcode)), 
                      rtrim(ltrim (t.netprice)), 
                      rtrim(ltrim (t.delivery_date)) 

                    FROM feedin_titles t, isbn i
                    WHERE (i.isbn10 = t.isbn)
                   -- ORDER BY t.isbn
                  FOR READ ONLY
              

              OPEN feed_titles

              FETCH NEXT FROM feed_titles INTO @cursor_row_isbn,@cursor_row_bisacstatuscode,@cursor_row_retailprice, 
                  @cursor_row_canadianprice,@cursor_row_categorycode,@cursor_row_pubdate,@cursor_row_reldate,@cursor_row_cartonqty, 
                  @cursor_row_projectisbn,@cursor_row_canadianrestriction,@cursor_row_discountcode,@cursor_row_netprice, 
                  @cursor_row_delivery_date

              IF (@@FETCH_STATUS = -1)
              BEGIN

					 INSERT INTO feederror(batchnumber, processdate,errordesc,detailtype)
					     VALUES ('3', @feed_system_date,'NO ROWS to PROCESS', 0)
                RETURN
				  END


              WHILE  NOT(@@FETCH_STATUS = -1)
                BEGIN
                 

                  SET @feedin_bisactatus = 0
                  SET @feedin_count = 0
                  SET @feedin_isbn_prefix = 0
                  SET @feedin_price_temp = 0
                  SET @feedin_bookkey = 0
                  SET @feedin_authorkey = 0
                  SET @feedin_retailprice = 0
                  SET @feedin_canadianprice = 0
                  SET @feedin_pubstring = ''
                  SET @feedin_pubdate = ''
                  SET @feedin_reldate = ''
                  SET @feedin_delivdate = ''
                  SET @feed_isbn = ''
                  SET @feedin_title = ''
                  SET @feedin_shorttitle = ''
                  SET @feedin_subtitle = ''
                  SET @feedin_authorlast = ''
                  SET @feedin_temp_isbn = ''
                  SET @feedin_price_temp = ''
                  SET @feedin_pubmonthcode = 0
                  SET @feedin_categorycode = 0
                  SET @feedin_canadianrestriction = 0
                  SET @feedin_bisacstatus_old = 0
                  SET @feedin_pubtowebind = 0
                  SET @feedin_net = 0
                  SET @feed_isbn = RTRIM(@cursor_row_isbn)
                  SET @feed_isbn10 = RTRIM(@cursor_row_isbn)
                  -- 11-05-02  THIS IS JUST TO INSERT ERROR ROWS INTO RERUN TABLE */
                  SET @feed_pricekey = 0
                  SET @feed_pricecount = 0

                  /*  remove reissue isbn book keys */

                  /* 11-19-02  duplicate isbns are present so just get the first one entered */

                  /* 11-19-02  duplicate isbns are present so just get the first one entered */

                  SET @feedin_count = 0

                  SELECT @feedin_count = count(*)
                    FROM isbn i, book b
                    WHERE i.bookkey = b.bookkey AND 
                          ((b.reuseisbnind IS NULL) OR (b.reuseisbnind = 0)) AND 
                           i.isbn10 = RTRIM(@cursor_row_isbn)

                   IF @feedin_count > 1
                   BEGIN  -- duplicate get lowest isbn 
                      SELECT @feedin_bookkey = min(b.bookkey), 
                             @feed_isbn = min(i.isbn)
                        FROM isbn i, book b
                        WHERE i.bookkey = b.bookkey AND 
                                ((b.reuseisbnind IS NULL) OR (b.reuseisbnind = 0)) AND 
                                i.isbn10 = RTRIM(@cursor_row_isbn)

					       SET @errordesc = '(Duplicate isbn on isbn table isbn = ' + isnull(@err_msg,'') + isnull(@feed_isbn,'') + ')'
		
                      INSERT INTO feederror(batchnumber, processdate,errordesc)
					         VALUES ('3', @feed_system_date, @errordesc)
                    END
                    ELSE 
                    BEGIN
                      SELECT @feedin_bookkey = b.bookkey, @feed_isbn = i.isbn
                        FROM isbn i, book b
                        WHERE i.bookkey = b.bookkey AND 
                             ((b.reuseisbnind IS NULL) OR (b.reuseisbnind = 0)) AND 
                              i.isbn10 = RTRIM(@cursor_row_isbn)
                    END


                  IF len(@feed_isbn) = 13
                    BEGIN

                      /* ------------- intialize data for new or old ------- */

                      /* bisacstatus */

                      SELECT @feedin_count = count( * )
                        FROM gentables
                        WHERE gentables.externalcode = @cursor_row_bisacstatuscode AND gentables.tableid = 314

                      IF (@feedin_count > 0)
                      BEGIN
                          SELECT @feedin_bisactatus = gentables.datacode
                            FROM gentables
                            WHERE gentables.externalcode = @cursor_row_bisacstatuscode AND gentables.tableid = 314
                      END
							 ELSE 
							 BEGIN
									  SET @feedin_bisactatus = 0
									  INSERT INTO feederror(batchnumber, processdate,errordesc)
										 VALUES ('3', @feed_system_date,('BISAC STATUS NOT ON gentables; BISAC STATUS NOT UPDATED ' + isnull(@cursor_row_bisacstatuscode, '')))
							 END

                       /*  11-26-02  force BSB to AS datacode; 16 to 1 */

                      IF LTRIM(RTRIM(@cursor_row_bisacstatuscode)) = 'BSB'
							 BEGIN
                        SET @feedin_bisactatus = 1
 							   SELECT @feedin_count = count( * )
								  FROM bookdetail b, gentables g
								 WHERE b.bookkey = @feedin_bookkey AND bisacstatuscode = g.datacode AND g.tableid = 314

								 IF (@feedin_count > 0)
									BEGIN
									  SELECT @feedin_bisacstatus_old = g.datacode, @feedin_pubtowebind = isnull(b.PUBLISHTOWEBIND, 0)
										 FROM bookdetail b, gentables g
										  WHERE b.bookkey = @feedin_bookkey AND bisacstatuscode = g.datacode AND g.tableid = 314
									END
                      END

                      --  retail prices 

                     IF len(@cursor_row_retailprice) > 0
                     BEGIN
                          SET @feedin_price_temp = convert(float,@cursor_row_retailprice)
                          
								  IF @feedin_price_temp > 0
                          BEGIN
                             SET @feedin_retailprice = @feedin_price_temp
                          END
                          ELSE 
                          BEGIN
                            SET @feedin_retailprice = 0
                          END
                      END

                      SELECT @feedin_price_temp = ''

                      IF len(@cursor_row_canadianprice) > 0
                      BEGIN
                          SET @feedin_price_temp = convert(float,@cursor_row_canadianprice)
                          IF @feedin_price_temp > 0
                            BEGIN
                              SET @feedin_canadianprice = @feedin_price_temp
                            END
                          ELSE 
                          BEGIN
                            SET @feedin_canadianprice = 0
                          END
                      END

                     /* 	NET PRICE NOT ON FEED TABLE AS YET UNCOMMENT WHEN ADDED */

                      SELECT @feedin_price_temp = ''
                      IF len(@cursor_row_netprice) > 0
                      BEGIN
                          SET @feedin_price_temp = convert(float,@cursor_row_netprice)
                          IF @feedin_price_temp > 0
                          BEGIN
                            SET @feedin_net =  @feedin_price_temp
                          END
                          ELSE 
                          BEGIN
                            SET @feedin_net = 0
                          END
                      END   /* end NP */

                      /* dates  */

                      /* dates  */
							 -- Publication Date
                      SET @feedin_count = 0
                      SET @feedin_year = 0
                      SET @feedin_count = 0
                      SET @feedin_year = SUBSTRING(RTRIM(LTRIM(@cursor_row_pubdate)), (@feedin_count - 1), 2)

                      IF len(@cursor_row_pubdate) > 0
                      BEGIN
                        IF (@feedin_year < 20)
                          BEGIN
                             -- 8-29-01 to account for
                             -- 			forcing in the 19 instead of 20 for the year change
                             select @feedin_pubdate = CONVERT(datetime,@cursor_row_pubdate,110)
                          END
                        ELSE 
                        BEGIN
                          SET @feedin_pubdate = CONVERT(datetime,(isnull(SUBSTRING(RTRIM(LTRIM(@cursor_row_pubdate)), 1, 6), '') + '19' + isnull(CAST( @feedin_year AS varchar(8000)), '')),110)
                        END
							 END

							 -- Release Date
                      SET @feedin_count = 0
                      SET @feedin_year = 0
                      SET @feedin_count = len(@cursor_row_reldate)
                      SET @feedin_year = SUBSTRING(RTRIM(LTRIM(@cursor_row_reldate)), (@feedin_count - 1), 2)

                      IF len(@cursor_row_reldate) > 0
                      BEGIN
                        IF (@feedin_year < 20)
                        BEGIN
                            /*
                             -- 8-29-01 to account for
                             -- 			forcing in the 19 instead of 20 for the year change
                             --*/
                            SET @feedin_reldate = CONVERT(datetime,@cursor_row_reldate, 110)
                        END
                        ELSE 
                        BEGIN
                          SET @feedin_reldate = CONVERT(datetime,(isnull(SUBSTRING(RTRIM(LTRIM(@cursor_row_reldate)), 1, 6), '') + '19' + isnull(CAST( @feedin_year AS varchar(8000)), '')), 110)
                        END
				          END

							 -- Delivery Date
                      SET @feedin_count = 0
                      SET @feedin_year = 0
                      SET @feedin_count = len(@cursor_row_delivery_date)
                      SET @feedin_year = SUBSTRING(RTRIM(LTRIM(@cursor_row_delivery_date)), (@feedin_count - 1), 2)

                      IF len(@cursor_row_delivery_date) > 0
                      BEGIN
                        IF (@feedin_year < 20)
                        BEGIN
                            /*
                             -- 8-29-01 to account for
                             -- 			forcing in the 19 instead of 20 for the year change
                             --*/
                            SET @feedin_delivdate = CONVERT(datetime,@cursor_row_delivery_date, 110)
                        END
                        ELSE 
                        BEGIN
                          SET @feedin_delivdate = CONVERT(datetime,(isnull(SUBSTRING(RTRIM(LTRIM(@cursor_row_delivery_date)), 1, 6), '') + '19' + isnull(CAST( @feedin_year AS varchar(8000)), '')), 110)
                        END
					       END

                      /*  4-1-04 comment */

                      /*
                       -- if length(feedin_pubdate) > 0 then
                       -- 		feedin_pubmonthcode := to_number(to_char(feedin_pubdate,'MM')) ;
                       -- 	end if;
                       --*/

                      -- canadian restrictionrictions 

                      SELECT @feedin_count = 0

                      IF len(@cursor_row_canadianrestriction) > 0
                      BEGIN

                          SELECT @feedin_count = count(*)
                            FROM gentables
                            WHERE gentables.externalcode = convert(char,@cursor_row_canadianrestriction) AND 
                                  gentables.tableid = 428
									                          
                          IF @feedin_count > 0
                          BEGIN
                              SELECT @feedin_canadianrestriction = gentables.datacode
                                FROM gentables
                                WHERE gentables.externalcode = convert(char,@cursor_row_canadianrestriction) AND 
                                  gentables.tableid = 428
									END
									ELSE 
									BEGIN  
										 select @feedin_tableid = 428	
                               select @feedin_canadianrestriction = @cursor_row_canadianrestriction
										 EXEC feed_insert_gentables @feedin_tableid, @feedin_canadianrestriction, @feedin_canadianrestriction OUTPUT
									END
                       END

                      --  6-28-02 discount code  
                      SELECT @feedin_count = 0

                      IF len(@cursor_row_discountcode) > 0
                      BEGIN

                          SELECT @feedin_count = count( * )
                            FROM gentables
                           WHERE gentables.externalcode = convert(char,(@cursor_row_discountcode)) AND 
                                 gentables.tableid = 459

                          IF (@feedin_count > 0)
                          BEGIN
                              SELECT @feedin_discount = gentables.datacode
                                FROM gentables
                               WHERE gentables.externalcode = convert(char,(@cursor_row_discountcode)) AND 
                                     gentables.tableid = 459

                          END
                          ELSE 
                          BEGIN
                             EXEC feed_insert_gentables 459, @cursor_row_discountcode, @feedin_discount OUTPUT
								  END
                      END
                                         


                      /*  --------------start updating existing title  record ---------- */

                      IF (@feedin_bookkey > 0)
                        BEGIN

                          /*  ------------------start updating tables---------------- */

                           SELECT @feedin_count = 0

                          SELECT @feedin_count = count(*)
                            FROM bookdetail
                           WHERE bookkey = @feedin_bookkey


                          IF @feedin_count = 0
                          BEGIN
                            INSERT INTO bookdetail(bookkey, lastuserid, lastmaintdate)
                              VALUES (@feedin_bookkey, 'VISTAFEED', @feed_system_date)
                          END

                          IF (@feedin_bisactatus > 0)
                          BEGIN

                              UPDATE feederror
                                SET detailtype = (detailtype + 1)
                                WHERE ((batchnumber = '3') AND 
                                        (processdate LIKE (isnull(CAST( @feed_system_date AS varchar(8000)), '') + '%')) AND 
                                        (errordesc = 'Feed Summary: Updates'))

                              select @titlehistory_newvalue=NULL
							         select @titlehistory_newvalue=convert(char (100),@feedin_bisactatus)
                              EXEC TITLEHISTORY_INSERT 4, @feedin_bookkey, 0, '', @titlehistory_newvalue

                              UPDATE bookdetail
                                SET bisacstatuscode = @feedin_bisactatus, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                WHERE bookkey = @feedin_bookkey

                          END

                          /* 8-4-04 modify for all status */

                          SELECT @feedin_count = 0

                          SELECT @feedin_count = count( * )
                            FROM bookdetail
                            WHERE bookkey = @feedin_bookkey
                         

                          IF (@feedin_discount > 0)
                          BEGIN
                            IF (@feedin_count > 0)
                            BEGIN
                                EXEC TITLEHISTORY_INSERT 90, @feedin_bookkey, 0, '', @feedin_discount 

                                UPDATE bookdetail
                                  SET discountcode = @feedin_discount, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                  WHERE bookkey = @feedin_bookkey
                            END
                          END
									

                           /* ***********************update titles that are not NYP,PC, PP, NAB ************** */

                          IF @cursor_row_bisacstatuscode <> 'NYP' AND 
                             @cursor_row_bisacstatuscode <> 'NAB' AND 
                             @cursor_row_bisacstatuscode <> 'PC' AND 
                             @cursor_row_bisacstatuscode <> 'PP'
                            BEGIN

                              /* cartonqty */
                              SELECT @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bindingspecs
                                WHERE bookkey = @feedin_bookkey AND printingkey = 1
                      

                              IF convert(float, @cursor_row_cartonqty ) > 0
                              BEGIN
                                IF @feedin_count > 0
                                  BEGIN
                                                                     
                                    SELECT @feedin_cartonqty = convert(float,@cursor_row_cartonqty)

                                    EXEC TITLEHISTORY_INSERT 89, @feedin_bookkey, 1, '', @feedin_cartonqty

                                    UPDATE bindingspecs
                                      SET cartonqty1 = @feedin_cartonqty, 
                                          lastuserid = 'VISTAFEED', 
                                          lastmaintdate = @feed_system_date
                                    WHERE bookkey = @feedin_bookkey AND printingkey = 1
                                  END
											 END
											 ELSE 
											 BEGIN
													SELECT @feedin_cartonqty = convert(float,@cursor_row_cartonqty)
	
													EXEC TITLEHISTORY_INSERT 89, @feedin_bookkey, 1, '', @feedin_cartonqty
	
													INSERT INTO bindingspecs(bookkey,printingkey,vendorkey,cartonqty1)
													  VALUES (@feedin_bookkey, 1, 0, @feedin_cartonqty)
	
											 END
									   END

                             -- retail price 
                              SELECT @feedin_count = 0
                              /*  list price code is datacode 11 */
                              SELECT @feedin_count = count( * )
                                FROM bookprice
                                WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11

                              IF @feedin_retailprice > 0
                                BEGIN
                                  --  8-27-03 update active row if more than 1 row present -
                                  IF @feedin_count > 0
                                  BEGIN
                                    IF @feedin_count > 1
                                    BEGIN

                                        SELECT @feed_pricecount = count( * )
                                          FROM bookprice
                                          WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11 AND activeind = 1


                                        IF (@feed_pricecount = 1)
                                        BEGIN
                                            EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '6', @feedin_retailprice
 
                                            UPDATE bookprice
                                              SET finalprice = @feedin_retailprice, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                              WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11 AND activeind = 1
                                        END
                                        ELSE 
                                        BEGIN
                                             -- no rows have activeind or all rows have activeind=1
                                             -- 4-1-04  a) if price in match one of bookprice rows finalprice; set that row to active=1  or
                                             --  			set all others to empty (this is the current selling price .. no need to do history
                                             --				since not updating value
                                             --  		b) if price in does not match any then send to error report
                                            
                                            SET @feed_pricefound = 0
                                              DECLARE feed_retailprice CURSOR 
                                              FOR 
                                              SELECT pricekey, activeind, CASE finalprice WHEN  NULL THEN BUDGETPRICE ELSE finalprice END AS LISTPRICE
                                                FROM bookprice
                                               WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11 
                                             
                                              OPEN feed_retailprice

                                              FETCH NEXT FROM feed_retailprice INTO @cursor_row_pricekey, @cursor_row_activeind, @cursor_row_retailprice2

                                              WHILE  NOT(@@FETCH_STATUS = -1)
                                                BEGIN
                                                  IF (@@FETCH_STATUS = 0)
                                                    IF (@cursor_row_retailprice2 = @feedin_retailprice)
                                                      BEGIN

                                                        UPDATE bookprice
                                                          SET activeind = 1, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                                          WHERE pricekey = @cursor_row_pricekey

                                                        /* make the rest activeind null */

                                                        UPDATE bookprice
                                                          SET activeind =  NULL, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                                          WHERE bookkey = @feedin_bookkey AND currencytypecode = 6 AND pricetypecode = 11 AND activeind = 1 AND 
                                                                pricekey = @cursor_row_pricekey

                                                        SET @feed_pricefound = 1

                                                      END
                                                  FETCH NEXT FROM feed_retailprice INTO @cursor_row_pricekey, @cursor_row_activeind, @cursor_row_retailprice2
                                                END
                                              CLOSE feed_retailprice
                                              DEALLOCATE feed_retailprice
                                            END
                                      END
                                    ELSE  -- feedin_count = 1
                                      BEGIN
                                        EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '6', @feedin_retailprice 

                                        UPDATE bookprice
                                           SET finalprice = @feedin_retailprice, activeind = 1, lastuserid = 'VISTAFEED',lastmaintdate = @feed_system_date
                                          WHERE ((bookkey = @feedin_bookkey) AND (currencytypecode = 6) AND (pricetypecode = 11))
                                      END
                                  END
                                  ELSE  -- feedin_count = 0 
                                  BEGIN
                                      EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '6', @feedin_retailprice
									 			  select @v_newkey = generickey from keys
 
                                      INSERT INTO bookprice(pricekey,bookkey,pricetypecode,currencytypecode,activeind,finalprice, 
                                          effectivedate, lastuserid,lastmaintdate)
                                        VALUES (@v_newkey,@feedin_bookkey,11,6, 1,@feedin_retailprice, 
                                            @feed_system_date, 'VISTAFEED',@feed_system_date)
                                    END
                                END
  										END

                              /* canada */

                              /* 7-27-04 do not update canada price for college titles */

                              /*
                               -- feed_orgentry_college := 0;
                               -- 
                               -- select count(*) into feed_orgentry_college from bookorgentry where orglevelkey=1 and orgentrykey=1485
                               --   and bookkey = feedin_bookkey;
                               -- 
                               -- if feed_orgentry_college = 0 then
                               -- 
                               -- feedin_count := 0;
                               -- feed_pricecount := 0;
                               -- 
                               -- 			select count(*)
                               -- 				into feedin_count
                               -- 					from qsidba.bookprice
                               -- 						where bookkey=feedin_bookkey
                               -- 							and currencytypecode=11
                               -- 							and pricetypecode=11;
                               -- 			if feedin_canada > 0 then
                               -- 				if feedin_count>0  then
                               -- 				   if feedin_count > 1 then
                               -- 				    	select count(*) into feed_pricecount
                               -- 						from qsidba.bookprice
                               -- 							where bookkey=feedin_bookkey
                               -- 								and currencytypecode=11
                               -- 								and pricetypecode=11 and activeind= 1;
                               -- 
                               -- 			   		if feed_pricecount = 1 then
                               -- 						titlehistory_insert(9,feedin_bookkey,0,'11',feedin_canada);
                               -- 						update qsidba.bookprice
                               -- 							set finalprice = feedin_canada,
                               -- 								lastuserid='VISTAFEED',
                               -- 								lastmaintdate = feed_system_date
                               -- 									where bookkey=feedin_bookkey
                               -- 										and currencytypecode=11
                               -- 										and pricetypecode=11 and activeind= 1;
                               -- 
                               -- 					else
                               -- 						feed_pricefound :=0;
                               -- 
                               -- 						FOR  cursor_row2 in feed_canadaprice loop
                               -- 							if feed_canadaprice%FOUND then
                               -- 								if cursor_row2.canadaprice = feedin_canada  then
                               -- 									update qsidba.bookprice
                               -- 										set activeind = 1,
                               -- 											lastuserid='VISTAFEED',
                               -- 											lastmaintdate = feed_system_date
                               -- 											  where pricekey = cursor_row2.pricekey;
                               -- 
                               -- 									update qsidba.bookprice
                               -- 										set activeind = null,
                               -- 											lastuserid='VISTAFEED',
                               -- 											lastmaintdate = feed_system_date
                               -- 											   where bookkey=feedin_bookkey
                               -- 												and currencytypecode=11
                               -- 												and pricetypecode=11 and pricekey <> cursor_row2.pricekey;
                               -- 									commit;
                               -- 									feed_pricefound :=1;
                               -- 								end if;
                               -- 							end if;
                               -- 						end loop;
                               -- 						--if feed_pricefound = 0 then
                               -- 							--UTL_FILE.PUT_LINE(lv_file_id_num,('Multple
                               -- --Canada Price on TMM and none match in coming price and more than 1 rows has activeind=1 or no rows
                               -- --have an activeind for isbn ' || feed_isbn));
                               -- 						--end if;
                               -- 
                               -- 					end if;
                               -- 				  else
                               -- 					titlehistory_insert(9,feedin_bookkey,0,'11',feedin_canada);
                               -- 					update qsidba.bookprice
                               -- 					  set finalprice = feedin_canada,
                               -- 					    activeind = 1,
                               -- 					    lastuserid='VISTAFEED',
                               -- 					    lastmaintdate = feed_system_date
                               -- 						where bookkey=feedin_bookkey
                               -- 						  and currencytypecode=11
                               -- 						  and pricetypecode=11;
                               -- 				  end if;
                               -- 				else
                               -- 					titlehistory_insert(9,feedin_bookkey,0,'11',feedin_canada);
                               -- 					insert into qsidba.bookprice (pricekey,bookkey,pricetypecode,
                               -- 						currencytypecode,activeind,finalprice,
                               -- 						effectivedate,lastuserid,lastmaintdate)
                               -- 					values (QSIDBA.qsikeys_seq.nextval,feedin_bookkey,11,11,1,
                               -- 						feedin_canada,feed_system_date,'VISTAFEED',feed_system_date);
                               -- 				end if;
                               -- 			end if;
                               -- 	commit;
                               -- 
                               -- end if;
                               --*/

                             -- 8-4-04 net price -
                              SELECT @feedin_count = 0
                              SELECT @feed_pricecount = 0

                              SELECT @feedin_count = count( * )
                                FROM bookprice
                                WHERE ((bookkey = @feedin_bookkey) AND 
                                        (currencytypecode = 6) AND 
                                        (pricetypecode = 9))

                              IF (@feedin_net > 0)
										BEGIN
                                IF (@feedin_count > 0)
                                BEGIN
                                  IF (@feedin_count > 1)
                                    BEGIN

                                      SELECT @feed_pricecount = count( * )
                                        FROM bookprice
                                        WHERE ((bookkey = @feedin_bookkey) AND 
                                                (currencytypecode = 6) AND 
                                                (pricetypecode = 9) AND 
                                                (activeind = 1))

                                      IF (@feed_pricecount = 1)
                                      BEGIN
                                          EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '9', @feedin_net 

                                          UPDATE bookprice
                                            SET finalprice = @feedin_net, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                            WHERE ((bookkey = @feedin_bookkey) AND 
                                                    (currencytypecode = 6) AND 
                                                    (pricetypecode = 9) AND 
                                                    (activeind = 1))
                                      END
                                      ELSE -- feedin pricecount > 1
                                      BEGIN
                                          SET @feed_pricefound = 0
                                          DECLARE feed_netprice CURSOR 
                                            FOR 
                                            SELECT pricekey, activeind, CASE finalprice WHEN  NULL THEN BUDGETPRICE ELSE finalprice END AS NETPRICE
                                              FROM bookprice
                                             WHERE ((bookkey = @feedin_bookkey) AND 
                                                    (currencytypecode = 6) AND 
                                                    (pricetypecode = 9))
                                            
                                            OPEN feed_netprice

                                            FETCH NEXT FROM feed_netprice INTO @cursor_row_pricekey, @cursor_row_activeind, @cursor_row_netprice2

                                            WHILE  NOT(@@FETCH_STATUS = -1)
                                              BEGIN
                                                IF (@@FETCH_STATUS = 0)
                                                  IF (@cursor_row_netprice2 = @feedin_net)
                                                    BEGIN

                                                      UPDATE bookprice
                                                        SET activeind = 1, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                                        WHERE (pricekey = @cursor_row_pricekey)

                                                      UPDATE bookprice
                                                        SET activeind =  NULL, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                                        WHERE bookkey = @feedin_bookkey AND 
                                                              currencytypecode = 6 AND pricetypecode = 9 AND 
                                                              pricekey = @cursor_row_pricekey

                                                     
                                                      SET @feed_pricefound = 1

                                                    END
                                                 FETCH NEXT FROM feed_netprice INTO @cursor_row_pricekey, @cursor_row_activeind, @cursor_row_netprice2
															 END
														  CLOSE feed_netprice
														  DEALLOCATE feed_netprice
													END  -- feedin pricecount > 1
                                   	END
                                    ELSE -- feedin count = 1
                                    BEGIN
                                      EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '9', @feedin_net 
                                      UPDATE bookprice
                                         SET finalprice = @feedin_net,activeind = 1,lastuserid = 'VISTAFEED',lastmaintdate = @feed_system_date
                                       WHERE bookkey = @feedin_bookkey AND 
                                             currencytypecode = 6 AND pricetypecode = 9
                                    END
                                END
                                ELSE -- feedin count = 0
                                BEGIN
                                    EXEC TITLEHISTORY_INSERT 9, @feedin_bookkey, 0, '9', @feedin_net
 
                                    select @v_newkey = generickey from keys

                                    INSERT INTO bookprice
                                      (pricekey,bookkey,pricetypecode,currencytypecode,activeind,finalprice,effectivedate,lastuserid,lastmaintdate)
                                      VALUES 
                                        (@v_newkey,@feedin_bookkey,9,6,1,@feedin_net, @feed_system_date,'VISTAFEED',@feed_system_date)
                                 END
										END
                              /* end NP */

                               /* pub date */
                              SELECT @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bookdates
                               WHERE bookkey = @feedin_bookkey AND printingkey = 1 AND datetypecode = 8
  
                              IF len(@feedin_pubdate) > 0
                                IF (@feedin_count > 0)
                                BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '8', @feedin_pubdate 

                                    UPDATE bookdates
                                       SET activedate = @feedin_pubdate, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                     WHERE bookkey = @feedin_bookkey AND 
                                           printingkey = 1 AND 
                                           datetypecode = 8
                                END
                                ELSE 
                                BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '8', @feedin_pubdate 

                                    INSERT INTO bookdates(bookkey,printingkey, datetypecode,activedate, 
                                        actualind, sortorder,lastuserid, lastmaintdate )
                                      VALUES (@feedin_bookkey, 1, 8, @feedin_pubdate, 
                                          0, 1, 'VISTAFEED', @feed_system_date )
                                 END
                              

                              /* rel date */

                              SET @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bookdates
                               WHERE bookkey = @feedin_bookkey AND printingkey = 1 AND datetypecode = 32

                              IF len(@feedin_reldate) > 0
                              BEGIN
                                IF (@feedin_count > 0)
                                  BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '32', @feedin_reldate 

                                    UPDATE bookdates
                                       SET activedate = @feedin_reldate, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                     WHERE bookkey = @feedin_bookkey AND printingkey = 1 AND datetypecode = 32
                                  END
                                ELSE 
                                BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '32', @feedin_reldate 

                                    INSERT INTO bookdates(bookkey,printingkey, datetypecode,activedate, 
                                        actualind, sortorder,lastuserid, lastmaintdate )
                                      VALUES (@feedin_bookkey, 1, 32, @feedin_reldate, 
                                          0, 2, 'VISTAFEED', @feed_system_date )
                                 END
                               END


                              /* delivery date */

                              SET @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bookdates
                               WHERE bookkey = @feedin_bookkey AND printingkey = 1 AND datetypecode = 528

                              IF len(@feedin_delivdate) > 0
                              BEGIN
                                IF (@feedin_count > 0)
                                  BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '528', @feedin_delivdate 

                                    UPDATE bookdates
                                       SET activedate = @feedin_delivdate, lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                     WHERE bookkey = @feedin_bookkey AND printingkey = 1 AND datetypecode = 528
                                  END
                                ELSE 
                                  BEGIN
                                    EXEC TITLEHISTORY_INSERT 36, @feedin_bookkey, 1, '528', @feedin_delivdate 

                                    INSERT INTO bookdates(bookkey,printingkey, datetypecode,activedate, 
                                        actualind, sortorder,lastuserid, lastmaintdate )
                                      VALUES (@feedin_bookkey, 1, 528, @feedin_delivdate, 
                                          0, 2, 'VISTAFEED', @feed_system_date )
                                  END
                              END

                                -- projectisbn does it need validation of isbn prefix:1 nope per john s. bookdetail
                               -- 	vista_productnumber
                              SET @feedin_count = 0

                              SELECT @feedin_count = count( * )
                                FROM bookdetail
                                WHERE (bookkey = @feedin_bookkey)

                              IF LTRIM(RTRIM(@cursor_row_projectisbn)) > 0
                              BEGIN
										  IF (@feedin_count > 0)
                                BEGIN
                                  UPDATE bookdetail
                                     SET vistaprojectnumber = SUBSTRING(RTRIM(@cursor_row_projectisbn), 1, 13), 
                                         lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                   WHERE (bookkey = @feedin_bookkey)
                                END
                                ELSE 
                                BEGIN
                                  INSERT INTO bookdetail(bookkey, vistaprojectnumber,lastmaintdate,lastuserid)
                                    VALUES (@feedin_bookkey, 
                                        SUBSTRING(RTRIM(@cursor_row_projectisbn), 1, 13), 
                                        @feed_system_date,'VISTAFEED')
                                END
                              END


                              -- categorycode -- per john s./doug does not need to be a gentables book detail-
                              SET @feedin_count = 0

                              SELECT @feedin_count = count(*)
                                FROM bookdetail
                               WHERE bookkey = @feedin_bookkey
                             
                              IF LTRIM(RTRIM(@cursor_row_categorycode)) > 0
                              BEGIN
                                IF (@feedin_count > 0)
                                BEGIN
                                  UPDATE bookdetail
                                     SET vistacategorycode = SUBSTRING(RTRIM(@cursor_row_categorycode), 1, 6), lastuserid = 'VISTAFEED', lastmaintdate = @feed_system_date
                                   WHERE bookkey = @feedin_bookkey
                                END
                                ELSE 
                                BEGIN
                                  INSERT INTO bookdetail
                                    (bookkey,vistacategorycode,lastmaintdate,lastuserid )
                                    VALUES 
                                      (@feedin_bookkey,SUBSTRING(RTRIM(@cursor_row_categorycode), 1, 6),
                                        @feed_system_date,'VISTAFEED')
    						    END
                        --END

                        END    /*  bookkey > 0  */

                      IF @feedin_bookkey = 0
                      BEGIN
                          UPDATE feederror
                             SET detailtype = (detailtype + 1)
                           WHERE batchnumber = '3' AND 
                                 processdate >=  @feed_system_date AND 
                                 errordesc LIKE 'Feed Summary: Rejected%'
     						 END -- bookkey = 0 new title

                    END

                   FETCH NEXT FROM feed_titles INTO @cursor_row_isbn,@cursor_row_bisacstatuscode,@cursor_row_retailprice, 
							@cursor_row_canadianprice,@cursor_row_categorycode,@cursor_row_pubdate,@cursor_row_reldate,@cursor_row_cartonqty, 
							@cursor_row_projectisbn,@cursor_row_canadianrestriction,@cursor_row_discountcode,@cursor_row_netprice, 
							@cursor_row_delivery_date

                END

              CLOSE feed_titles

              DEALLOCATE feed_titles

            END

            /*   delete when complete since looping through cursor no need delete truncate when reloading */

            /* DELETE FROM feedin_titles; */

            /* commit; */

             INSERT INTO feederror(batchnumber, processdate,errordesc)
					         VALUES ('3', @feed_system_date,'Titles Completed')

            IF (@@TRANCOUNT > 0)
                COMMIT WORK

            IF (cursor_status(N'local', N'feed_titles') = 1)
              BEGIN
                CLOSE feed_titles
                DEALLOCATE feed_titles
              END

          END TRY
          BEGIN CATCH

            DECLARE 
              @ErrorMessage nvarchar(4000),
              @ErrorNumber int,
              @ExceptionIdentifier nvarchar(4000)            

            SELECT @ErrorMessage = ERROR_MESSAGE(), @ErrorNumber = ERROR_NUMBER()

            SELECT @ExceptionIdentifier = SYSDB.SSMA.db_error_get_oracle_exception_id(@ErrorMessage, @ErrorNumber)

            BEGIN

              SET @err_msg = SYSDB.SSMA.SUBSTR3_VARCHAR(SYSDB.SSMA.DB_ERROR_SQLERRM_0(@ExceptionIdentifier), 1, 100)

              INSERT INTO feederror
                (batchnumber, processdate, errordesc)
                VALUES ('3', @feed_system_date, ('Error on vista feed in bookkey = ' + isnull(@err_msg, '') + isnull(CAST( @feedin_bookkey AS varchar(8000)), '')))

              IF (@@TRANCOUNT > 0)
                  COMMIT WORK

              INSERT INTO feed_titles_rerun
                (isbn,bisacstatuscode,retailprice,canadianprice,categorycode,pubdate,reldate,cartonqty,projectisbn,
                 canadianrestriction,discountcode,netprice,delivery_date)
                SELECT 
                   isbn,bisacstatuscode,retailprice,canadianprice,categorycode,pubdate,reldate,cartonqty,projectisbn,
                  canadianrestriction,discountcode,netprice,delivery_date
                  FROM feedin_titles
                  WHERE (isbn = @feed_isbn)

              IF (@@TRANCOUNT > 0)
                  COMMIT WORK

              DELETE FROM feedin_titles

              IF (@@TRANCOUNT > 0)
                  COMMIT WORK

            END

          END CATCH
      END

GO



