if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[AUTHINDEX_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[AUTHINDEX_VIEW]
GO

create view dbo.AUTHINDEX_VIEW(BOOKKEY, LASTNAME, FIRSTNAME, MIDDLENAME, DISPLAYNAME, AUTHORNAME, AUTHORTYPE, AUTHORKEY, TITLE, CORPORATECONTRIBUTORIND, AUTHORSUFFIX, AUTHORDEGREE, AUTHORURL, BIOGRAPHY, SORTORDER)  AS 
  SELECT 
      BA.BOOKKEY, 
      A.LASTNAME, 
      A.FIRSTNAME, 
      A.MIDDLENAME, 
      CASE A.MIDDLENAME WHEN  NULL THEN (isnull(A.LASTNAME, '') + ', ' + isnull(A.FIRSTNAME, '')) ELSE (isnull(A.LASTNAME, '') + ', ' + isnull(A.FIRSTNAME, '') + ' ' + isnull(A.MIDDLENAME, '')) END AS DISPLAYNAME, 
      CASE A.MIDDLENAME WHEN  NULL THEN (isnull(A.FIRSTNAME, '') + ' ' + isnull(A.LASTNAME, '')) ELSE (isnull(A.FIRSTNAME, '') + ' ' + isnull(A.MIDDLENAME, '') + ' ' + isnull(A.LASTNAME, '')) END AS AUTHORNAME, 
      [AT].DATADESC AS AUTHORTYPE, 
      A.AUTHORKEY, 
      A.TITLE, 
      A.CORPORATECONTRIBUTORIND, 
      A.AUTHORSUFFIX, 
      A.AUTHORDEGREE, 
      A.AUTHORURL, 
      A.BIOGRAPHY, 
      BA.SORTORDER
    FROM dbo.BOOKAUTHOR BA, dbo.AUTHOR A, dbo.AUTHORTY_VIEW [AT]
    WHERE ((BA.AUTHORKEY = A.AUTHORKEY) AND 
            (BA.AUTHORTYPECODE = [AT].DATACODE))
go
GRANT SELECT ON AUTHINDEX_VIEW TO public
go