if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BESTPUBDATE_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BESTPUBDATE_VIEW]
GO

create view dbo.BESTPUBDATE_VIEW(BOOKKEY, PRINTINGKEY, BESTPUBDATE)  AS 
  SELECT dbo.PRINTING.BOOKKEY, dbo.PRINTING.PRINTINGKEY, CASE dbo.BOOKDATES.ACTIVEDATE WHEN  NULL THEN dbo.BOOKDATES.ESTDATE ELSE dbo.BOOKDATES.ACTIVEDATE END AS BESTPUBDATE
    FROM dbo.BOOKDATES, dbo.PRINTING
    WHERE ((dbo.BOOKDATES.BOOKKEY = dbo.PRINTING.BOOKKEY) AND 
            (dbo.BOOKDATES.PRINTINGKEY = dbo.PRINTING.PRINTINGKEY) AND 
            (dbo.BOOKDATES.DATETYPECODE = 8))




go
GRANT SELECT ON BESTPUBDATE_VIEW TO public
go