if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BESTAUTHOR_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BESTAUTHOR_VIEW]
GO

create view dbo.BESTAUTHOR_VIEW(BOOKKEY, BESTAUTHOR)  AS 
  SELECT dbo.BOOK.BOOKKEY, CASE dbo.BOOKDETAIL.FULLAUTHORDISPLAYNAME WHEN  NULL THEN CASE dbo.AUTH1_VIEW.AUTHNAME1 WHEN  NULL THEN  NULL ELSE CASE dbo.AUTH2_VIEW.AUTHNAME2 WHEN  NULL THEN dbo.AUTH1_VIEW.AUTHNAME1 ELSE CASE dbo.AUTH3_VIEW.AUTHNAME3 WHEN  NULL THEN (isnull(dbo.AUTH1_VIEW.AUTHNAME1, '') + ', ' + isnull(dbo.AUTH2_VIEW.AUTHNAME2, '')) ELSE CASE dbo.AUTH4_VIEW.AUTHNAME4 WHEN  NULL THEN (isnull(dbo.AUTH1_VIEW.AUTHNAME1, '') + ', ' + isnull(dbo.AUTH2_VIEW.AUTHNAME2, '') + ', ' + isnull(dbo.AUTH3_VIEW.AUTHNAME3, '')) ELSE (isnull(dbo.AUTH1_VIEW.AUTHNAME1, '') + ', ' + isnull(dbo.AUTH2_VIEW.AUTHNAME2, '') + ', ' + isnull(dbo.AUTH3_VIEW.AUTHNAME3, '') + ', ' + isnull(dbo.AUTH4_VIEW.AUTHNAME4, '')) END END END END ELSE dbo.BOOKDETAIL.FULLAUTHORDISPLAYNAME END AS BESTAUTHOR
    FROM dbo.BOOKDETAIL, dbo.BOOK
       LEFT JOIN dbo.AUTH1_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTH1_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTH2_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTH2_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTH3_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTH3_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTH4_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTH4_VIEW.BOOKKEY)
    WHERE (dbo.BOOK.BOOKKEY = dbo.BOOKDETAIL.BOOKKEY)




go
GRANT SELECT ON BESTAUTHOR_VIEW TO public
go