if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BESTPUBMONTH_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BESTPUBMONTH_VIEW]
GO

create view dbo.BESTPUBMONTH_VIEW(BOOKKEY, PRINTINGKEY, BESTPUBMONTH)  AS 
  SELECT dbo.PRINTING.BOOKKEY, dbo.PRINTING.PRINTINGKEY, CASE dbo.BOOKDATES.ACTIVEDATE WHEN  NULL THEN SYSDB.SSMA.TO_CHAR_DATE(dbo.BOOKDATES.ESTDATE, 'MON YYYY') ELSE SYSDB.SSMA.TO_CHAR_DATE(dbo.BOOKDATES.ACTIVEDATE, 'MON YYYY') END AS BESTPUBMONTH
    FROM dbo.BOOKDATES, dbo.PRINTING
    WHERE ((dbo.BOOKDATES.BOOKKEY = dbo.PRINTING.BOOKKEY) AND 
            (dbo.BOOKDATES.PRINTINGKEY = dbo.PRINTING.PRINTINGKEY) AND 
            (dbo.BOOKDATES.DATETYPECODE = 8))




go
GRANT SELECT ON BESTPUBMONTH_VIEW TO public
go