if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BOOKCATALOGTITLES_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BOOKCATALOGTITLES_VIEW]
GO
create view dbo.BOOKCATALOGTITLES_VIEW(BOOKKEY, CATALOGTITLE, CATALOGTYPE, [SECTION], SEASON, [POSITION], WEIGHT, CATALOGPAGENUMBER, FINALIZEDIND, CATALOGHEADING)  AS 

  SELECT 
      b.BOOKKEY, 
      c.CATALOGTITLE, 
      c.CATALOGTYPE, 
      c.[SECTION], 
      c.SEASON, 
      c.[POSITION], 
      c.WEIGHT, 
      c.CATALOGPAGENUMBER, 
      c.FINALIZEDIND, 
      c.CATALOGHEADING
    FROM dbo.BOOK b
       LEFT JOIN dbo.CATALOGTITLES_VIEW c  ON (b.BOOKKEY = c.BOOKKEY)


go
GRANT SELECT ON BOOKCATALOGTITLES_VIEW TO public
go