if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BOOK1]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BOOK1]
GO
create view dbo.BOOK1(BOOKKEY, TITLE, SKU, ISBN, ISBN10, STANDARDIND, CREATIONDATE, CYCLE, MEDIATYPECODE, MEDIATYPESUBCODE, LASTUSERID, LASTMAINTDATE, SPECSRECIND, NEXTPRINTINGNBR, TTLCD, SCALEORGENTRYKEY, TITLEUPPER, PRODUCTNUMBER, REUSEISBNIND, AUTHORNAME, EAN)  AS 
  SELECT 
      dbo.BOOK.BOOKKEY, 
      dbo.BOOK.TITLE, 
      dbo.BOOK.SKU, 
      dbo.ISBN.ISBN, 
      dbo.ISBN.ISBN10, 
      dbo.BOOK.STANDARDIND, 
      dbo.BOOK.CREATIONDATE, 
      dbo.BOOK.CYCLE, 
      dbo.BOOKDETAIL.MEDIATYPECODE, 
      dbo.BOOKDETAIL.MEDIATYPESUBCODE, 
      dbo.BOOK.LASTUSERID, 
      dbo.BOOK.LASTMAINTDATE, 
      dbo.BOOK.SPECSRECIND, 
      dbo.BOOK.NEXTPRINTINGNBR, 
      dbo.ISBN.TTLCD, 
      dbo.BOOK.SCALEORGENTRYKEY, 
      UPPER(dbo.BOOK.TITLE),
      dbo.PRODUCTNUMBER.PRODUCTNUMBER, 
      dbo.BOOK.REUSEISBNIND, 
      '                               ', 
      dbo.ISBN.EAN
    FROM dbo.BOOK, dbo.BOOKDETAIL, dbo.ISBN, dbo.PRODUCTNUMBER
    WHERE ((dbo.BOOK.BOOKKEY = dbo.BOOKDETAIL.BOOKKEY) AND 
            (dbo.BOOKDETAIL.BOOKKEY = dbo.ISBN.BOOKKEY) AND 
            (dbo.BOOK.BOOKKEY = dbo.PRODUCTNUMBER.BOOKKEY))


go
GRANT SELECT ON BOOK1 TO public
go