if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[COLLEGE_COURSES]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[COLLEGE_COURSES]
GO
create view dbo.COLLEGE_COURSES(TABLEID, DATACODE, DATADESC, DELETESTATUS, APPLID, SORTORDER, TABLEMNEMONIC, EXTERNALCODE, DATADESCSHORT, LASTUSERID, LASTMAINTDATE, NUMERICDESC1, NUMERICDESC2, SDATACODE, SDATASUBCODE, SDATADESC, SDELETESTATUS, SAPPLID, SSORTORDER, STABLEMNEMONIC, SEXTERNALCODE, SDATADESCSHORT, SLASTUSERID, SLASTMAINTDATE, SNUMERICDESC1, SNUMERICDESC2)  AS 
  SELECT 
      dbo.GENTABLES.TABLEID, 
      dbo.GENTABLES.DATACODE, 
      dbo.GENTABLES.DATADESC, 
      dbo.GENTABLES.DELETESTATUS, 
      dbo.GENTABLES.APPLID, 
      dbo.GENTABLES.SORTORDER, 
      dbo.GENTABLES.TABLEMNEMONIC, 
      dbo.GENTABLES.EXTERNALCODE, 
      dbo.GENTABLES.DATADESCSHORT, 
      dbo.GENTABLES.LASTUSERID, 
      dbo.GENTABLES.LASTMAINTDATE, 
      dbo.GENTABLES.NUMERICDESC1, 
      dbo.GENTABLES.NUMERICDESC2, 
      dbo.SUBGENTABLES.DATACODE AS SDATACODE, 
      dbo.SUBGENTABLES.DATASUBCODE AS SDATASUBCODE, 
      dbo.SUBGENTABLES.DATADESC AS SDATADESC, 
      dbo.SUBGENTABLES.DELETESTATUS AS SDELETESTATUS, 
      dbo.SUBGENTABLES.APPLID AS SAPPLID, 
      dbo.SUBGENTABLES.SORTORDER AS SSORTORDER, 
      dbo.SUBGENTABLES.TABLEMNEMONIC AS STABLEMNEMONIC, 
      dbo.SUBGENTABLES.EXTERNALCODE AS SEXTERNALCODE, 
      dbo.SUBGENTABLES.DATADESCSHORT AS SDATADESCSHORT, 
      dbo.SUBGENTABLES.LASTUSERID AS SLASTUSERID, 
      dbo.SUBGENTABLES.LASTMAINTDATE AS SLASTMAINTDATE, 
      dbo.SUBGENTABLES.NUMERICDESC1 AS SNUMERICDESC1, 
      dbo.SUBGENTABLES.NUMERICDESC2 AS SNUMERICDESC2
    FROM dbo.GENTABLES, dbo.SUBGENTABLES
    WHERE ((dbo.GENTABLES.DATACODE = dbo.SUBGENTABLES.DATACODE) AND 
            (dbo.GENTABLES.TABLEID = 436) AND 
            (dbo.SUBGENTABLES.TABLEID = 436))


go
GRANT SELECT ON COLLEGE_COURSES TO public
go