if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CONTRACT_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[CONTRACT_VIEW]
GO
create view dbo.CONTRACT_VIEW(CONTRACTKEY, CONTRACTNUMBER, CONTRACTSTATUSCODE, CONTRACTTYPE, EDITORCODE, BOOKKEY)  AS 


  SELECT 
      dbo.CONTRACT.CONTRACTKEY, 
      dbo.CONTRACT.CONTRACTNUMBER, 
      dbo.CONTRACT.CONTRACTSTATUSCODE, 
      dbo.CONTRACT.CONTRACTTYPE, 
      dbo.CONTRACT.EDITORCODE, 
      dbo.CONTRACTBOOK.BOOKKEY
    FROM dbo.CONTRACT, dbo.CONTRACTBOOK
    WHERE (dbo.CONTRACT.CONTRACTKEY = dbo.CONTRACTBOOK.CONTRACTKEY)


go
GRANT SELECT ON CONTRACT_VIEW TO public
go