sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_ActiveDate2.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_FinalPrice3c.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_FinalPrice_ResortPriceList.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_MiscItem6.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_Table_bindingspecs_printingkey2.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_Table_book3.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_Table_bookdetail3.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_Table_isbn3.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_Table_printing3_printingkey.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_Util_DelimitedFieldPos3.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_Util_GentablesCodeAndDescMap.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_Util_GentablesCodeMap4.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_ActiveDate7.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_FinalPrice7.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_MiscItem7.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_QsiJob_End2.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_QsiJob_ErrorStats2.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_QsiJob_MessageBuilder.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_QsiJob_Start.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_QsiJob_WriteMessage.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Table7.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_Common_RemoveAllLeadingZeroes.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_Common_RemoveLeadingZeroes.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_Date8_Reverse.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_MiscItem_RemoveLeadingZeroes.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_MiscItem_RemoveLeadingZeroes_ZeroIsNull.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_Price_RemoveLeadingZeroes.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_Table_RemoveAllLeadingZeroes.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_Table_RemoveLeadingZeroes.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Transform_Table_RemoveLeadingZeroes_ZeroIsNull.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_DateCode.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_DateCode_Date.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_DateCode_Date_IgnoreEmpty.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_DateTypeCode.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_MiscItemType5_Exists3.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_PriceCode.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_PriceCode_Price.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_PriceCode_Price_IgnoreEmpty.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_PriceCode_Price_NonExistentIgnoreEmpty.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Price_ErrorEmpty.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Price_ErrorZero.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Price_IgnoreEmpty.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Price_IgnoreZero.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Price_NonExistentIgnoreEmpty.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Price_NonExistentIgnoreZero.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_RefTableItem.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_RefTableItem_Exists3.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Table_Number_ErrorEmpty.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Table_Number_ErrorZero.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Table_Number_IgnoreEmpty2.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Table_Number_IgnoreZero.sql >> UpdFld_Baseline_LoadSQL.log
sqlcmd -S MONTY -U qsidba -P qsidba -d AMP_DEV -i UpdFld_XVQ_Validate_Table_Number_NonExistentIgnoreZero2.sql >> UpdFld_Baseline_LoadSQL.log
