if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BESTCANPRICE_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BESTCANPRICE_VIEW]
GO

create view dbo.BESTCANPRICE_VIEW(BOOKKEY, BESTCANPRICE)  AS 
  SELECT dbo.BOOK.BOOKKEY, CASE dbo.BOOKPRICE.FINALPRICE WHEN  NULL THEN dbo.BOOKPRICE.BUDGETPRICE ELSE dbo.BOOKPRICE.FINALPRICE END AS BESTCANPRICE
    FROM dbo.BOOKPRICE, dbo.BOOK
    WHERE ((dbo.BOOKPRICE.BOOKKEY = dbo.BOOK.BOOKKEY) AND 
            (dbo.BOOKPRICE.PRICETYPECODE = 11) AND 
            (dbo.BOOKPRICE.CURRENCYTYPECODE = 11) AND 
            (dbo.BOOKPRICE.ACTIVEIND = 1))




go
GRANT SELECT ON BESTCANPRICE_VIEW TO public
go