if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BESTINSERT_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BESTINSERT_VIEW]
GO


create view dbo.BESTINSERT_VIEW(BOOKKEY, PRINTINGKEY, BESTINSERT)  AS 
  SELECT dbo.PRINTING.BOOKKEY, dbo.PRINTING.PRINTINGKEY, CASE dbo.PRINTING.ACTUALINSERTILLUS WHEN  NULL THEN dbo.PRINTING.ESTIMATEDINSERTILLUS ELSE dbo.PRINTING.ACTUALINSERTILLUS END AS BESTINSERT
    FROM dbo.PRINTING
    WHERE (dbo.PRINTING.PRINTINGKEY = 1)



go
GRANT SELECT ON BESTINSERT_VIEW TO public
go