if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BESTSEASON_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BESTSEASON_VIEW]
GO
create view dbo.BESTSEASON_VIEW(BOOKKEY, PRINTINGKEY, BESTSEASON)  AS 
  SELECT dbo.BESTSEASONKEY_VIEW.BOOKKEY, dbo.BESTSEASONKEY_VIEW.PRINTINGKEY, dbo.GENTABLES.DATADESC AS BESTSEASON
    FROM dbo.BESTSEASONKEY_VIEW, dbo.GENTABLES, dbo.SEASON
    WHERE ((dbo.BESTSEASONKEY_VIEW.BESTSEASONKEY = dbo.SEASON.SEASONKEY) AND 
            (dbo.GENTABLES.DATACODE = dbo.SEASON.SEASONTYPECODE) AND 
            (dbo.GENTABLES.TABLEID = 289))

go
GRANT SELECT ON BESTSEASON_VIEW TO public
go