if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BOOKLASTMAINTDATE_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BOOKLASTMAINTDATE_VIEW]
GO
create view dbo.BOOKLASTMAINTDATE_VIEW(BOOKKEY, LASTMAINTDATE)  AS 
  SELECT dbo.TITLEHISTORY.BOOKKEY, max(dbo.TITLEHISTORY.LASTMAINTDATE)
    FROM dbo.TITLEHISTORY
    WHERE (dbo.TITLEHISTORY.LASTMAINTDATE >= '25-FEB-2003')
    GROUP BY dbo.TITLEHISTORY.BOOKKEY


go
GRANT SELECT ON BOOKLASTMAINTDATE_VIEW TO public
go