if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CONTRACT_LIC_BOOK]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[CONTRACT_LIC_BOOK]
GO
create view dbo.CONTRACT_LIC_BOOK(C_CONTRACTKEY, C_BOOKKEY, L_CONTRACTKEY)  AS 

  SELECT DISTINCT dbo.CONTRACTBOOK.CONTRACTKEY AS C_CONTRACTKEY, dbo.CONTRACTBOOK.BOOKKEY AS C_BOOKKEY, dbo.CONTRACTBOOKLICENSE.CONTRACTKEY AS L_CONTRACTKEY
    FROM dbo.CONTRACTBOOK, dbo.CONTRACTBOOKLICENSE
    WHERE (dbo.CONTRACTBOOK.CONTRACTKEY = dbo.CONTRACTBOOKLICENSE.CONTRACTKEY)

go
GRANT SELECT ON CONTRACT_LIC_BOOK TO public
go