if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[EBOOKFORMAT_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[EBOOKFORMAT_VIEW]
GO
create view dbo.EBOOKFORMAT_VIEW(TABLEID, DATACODE, DATASUBCODE, DATADESC, DELETESTATUS, APPLID, SORTORDER, TABLEMNEMONIC, EXTERNALCODE, DATADESCSHORT, LASTUSERID, LASTMAINTDATE, NUMERICDESC1, NUMERICDESC2)  AS 
  SELECT 
      dbo.SUBGENTABLES.TABLEID, 
      dbo.SUBGENTABLES.DATACODE, 
      dbo.SUBGENTABLES.DATASUBCODE, 
      dbo.SUBGENTABLES.DATADESC, 
      dbo.SUBGENTABLES.DELETESTATUS, 
      dbo.SUBGENTABLES.APPLID, 
      dbo.SUBGENTABLES.SORTORDER, 
      dbo.SUBGENTABLES.TABLEMNEMONIC, 
      dbo.SUBGENTABLES.EXTERNALCODE, 
      dbo.SUBGENTABLES.DATADESCSHORT, 
      dbo.SUBGENTABLES.LASTUSERID, 
      dbo.SUBGENTABLES.LASTMAINTDATE, 
      dbo.SUBGENTABLES.NUMERICDESC1, 
      dbo.SUBGENTABLES.NUMERICDESC2
    FROM dbo.SUBGENTABLES
    WHERE ((dbo.SUBGENTABLES.TABLEID = 312) AND 
            (dbo.SUBGENTABLES.DATACODE = 14))


go
GRANT SELECT ON EBOOKFORMAT_VIEW TO public
go