if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[FILE_LOCATION_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[FILE_LOCATION_VIEW]
GO
create view dbo.FILE_LOCATION_VIEW(BOOKKEY, FILESTATUSCODE, FILETYPECODE, DATADESC, NOTES, PATHNAME, PRINTINGKEY, SENDTOELOQUENCEIND, SORTORDER)  AS 

  /*****
  *  WARNING ORA2MS-4036 line: 1 col: 1: View attribute WITH READ ONLY cannot be converted. Will be ignored.
  *****/

  SELECT 
      dbo.FILELOCATION.BOOKKEY, 
      dbo.FILELOCATION.FILESTATUSCODE, 
      dbo.FILELOCATION.FILETYPECODE, 
      dbo.GENTABLES.DATADESC, 
      dbo.FILELOCATION.NOTES, 
      dbo.FILELOCATION.PATHNAME, 
      dbo.FILELOCATION.PRINTINGKEY, 
      dbo.FILELOCATION.SENDTOELOQUENCEIND, 
      dbo.FILELOCATION.SORTORDER
    FROM dbo.FILELOCATION, dbo.GENTABLES
    WHERE ((dbo.FILELOCATION.PRINTINGKEY = '1') AND 
            (dbo.GENTABLES.TABLEID = 354) AND 
            (dbo.GENTABLES.DATACODE = dbo.FILELOCATION.FILETYPECODE))


go
GRANT SELECT ON FILE_LOCATION_VIEW TO public
go