
/******************************************************************************************
**  Executes the qutl_insert_gentableitem procedure for the Standard Specification Items
*******************************************************************************************/

BEGIN

  DECLARE
   @v_tableid INT,
   @v_datacode INT,
   @v_datasubcode INT,
   @v_datasub2code INT,
   @v_itemtype INT,
   @v_classcode INT,   
   @v_error_code  INT,
   @v_error_desc VARCHAR(2000) 
   
SET @v_error_code = 0
SET @v_error_desc = ' ' 
 
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',22,'Other Format', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 1	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',23,'Jacket Vendor ', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 1	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',24,'Print Vendor', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 1	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
					
					
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',22,'Other Format', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 3	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',23,'Jacket Vendor ', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 3	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',24,'Print Vendor', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 3	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
					
					
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',22,'Other Format', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 9	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',23,'Jacket Vendor ', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 9	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',24,'Print Vendor', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 9	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
					
					
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',22,'Other Format', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 5	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',23,'Jacket Vendor ', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 5	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',24,'Print Vendor', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 5	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
					
					
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',22,'Other Format', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 14	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',23,'Jacket Vendor ', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 14	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc
exec qutl_get_subgentables_codes_by_qsi_or_desc 616,1,'Summary',24,'Print Vendor', @v_datacode OUTPUT,  @v_datasubcode OUTPUT, @v_error_code OUTPUT, @v_error_desc OUTPUT	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc   SET @v_error_code = 0   SET  @v_error_desc = ' ' 	SELECT @v_itemtype = datacode from gentables where tableid = 550 and qsicode = 14	SET @v_classcode =  0	IF (@v_itemtype <>0 AND @v_datacode <> 0 AND @v_datasubcode <>0)   BEGIN exec qutl_insert_gentablesitemtype 616, @v_datacode,  @v_datasubcode, 0,@v_itemtype, @v_classcode,@v_error_code OUTPUT, @v_error_desc OUTPUT END	IF @v_error_code <> 0  print 'datacode = ' + CAST(@v_datacode AS varchar)+ ', datasubcode = ' + CAST(@v_datasubcode AS varchar) +', error message =' + @v_error_desc

END  
  
 GO