/*GRANT EXECUTE ON <procedure name> TO PUBLIC*/


GRANT ALL ON DELETETITLE_BOOKELEMENT TO PUBLIC 
go


GRANT EXECUTE ON DELETETITLE_DATAWH  TO PUBLIC 
go


GRANT EXECUTE ON DELETETITLE_DEASSIGN_ONHAND  TO PUBLIC ;


GRANT EXECUTE ON DELETETITLE_DEASSIGN_ONORDER  TO PUBLIC ;


GRANT EXECUTE ON DELETETITLE_DELETE_BOOK  TO PUBLIC ;


GRANT EXECUTE ON DELETETITLE_DELETE_PRINTING  TO PUBLIC ;


GRANT EXECUTE ON DELETETITLE_ESTBOOK  TO PUBLIC ;


GRANT EXECUTE ON DELETETITLE_GPOSECTION  TO PUBLIC ;


GRANT EXECUTE ON DELETETITLE_GPOSUBSECTION  TO PUBLIC ;


GRANT EXECUTE ON DELETETITLE_MATERIALSPECS  TO PUBLIC ;


GRANT EXECUTE ON DELETETITLE_MATREQUEST  TO PUBLIC ;

GRANT EXECUTE ON delete_title_taqprojecttask  TO PUBLIC;

GRANT EXECUTE ON delete_title_taqprojecttitle  TO PUBLIC;

GRANT EXECUTE ON delete_title_associatedprintings  TO PUBLIC;

GRANT EXECUTE ON qproject_delete_project_desktop  TO PUBLIC;


