IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'dw_whtitlepositioning')
BEGIN
  DROP  Procedure  dw_whtitlepositioning
END
GO


 
  CREATE 
    PROCEDURE dbo.dw_whtitlepositioning 
        @ware_bookkey integer,
        @ware_system_date datetime
    AS
      /*
       -- Generated by SQL Server Migration Assistant for Oracle
       --  Please, contact SSMAHELP@microsoft.com or visit http://www.microsoft.com/sql/migration for more information.
       --*/
      BEGIN
          DECLARE 
            @cursor_row$BOOKKEY integer,
            @cursor_row$ASSOCIATIONTYPECODE integer,
            @cursor_row$ASSOCIATIONTYPESUBCODE integer,
            @cursor_row$AUTHORKEY integer,
            @cursor_row$AUTHORNAME varchar(100),
            @cursor_row$ASSOCIATETITLEBOOKKEY integer,
            @cursor_row$ORIGPUBHOUSECODE integer,
            @cursor_row$ISBN varchar(30),
            @cursor_row$TITLE varchar(100),
            @cursor_row$MEDIATYPECODE integer,
            @cursor_row$MEDIATYPESUBCODE integer,
            @cursor_row$PRICE integer,
            @cursor_row$PUBDATE datetime,
            @cursor_row$SALESUNITGROSS integer,
            @cursor_row$SALESUNITNET integer,
            @cursor_row$SORTORDER integer,
            @cursor_row$EDITIONCODE integer,
            @cursor_row$BISACSTATUS integer,
            @cursor_row$LASTUSERID varchar(50),
            @cursor_row$LASTMAINTDATE datetime,
            @cursor_row$REPORTIND integer,
            @ware_count integer,
            @ware_author_count integer,
            @ware_author_displayname varchar(255),
            @ware_bookdetail_count integer,
            @ware_mediatypecode integer,
            @ware_mediatypesubcode integer,
            @ware_mediacode_long varchar(40),
            @ware_mediacode_short varchar(20),
            @ware_formatcode_long varchar(120),
            @ware_formatcode_short varchar(20),
            @ware_titleprefix varchar(100),
            @ware_book_count integer,
            @ware_title varchar(255),
            @ware_titleprefixandtitle varchar(255),
            @prefix varchar(25),
            @ware_publishedinhouseyesno varchar(3),
            @ware_salesunitgross integer,
            @ware_salesunitnet integer,
            @ware_isbn_count integer,
            @ware_isbn varchar(19),
            @ware_bookprice_count integer,
            @ware_price numeric(9, 2),
            @ware_budgetprice numeric(9, 2),
            @ware_bookdates_count integer,
            @ware_pubdate datetime,
            @ware_orglevelkey integer,
            @ware_orgentrykey integer,
            @filterorglevel_count integer,
            @orgentry_count integer,
            @ware_origpubhouse varchar(40),
            @ware_bookorgentry_count integer,
            @ware_editioncode integer,
            @ware_editioncode_long varchar(40),
            @ware_currencycode integer,
            @ware_pricecode integer,
            @ware_bisacstatuscode integer,
            @ware_bisacstatus varchar(40),
            @ware_associationtypedesc varchar(40),
            @ware_lastmaintdate datetime          
          SET @ware_count = 1
          SET @ware_author_count = 0
          SET @ware_author_displayname = ''
          SET @ware_bookdetail_count = 0
          SET @ware_mediatypecode = 0
          SET @ware_mediatypesubcode = 0
          SET @ware_mediacode_long = ''
          SET @ware_mediacode_short = ''
          SET @ware_formatcode_long = ''
          SET @ware_formatcode_short = ''
          SET @ware_titleprefix = ''
          SET @ware_book_count = 0
          SET @ware_title = ''
          SET @ware_titleprefixandtitle = ''
          SET @prefix = ''
          SET @ware_publishedinhouseyesno = ''
          SET @ware_salesunitgross = 0
          SET @ware_salesunitnet = 0
          SET @ware_isbn_count = 0
          SET @ware_isbn = ''
          SET @ware_bookprice_count = 0
          SET @ware_price = 0
          SET @ware_budgetprice = 0
          SET @ware_bookdates_count = 0
          SET @ware_orglevelkey = 0
          SET @ware_orgentrykey = 0
          SET @filterorglevel_count = 0
          SET @orgentry_count = 0
          SET @ware_origpubhouse = ''
          SET @ware_bookorgentry_count = 0
          SET @ware_editioncode = 0
          SET @ware_editioncode_long = ''
          SET @ware_currencycode = 0
          SET @ware_pricecode = 0
          SET @ware_bisacstatuscode = 0
          SET @ware_bisacstatus = ''
          SET @ware_associationtypedesc = ''
          BEGIN
            BEGIN

              DECLARE 
                @cursor_row$BOOKKEY$2 integer,
                @cursor_row$ASSOCIATIONTYPECODE$2 integer,
                @cursor_row$ASSOCIATIONTYPESUBCODE$2 integer,
                @cursor_row$AUTHORKEY$2 integer,
                @cursor_row$AUTHORNAME$2 varchar(8000),
                @cursor_row$ASSOCIATETITLEBOOKKEY$2 integer,
                @cursor_row$ORIGPUBHOUSECODE$2 integer,
                @cursor_row$ISBN$2 varchar(8000),
                @cursor_row$TITLE$2 varchar(8000),
                @cursor_row$MEDIATYPECODE$2 integer,
                @cursor_row$MEDIATYPESUBCODE$2 integer,
                @cursor_row$PRICE$2 integer,
                @cursor_row$PUBDATE$2 datetime,
                @cursor_row$SALESUNITGROSS$2 integer,
                @cursor_row$SALESUNITNET$2 integer,
                @cursor_row$SORTORDER$2 integer,
                @cursor_row$EDITIONCODE$2 integer,
                @cursor_row$BISACSTATUS$2 integer,
                @cursor_row$LASTUSERID$2 varchar(8000),
                @cursor_row$LASTMAINTDATE$2 datetime,
                @cursor_row$REPORTIND$2 integer              

              DECLARE 
                whassociatedtitles CURSOR LOCAL 
                 FOR 
                  SELECT 
                      dbo.ASSOCIATEDTITLES.BOOKKEY, 
                      dbo.ASSOCIATEDTITLES.ASSOCIATIONTYPECODE, 
                      dbo.ASSOCIATEDTITLES.ASSOCIATIONTYPESUBCODE, 
                      isnull(ASSOCIATEDTITLES.AUTHORKEY, 0), 
                      isnull(ASSOCIATEDTITLES.AUTHORNAME, ''),
                      isnull(ASSOCIATEDTITLES.ASSOCIATETITLEBOOKKEY, 0),
                      isnull(ASSOCIATEDTITLES.ORIGPUBHOUSECODE, 0),
                      isnull(ASSOCIATEDTITLES.ISBN , ''),           
                      isnull(ASSOCIATEDTITLES.TITLE  , ''),
                      isnull(ASSOCIATEDTITLES.MEDIATYPECODE, 0),
                      isnull(ASSOCIATEDTITLES.MEDIATYPESUBCODE, 0),
                      isnull(ASSOCIATEDTITLES.PRICE, 0),
                      isnull(ASSOCIATEDTITLES.PUBDATE, NULL),
                      isnull(ASSOCIATEDTITLES.SALESUNITGROSS, 0),
                      isnull(ASSOCIATEDTITLES.SALESUNITNET, 0),
                      isnull(ASSOCIATEDTITLES.SORTORDER, 0), 
                      isnull(ASSOCIATEDTITLES.EDITIONCODE, 0), 
                      isnull(ASSOCIATEDTITLES.BISACSTATUS, 0),
                      dbo.ASSOCIATEDTITLES.LASTUSERID, 
                      dbo.ASSOCIATEDTITLES.LASTMAINTDATE, 
                      dbo.ASSOCIATEDTITLES.REPORTIND
                    FROM dbo.ASSOCIATEDTITLES
                    WHERE (dbo.ASSOCIATEDTITLES.BOOKKEY = @ware_bookkey)
                  ORDER BY dbo.ASSOCIATEDTITLES.BOOKKEY ASC, dbo.ASSOCIATEDTITLES.ASSOCIATIONTYPECODE ASC, sortorder ASC
              

              OPEN whassociatedtitles

              FETCH NEXT FROM whassociatedtitles
                INTO 
                  @cursor_row$BOOKKEY$2, 
                  @cursor_row$ASSOCIATIONTYPECODE$2, 
                  @cursor_row$ASSOCIATIONTYPESUBCODE$2, 
                  @cursor_row$AUTHORKEY$2, 
                  @cursor_row$AUTHORNAME$2, 
                  @cursor_row$ASSOCIATETITLEBOOKKEY$2, 
                  @cursor_row$ORIGPUBHOUSECODE$2, 
                  @cursor_row$ISBN$2, 
                  @cursor_row$TITLE$2, 
                  @cursor_row$MEDIATYPECODE$2, 
                  @cursor_row$MEDIATYPESUBCODE$2, 
                  @cursor_row$PRICE$2, 
                  @cursor_row$PUBDATE$2, 
                  @cursor_row$SALESUNITGROSS$2, 
                  @cursor_row$SALESUNITNET$2, 
                  @cursor_row$SORTORDER$2, 
                  @cursor_row$EDITIONCODE$2, 
                  @cursor_row$BISACSTATUS$2, 
                  @cursor_row$LASTUSERID$2, 
                  @cursor_row$LASTMAINTDATE$2, 
                  @cursor_row$REPORTIND$2


              WHILE  NOT(@@FETCH_STATUS = -1)
                BEGIN

                  IF (@@FETCH_STATUS = -1)
                    BREAK 

                  IF (@cursor_row$ASSOCIATETITLEBOOKKEY$2 > 0)
                    BEGIN

                      /*  in house title */

                      SET @ware_author_count = 0

                      SELECT @ware_author_count = count( * )
                        FROM dbo.CORETITLEINFO
                        WHERE (dbo.CORETITLEINFO.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2)


                      IF ((@@ROWCOUNT > 0) AND 
                              (@ware_author_count > 0))
                        BEGIN
                          SELECT @ware_author_displayname = dbo.CORETITLEINFO.AUTHORNAME
                            FROM dbo.CORETITLEINFO
                            WHERE ((dbo.CORETITLEINFO.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2) AND 
                                    (dbo.CORETITLEINFO.PRINTINGKEY = 1))

                        END
                      ELSE 
                        SET @ware_author_displayname = ''

                      IF (@cursor_row$ASSOCIATIONTYPECODE$2 > 0)
                        BEGIN
                          SET @ware_associationtypedesc = dbo.GENTABLES_LONGDESC_FUNCTION(440, @cursor_row$ASSOCIATIONTYPECODE$2)
                          SET @ware_associationtypedesc = substring(@ware_associationtypedesc, 1, 40)
                        END
                      ELSE 
                        SET @ware_associationtypedesc = ''

                      SET @ware_isbn_count = 0

                      SELECT @ware_isbn_count = count( * )
                        FROM dbo.ISBN
                        WHERE (dbo.ISBN.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2)


                      IF ((@@ROWCOUNT > 0) AND 
                              (@ware_isbn_count > 0))
                        BEGIN
                          SELECT @ware_isbn = isnull(ISBN.ISBN, '')
                            FROM dbo.ISBN
                            WHERE (dbo.ISBN.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2)

                        END
                      ELSE 
                        SET @ware_isbn = ''

                      SET @filterorglevel_count = 0

                      SET @ware_orglevelkey = 0

                      SET @ware_bookorgentry_count = 0

                      SET @ware_orgentrykey = 0

                      SET @orgentry_count = 0

                      SELECT @filterorglevel_count = count( * )
                        FROM dbo.FILTERORGLEVEL
                        WHERE (dbo.FILTERORGLEVEL.FILTERKEY = 23)


                      IF ((@@ROWCOUNT > 0) AND 
                              (@filterorglevel_count > 0))
                        BEGIN

                          SELECT @ware_orglevelkey = isnull(FILTERORGLEVEL.FILTERORGLEVELKEY, 0)
                            FROM dbo.FILTERORGLEVEL
                            WHERE (dbo.FILTERORGLEVEL.FILTERKEY = 23)

                          IF (@ware_orglevelkey > 0)
                            BEGIN

                              SELECT @ware_bookorgentry_count = count( * )
                                FROM dbo.BOOKORGENTRY
                                WHERE ((dbo.BOOKORGENTRY.ORGLEVELKEY = @ware_orglevelkey) AND 
                                        (dbo.BOOKORGENTRY.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2))


                              IF ((@@ROWCOUNT > 0) AND 
                                      (@ware_bookorgentry_count > 0))
                                BEGIN

                                  SELECT @ware_orgentrykey = dbo.BOOKORGENTRY.ORGENTRYKEY
                                    FROM dbo.BOOKORGENTRY
                                    WHERE ((dbo.BOOKORGENTRY.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2) AND 
                                            (dbo.BOOKORGENTRY.ORGLEVELKEY = @ware_orglevelkey))

                                  IF (@ware_orgentrykey > 0)
                                    BEGIN

                                      SELECT @orgentry_count = count( * )
                                        FROM dbo.ORGENTRY
                                        WHERE (dbo.ORGENTRY.ORGENTRYKEY = @ware_orgentrykey)

                                      IF ((@@ROWCOUNT > 0) AND 
                                              (@orgentry_count > 0))
                                        BEGIN
                                          SELECT @ware_origpubhouse = isnull(ORGENTRY.ORGENTRYDESC, '')
                                            FROM dbo.ORGENTRY
                                            WHERE (dbo.ORGENTRY.ORGENTRYKEY = @ware_orgentrykey)

                                        END
                                      ELSE 
                                        SET @ware_origpubhouse = ''

                                    END

                                END
                              ELSE 
                                SET @ware_origpubhouse = ''

                            END

                        END
                      ELSE 
                        SET @ware_origpubhouse = ''

                      SET @ware_bookdetail_count = 0

                      SELECT @ware_bookdetail_count = count( * )
                        FROM dbo.BOOKDETAIL
                        WHERE (dbo.BOOKDETAIL.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2)

                      IF ((@@ROWCOUNT > 0) AND 
                              (@ware_bookdetail_count > 0))
                        BEGIN
                          SELECT 
                              @ware_mediatypecode = dbo.BOOKDETAIL.MEDIATYPECODE, 
                              @ware_mediatypesubcode = dbo.BOOKDETAIL.MEDIATYPESUBCODE, 
                              @ware_titleprefix = isnull(BOOKDETAIL.TITLEPREFIX, ''), 
                              @ware_editioncode = dbo.BOOKDETAIL.EDITIONCODE, 
                              @ware_bisacstatuscode = dbo.BOOKDETAIL.BISACSTATUSCODE
                            FROM dbo.BOOKDETAIL
                            WHERE (dbo.BOOKDETAIL.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2)

                        END
                      ELSE 
                        BEGIN

                          SET @ware_mediatypecode = 0

                          SET @ware_mediatypesubcode = 0

                          SET @ware_titleprefix = ''

                          SET @ware_editioncode = 0

                        END

                      IF (@ware_mediatypecode > 0)
                        BEGIN

                          SET @ware_mediacode_long = dbo.GENTABLES_LONGDESC_FUNCTION(312, @ware_mediatypecode)

                          SET @ware_mediacode_long = substring(@ware_mediacode_long, 1, 40)

                          SET @ware_mediacode_short = dbo.GENTABLES_LONGDESC_FUNCTION(312, @ware_mediatypecode)

                          SET @ware_mediacode_short = substring(@ware_mediacode_short, 1, 8)

                        END
                      ELSE 
                        BEGIN
                          SET @ware_mediacode_long = ''
                          SET @ware_mediacode_short = ''
                        END

                      IF (@ware_mediatypesubcode > 0)
                        BEGIN

                          SET @ware_formatcode_long = dbo.SUBGENT_LONGDESC_FUNCTION(312, @ware_mediatypecode, @ware_mediatypesubcode)

                          SET @ware_formatcode_short = dbo.SUBGENT_SHORTDESC_FUNCTION(312, @ware_mediatypecode, @ware_mediatypesubcode)

                          SET @ware_formatcode_short = substring(@ware_formatcode_short, 1, 8)

                        END
                      ELSE 
                        BEGIN
                          SET @ware_formatcode_long = ''
                          SET @ware_formatcode_short = ''
                        END

                      IF (@ware_editioncode > 0)
                        BEGIN
                          SET @ware_editioncode_long = dbo.GENTABLES_LONGDESC_FUNCTION(200, @ware_editioncode)
                          SET @ware_editioncode_long = substring(@ware_editioncode_long, 1, 40)
                        END
                      ELSE 
                        SET @ware_editioncode_long = ''

                      IF (@ware_bisacstatuscode > 0)
                        BEGIN
                          SET @ware_bisacstatus = dbo.GENTABLES_LONGDESC_FUNCTION(314, @ware_bisacstatuscode)
                          SET @ware_bisacstatus = substring(@ware_bisacstatus, 1, 40)
                        END
                      ELSE 
                        SET @ware_bisacstatus = ''

                      SET @ware_book_count = 0

                      SELECT @ware_book_count = count( * )
                        FROM dbo.BOOK
                        WHERE (dbo.BOOK.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2)

                      IF ((@@ROWCOUNT > 0) AND 
                              (@ware_book_count > 0))
                        BEGIN
                          SELECT @ware_title = isnull(BOOK.TITLE, '')
                            FROM dbo.BOOK
                            WHERE (dbo.BOOK.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2)

                        END
                      ELSE 
                        SET @ware_title = ''

                      SET @prefix = rtrim(ltrim(substring(@ware_titleprefix, 1, 15)))

                      IF (len(@prefix) > 0)
                        SET @ware_titleprefixandtitle = (isnull(@ware_title, '') + ',  ' + isnull(@prefix, ''))
                      ELSE 
                        SET @ware_titleprefixandtitle = @ware_title

                      SET @ware_title = @ware_titleprefixandtitle

                      SET @ware_publishedinhouseyesno = 'yes'

                      SET @ware_count = 0

                      SELECT @ware_count = count( * )
                        FROM dbo.FILTERPRICETYPE
                        WHERE (dbo.FILTERPRICETYPE.FILTERKEY = 5)


                      /*  currency and price types */

                      IF (@ware_count > 0)
                        BEGIN
                          SELECT @ware_pricecode = isnull(FILTERPRICETYPE.PRICETYPECODE, 0), @ware_currencycode = isnull(FILTERPRICETYPE.CURRENCYTYPECODE, 0)
                            FROM dbo.FILTERPRICETYPE
                            WHERE (dbo.FILTERPRICETYPE.FILTERKEY = 5)

                        END

                      SET @ware_bookprice_count = 0

                      SELECT @ware_bookprice_count = count( * )
                        FROM dbo.BOOKPRICE
                        WHERE ((dbo.BOOKPRICE.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2) AND 
                                (dbo.BOOKPRICE.PRICETYPECODE = @ware_pricecode) AND 
                                (dbo.BOOKPRICE.CURRENCYTYPECODE = @ware_currencycode) AND 
                                (dbo.BOOKPRICE.ACTIVEIND = 1))

                      IF ((@@ROWCOUNT > 0) AND 
                              (@ware_bookprice_count > 0))
                        BEGIN
                          SELECT @ware_price = isnull(BOOKPRICE.FINALPRICE, 0), @ware_budgetprice = isnull(BOOKPRICE.BUDGETPRICE, 0)
                            FROM dbo.BOOKPRICE
                            WHERE ((dbo.BOOKPRICE.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2) AND 
                                    (dbo.BOOKPRICE.PRICETYPECODE = @ware_pricecode) AND 
                                    (dbo.BOOKPRICE.CURRENCYTYPECODE = @ware_currencycode) AND 
                                    (dbo.BOOKPRICE.ACTIVEIND = 1))

                        END
                      ELSE 
                        SET @ware_price = 0

                      IF ((@@ROWCOUNT > 0) AND 
                              (@ware_bookprice_count > 0))
                        IF (@ware_price = 0)
                          SET @ware_price = @ware_budgetprice

                      SET @ware_bookdates_count = 0

                      SELECT @ware_bookdates_count = count( * )
                        FROM dbo.BOOKDATES
                        WHERE ((dbo.BOOKDATES.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2) AND 
                                (dbo.BOOKDATES.DATETYPECODE = 8) AND 
                                (dbo.BOOKDATES.PRINTINGKEY = 1))

                      IF ((@@ROWCOUNT > 0) AND 
                              (@ware_bookdates_count > 0))
                        BEGIN
                          SELECT @ware_pubdate = isnull(BOOKDATES.BESTDATE,  NULL)
                            FROM dbo.BOOKDATES
                            WHERE ((dbo.BOOKDATES.BOOKKEY = @cursor_row$ASSOCIATETITLEBOOKKEY$2) AND 
                                    (dbo.BOOKDATES.DATETYPECODE = 8) AND 
                                    (dbo.BOOKDATES.PRINTINGKEY = 1))


                        END

                      SET @ware_salesunitgross = @cursor_row$SALESUNITGROSS$2

                      SET @ware_salesunitnet = @cursor_row$SALESUNITNET$2

                      INSERT INTO dbo.WHTITLEPOSITIONING
                        (
                          dbo.WHTITLEPOSITIONING.BOOKKEY, 
                          dbo.WHTITLEPOSITIONING.ASSOCIATIONTYPECODE, 
                          dbo.WHTITLEPOSITIONING.ASSOCIATIONTYPESUBCODE, 
                          dbo.WHTITLEPOSITIONING.ASSOCIATIONTYPEDESC, 
                          dbo.WHTITLEPOSITIONING.ASSOCIATETITLEBOOKKEY, 
                          dbo.WHTITLEPOSITIONING.SORTORDER, 
                          dbo.WHTITLEPOSITIONING.ISBN, 
                          dbo.WHTITLEPOSITIONING.TITLE, 
                          dbo.WHTITLEPOSITIONING.AUTHORKEY, 
                          dbo.WHTITLEPOSITIONING.AUTHORNAME, 
                          dbo.WHTITLEPOSITIONING.BISACSTATUS, 
                          dbo.WHTITLEPOSITIONING.BISACSTATUSDESC, 
                          dbo.WHTITLEPOSITIONING.ORIGPUBHOUSECODE, 
                          dbo.WHTITLEPOSITIONING.ORIGINALPUBHOUSE, 
                          dbo.WHTITLEPOSITIONING.MEDIATYPECODE, 
                          dbo.WHTITLEPOSITIONING.MEDIA, 
                          dbo.WHTITLEPOSITIONING.MEDIASHORT, 
                          dbo.WHTITLEPOSITIONING.MEDIATYPESUBCODE, 
                          dbo.WHTITLEPOSITIONING.FORMAT, 
                          dbo.WHTITLEPOSITIONING.FORMATSHORT, 
                          dbo.WHTITLEPOSITIONING.PRICE, 
                          dbo.WHTITLEPOSITIONING.PUBDATE, 
                          dbo.WHTITLEPOSITIONING.SALESUNITGROSS, 
                          dbo.WHTITLEPOSITIONING.SALESUNITNET, 
                          dbo.WHTITLEPOSITIONING.REPORTIND, 
                          dbo.WHTITLEPOSITIONING.PUBLISHEDINHOUSE, 
                          dbo.WHTITLEPOSITIONING.EDITIONCODE, 
                          dbo.WHTITLEPOSITIONING.EDITION, 
                          dbo.WHTITLEPOSITIONING.LASTUSERID, 
                          dbo.WHTITLEPOSITIONING.LASTMAINTDATE
                        )
                        VALUES 
                          (
                            @cursor_row$BOOKKEY$2, 
                            @cursor_row$ASSOCIATIONTYPECODE$2, 
                            @cursor_row$ASSOCIATIONTYPESUBCODE$2, 
                            @ware_associationtypedesc, 
                            @cursor_row$ASSOCIATETITLEBOOKKEY$2, 
                            @cursor_row$SORTORDER$2, 
                            @ware_isbn, 
                            substring(@ware_title, 1, 80), 
                            @cursor_row$AUTHORKEY$2, 
                            @ware_author_displayname, 
                            @ware_bisacstatuscode, 
                            @ware_bisacstatus, 
                            @cursor_row$ORIGPUBHOUSECODE$2, 
                            @ware_origpubhouse, 
                            @ware_mediatypecode, 
                            @ware_mediacode_long, 
                            @ware_mediacode_short, 
                            @ware_mediatypesubcode, 
                            @ware_formatcode_long, 
                            @ware_formatcode_short, 
                            @ware_price, 
                            @ware_pubdate, 
                            @ware_salesunitgross, 
                            @ware_salesunitnet, 
                            @cursor_row$REPORTIND$2, 
                            @ware_publishedinhouseyesno, 
                            @ware_editioncode, 
                            @ware_editioncode_long, 
                            'WARE_STORED_PROC', 
                            @ware_system_date
                          )

                      IF (@@TRANCOUNT > 0)
                          COMMIT WORK

                    END
                  ELSE 
                    BEGIN

                      /*  out of house title  */

                      SET @ware_author_displayname = @cursor_row$AUTHORNAME$2

                      IF (@cursor_row$ASSOCIATIONTYPECODE$2 > 0)
                        BEGIN
                          SET @ware_associationtypedesc = dbo.GENTABLES_LONGDESC_FUNCTION(440, @cursor_row$ASSOCIATIONTYPECODE$2)
                          SET @ware_associationtypedesc = substring(@ware_associationtypedesc, 1, 40)
                        END
                      ELSE 
                        SET @ware_associationtypedesc = ''

                      IF (@cursor_row$ORIGPUBHOUSECODE$2 > 0)
                        SET @ware_origpubhouse = dbo.GENTABLES_LONGDESC_FUNCTION(126, @cursor_row$ORIGPUBHOUSECODE$2)
                      ELSE 
                        SET @ware_origpubhouse = ''

                      SET @ware_isbn = @cursor_row$ISBN$2

                      IF (@cursor_row$MEDIATYPECODE$2 > 0)
                        BEGIN

                          SET @ware_mediacode_long = dbo.GENTABLES_LONGDESC_FUNCTION(312, @cursor_row$MEDIATYPECODE$2)

                          SET @ware_mediacode_long = substring(@ware_mediacode_long, 1, 40)

                          SET @ware_mediacode_short = dbo.GENTABLES_LONGDESC_FUNCTION(312, @cursor_row$MEDIATYPECODE$2)

                          SET @ware_mediacode_short = substring(@ware_mediacode_short, 1, 8)

                        END
                      ELSE 
                        BEGIN
                          SET @ware_mediacode_long = ''
                          SET @ware_mediacode_short = ''
                        END

                      IF (@cursor_row$MEDIATYPESUBCODE$2 > 0)
                        BEGIN

                          SET @ware_formatcode_long = dbo.SUBGENT_LONGDESC_FUNCTION(312, @cursor_row$MEDIATYPECODE$2, @cursor_row$MEDIATYPESUBCODE$2)

                          SET @ware_formatcode_short = dbo.SUBGENT_SHORTDESC_FUNCTION(312, @cursor_row$MEDIATYPECODE$2, @cursor_row$MEDIATYPESUBCODE$2)

                          SET @ware_formatcode_short = substring(@ware_formatcode_short, 1, 8)

                        END
                      ELSE 
                        BEGIN
                          SET @ware_formatcode_long = ''
                          SET @ware_formatcode_short = ''
                        END

                      IF (@cursor_row$EDITIONCODE$2 > 0)
                        BEGIN
                          SET @ware_editioncode_long = dbo.GENTABLES_LONGDESC_FUNCTION(200, @cursor_row$EDITIONCODE$2)
                          SET @ware_editioncode_long = substring(@ware_editioncode_long, 1, 40)
                        END
                      ELSE 
                        SET @ware_editioncode_long = ''

                      IF (@cursor_row$BISACSTATUS$2 > 0)
                        BEGIN
                          SET @ware_bisacstatus = dbo.GENTABLES_LONGDESC_FUNCTION(314, @cursor_row$BISACSTATUS$2)
                          SET @ware_bisacstatus = substring(@ware_bisacstatus, 1, 40)
                        END
                      ELSE 
                        SET @ware_bisacstatus = ''

                      SET @ware_title = @cursor_row$TITLE$2

                      SET @ware_price = @cursor_row$PRICE$2

                      SET @ware_pubdate = @cursor_row$PUBDATE$2

                      SET @ware_publishedinhouseyesno = 'no'

                      SET @ware_salesunitgross = @cursor_row$SALESUNITGROSS$2

                      SET @ware_salesunitnet = @cursor_row$SALESUNITNET$2

                      INSERT INTO dbo.WHTITLEPOSITIONING
                        (
                          dbo.WHTITLEPOSITIONING.BOOKKEY, 
                          dbo.WHTITLEPOSITIONING.ASSOCIATIONTYPECODE, 
                          dbo.WHTITLEPOSITIONING.ASSOCIATIONTYPESUBCODE, 
                          dbo.WHTITLEPOSITIONING.ASSOCIATIONTYPEDESC, 
                          dbo.WHTITLEPOSITIONING.ASSOCIATETITLEBOOKKEY, 
                          dbo.WHTITLEPOSITIONING.SORTORDER, 
                          dbo.WHTITLEPOSITIONING.ISBN, 
                          dbo.WHTITLEPOSITIONING.TITLE, 
                          dbo.WHTITLEPOSITIONING.AUTHORKEY, 
                          dbo.WHTITLEPOSITIONING.AUTHORNAME, 
                          dbo.WHTITLEPOSITIONING.BISACSTATUS, 
                          dbo.WHTITLEPOSITIONING.BISACSTATUSDESC, 
                          dbo.WHTITLEPOSITIONING.ORIGPUBHOUSECODE, 
                          dbo.WHTITLEPOSITIONING.ORIGINALPUBHOUSE, 
                          dbo.WHTITLEPOSITIONING.MEDIATYPECODE, 
                          dbo.WHTITLEPOSITIONING.MEDIA, 
                          dbo.WHTITLEPOSITIONING.MEDIASHORT, 
                          dbo.WHTITLEPOSITIONING.MEDIATYPESUBCODE, 
                          dbo.WHTITLEPOSITIONING.FORMAT, 
                          dbo.WHTITLEPOSITIONING.FORMATSHORT, 
                          dbo.WHTITLEPOSITIONING.PRICE, 
                          dbo.WHTITLEPOSITIONING.PUBDATE, 
                          dbo.WHTITLEPOSITIONING.SALESUNITGROSS, 
                          dbo.WHTITLEPOSITIONING.SALESUNITNET, 
                          dbo.WHTITLEPOSITIONING.REPORTIND, 
                          dbo.WHTITLEPOSITIONING.PUBLISHEDINHOUSE, 
                          dbo.WHTITLEPOSITIONING.EDITIONCODE, 
                          dbo.WHTITLEPOSITIONING.EDITION, 
                          dbo.WHTITLEPOSITIONING.LASTUSERID, 
                          dbo.WHTITLEPOSITIONING.LASTMAINTDATE
                        )
                        VALUES 
                          (
                            @cursor_row$BOOKKEY$2, 
                            @cursor_row$ASSOCIATIONTYPECODE$2, 
                            @cursor_row$ASSOCIATIONTYPESUBCODE$2, 
                            @ware_associationtypedesc, 
                            @cursor_row$ASSOCIATETITLEBOOKKEY$2, 
                            @cursor_row$SORTORDER$2, 
                            @ware_isbn, 
                            substring(@ware_title, 1, 80), 
                            @cursor_row$AUTHORKEY$2, 
                            @ware_author_displayname, 
                            @cursor_row$BISACSTATUS$2, 
                            @ware_bisacstatus, 
                            @cursor_row$ORIGPUBHOUSECODE$2, 
                            @ware_origpubhouse, 
                            @cursor_row$MEDIATYPECODE$2, 
                            @ware_mediacode_long, 
                            @ware_mediacode_short, 
                            @cursor_row$MEDIATYPESUBCODE$2, 
                            @ware_formatcode_long, 
                            @ware_formatcode_short, 
                            @cursor_row$PRICE$2, 
                            @cursor_row$PUBDATE$2, 
                            @cursor_row$SALESUNITGROSS$2, 
                            @cursor_row$SALESUNITNET$2, 
                            @cursor_row$REPORTIND$2, 
                            @ware_publishedinhouseyesno, 
                            @cursor_row$EDITIONCODE$2, 
                            @ware_editioncode_long, 
                            'WARE_STORED_PROC', 
                            @ware_system_date
                          )

                      IF (@@TRANCOUNT > 0)
                          COMMIT WORK

                    END

                  FETCH NEXT FROM whassociatedtitles
                    INTO 
                      @cursor_row$BOOKKEY$2, 
                      @cursor_row$ASSOCIATIONTYPECODE$2, 
                      @cursor_row$ASSOCIATIONTYPESUBCODE$2, 
                      @cursor_row$AUTHORKEY$2, 
                      @cursor_row$AUTHORNAME$2, 
                      @cursor_row$ASSOCIATETITLEBOOKKEY$2, 
                      @cursor_row$ORIGPUBHOUSECODE$2, 
                      @cursor_row$ISBN$2, 
                      @cursor_row$TITLE$2, 
                      @cursor_row$MEDIATYPECODE$2, 
                      @cursor_row$MEDIATYPESUBCODE$2, 
                      @cursor_row$PRICE$2, 
                      @cursor_row$PUBDATE$2, 
                      @cursor_row$SALESUNITGROSS$2, 
                      @cursor_row$SALESUNITNET$2, 
                      @cursor_row$SORTORDER$2, 
                      @cursor_row$EDITIONCODE$2, 
                      @cursor_row$BISACSTATUS$2, 
                      @cursor_row$LASTUSERID$2, 
                      @cursor_row$LASTMAINTDATE$2, 
                      @cursor_row$REPORTIND$2

                END

              CLOSE whassociatedtitles

              DEALLOCATE whassociatedtitles

            END
            IF (cursor_status(N'local', N'whassociatedtitles') = 1)
              BEGIN
                CLOSE whassociatedtitles
                DEALLOCATE whassociatedtitles
              END
          END
      END
go
grant execute on dw_whtitlepositioning  to public
go







