IF EXISTS (SELECT * FROM sysobjects WHERE type = 'P' AND name = 'datawarehouse_base_incr')
BEGIN
  DROP  Procedure  datawarehouse_base_incr
END
GO
  CREATE 
    PROCEDURE dbo.datawarehouse_base_incr 
        @i_titleonly integer
    AS
      /*
       -- Generated by SQL Server Migration Assistant for Oracle
       --  Please, contact SSMAHELP@microsoft.com or visit http://www.microsoft.com/sql/migration for more information.
       --*/
      BEGIN
          DECLARE 
            @cursor_row$BOOKKEY integer,
            @cursor_row$BOOKKEY1 integer,
            @cursor_row$BOOKKEY$2 integer,
            @cursor_row$PRINTINGKEY integer,
            @err_msg varchar(200),
            @ware_count integer,
            @ware_count2 integer,
            @ware_total integer,
            @ware_warehousekey integer,
            @ware_newhousekey integer,
            @ware_activeind numeric(3, 0),
            @ware_logkey integer,
            @ware_illuspapchgcode integer,
            @ware_textpapchgcode integer,
            @ware_lastbookkey integer,
            @ware_system_date datetime,
            @ware_company varchar(20),
            @ware_lasttypeofbuild varchar(30),
            @ware_laststarttime datetime,
            @ware_lastendtime datetime,
            @ware_lastrowsprocessed integer,
            @ware_lasttotalrows integer,
            @ware_associationtypecode integer,
            @ware_associatedtitles_count integer          
          SET @ware_count = 0
          SET @ware_count2 = 0
          SET @ware_total = 0
          SET @ware_warehousekey = 0
          SET @ware_newhousekey = 0
          SET @ware_activeind = 0
          SET @ware_logkey = 0
          SET @ware_illuspapchgcode = 0
          SET @ware_textpapchgcode = 0
          SET @ware_lastbookkey = 0
          SET @ware_company = ''
          SET @ware_lasttypeofbuild = ''
          SET @ware_lastrowsprocessed = 0
          SET @ware_lasttotalrows = 0
          SET @ware_associationtypecode = 0
          SET @ware_associatedtitles_count = 0



           /*
             -- PM 071805 cannot figure out why Salesfeed rows are getting populated in estwhupdate so I'm running the statment here
             -- on the incremental so I'm sure it will get executed
             --*/

            /* delete from estwhupdate where lastuserid = 'SALESFEED'; */

            /* 07-22-2005 WNB remove non bookkeys from whbookupdate prior to run */

            DELETE FROM dbo.BOOKWHUPDATE
              WHERE (dbo.BOOKWHUPDATE.BOOKKEY NOT IN
                          ( 
                            SELECT dbo.BOOK.BOOKKEY
                              FROM dbo.BOOK
                          ))

            SELECT @ware_warehousekey = max(dbo.WHHISTORYINFO.WAREHOUSEKEY)
              FROM dbo.WHHISTORYINFO
	   	

            IF ((@@ROWCOUNT > 0) AND 
                    (@ware_warehousekey > 0))
              BEGIN

                SELECT @ware_activeind = isnull(dbo.WHHISTORYINFO.ACTIVERUNIND, 0)
                  FROM dbo.WHHISTORYINFO
                  WHERE (dbo.WHHISTORYINFO.WAREHOUSEKEY = @ware_warehousekey)


                IF (@ware_activeind = 1)
                  BEGIN

                    SET @ware_count2 = 0

                    SELECT @ware_count2 = count( * )
                      FROM dbo.WHERRORLOG
                      WHERE (dbo.WHERRORLOG.WAREHOUSEKEY = @ware_warehousekey)


                    IF ((@@ROWCOUNT > 0) AND 
                            (@ware_count2 > 0))
                      BEGIN

                        SELECT DISTINCT @ware_logkey = isnull(dbo.WHERRORLOG.LOGKEY, 0)
                          FROM dbo.WHERRORLOG
                          WHERE (dbo.WHERRORLOG.WAREHOUSEKEY = @ware_warehousekey)

                        IF (@@ROWCOUNT > 0)
                          BEGIN
                            INSERT INTO dbo.WHERRORLOG
                              (
                                dbo.WHERRORLOG.LOGKEY, 
                                dbo.WHERRORLOG.WAREHOUSEKEY, 
                                dbo.WHERRORLOG.ERRORDESC, 
                                dbo.WHERRORLOG.ERRORSEVERITY, 
                                dbo.WHERRORLOG.ERRORFUNCTION, 
                                dbo.WHERRORLOG.LASTUSERID, 
                                dbo.WHERRORLOG.LASTMAINTDATE
                              )
                              VALUES 
                                (
                                  @ware_logkey, 
                                  @ware_warehousekey, 
                                  'Status indicates that a Warehouse build already in progress; EXIT INCREMENTAL', 
                                  'Warning/data error', 
                                  'Stored procedure startup', 
                                  'WARE_STORED_PROC', 
                                  getdate()
                                )
                          END
                        ELSE 
                          BEGIN

                            SELECT @ware_logkey = max(dbo.WHERRORLOG.LOGKEY)
                              FROM dbo.WHERRORLOG

                            IF (@@ROWCOUNT = 0)
                              SET @ware_logkey = 1

                            INSERT INTO dbo.WHERRORLOG
                              (
                                dbo.WHERRORLOG.LOGKEY, 
                                dbo.WHERRORLOG.WAREHOUSEKEY, 
                                dbo.WHERRORLOG.ERRORDESC, 
                                dbo.WHERRORLOG.ERRORSEVERITY, 
                                dbo.WHERRORLOG.ERRORFUNCTION, 
                                dbo.WHERRORLOG.LASTUSERID, 
                                dbo.WHERRORLOG.LASTMAINTDATE
                              )
                              VALUES 
                                (
                                  @ware_logkey, 
                                  @ware_warehousekey, 
                                  'Status indicates that a Warehouse build already in progress; EXIT INCREMENTAL', 
                                  'Warning/data error', 
                                  'Stored procedure startup', 
                                  'WARE_STORED_PROC', 
                                  getdate()
                                )
                          END

                      END

                  END

              END

            BEGIN

              DECLARE 
                @cursor_row$BOOKKEY$3 integer,
                @cursor_row$PRINTINGKEY$2 integer              

              DECLARE 
                datawarehouse_base2 CURSOR LOCAL 
                 FOR 
                  SELECT dbo.TITLEDELETEAUDIT.BOOKKEY, dbo.TITLEDELETEAUDIT.PRINTINGKEY
                    FROM dbo.TITLEDELETEAUDIT
                    WHERE (dbo.TITLEDELETEAUDIT.DATAWAREHOUSEDELETED = 'N')
                  ORDER BY dbo.TITLEDELETEAUDIT.BOOKKEY DESC
              

              OPEN datawarehouse_base2

              FETCH NEXT FROM datawarehouse_base2
                INTO @cursor_row$BOOKKEY$3, @cursor_row$PRINTINGKEY$2

              WHILE  NOT(@@FETCH_STATUS = -1)
                BEGIN

                  IF (@ware_activeind = 1)
                    BREAK 

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLEINFO
                    WHERE (dbo.WHTITLEINFO.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLEINFO
                      WHERE (dbo.WHTITLEINFO.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHAUTHOR
                    WHERE (dbo.WHAUTHOR.BOOKKEY = @cursor_row$BOOKKEY$3)



                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHAUTHOR
                      WHERE (dbo.WHAUTHOR.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLECLASS
                    WHERE (dbo.WHTITLECLASS.BOOKKEY = @cursor_row$BOOKKEY$3)

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLECLASS
                      WHERE (dbo.WHTITLECLASS.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLEDATES
                    WHERE (dbo.WHTITLEDATES.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLEDATES
                      WHERE (dbo.WHTITLEDATES.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLEFILES
                    WHERE (dbo.WHTITLEFILES.BOOKKEY = @cursor_row$BOOKKEY$3)



                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLEFILES
                      WHERE (dbo.WHTITLEFILES.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLECOMMENTS
                    WHERE (dbo.WHTITLECOMMENTS.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLECOMMENTS
                      WHERE (dbo.WHTITLECOMMENTS.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLECOMMENTS2
                    WHERE (dbo.WHTITLECOMMENTS2.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLECOMMENTS2
                      WHERE (dbo.WHTITLECOMMENTS2.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLECOMMENTS3
                    WHERE (dbo.WHTITLECOMMENTS3.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLECOMMENTS3
                      WHERE (dbo.WHTITLECOMMENTS3.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLEPERSONNEL
                    WHERE (dbo.WHTITLEPERSONNEL.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLEPERSONNEL
                      WHERE (dbo.WHTITLEPERSONNEL.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLEPREVWORKS
                    WHERE (dbo.WHTITLEPREVWORKS.BOOKKEY = @cursor_row$BOOKKEY$3)

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLEPREVWORKS
                      WHERE (dbo.WHTITLEPREVWORKS.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLECUSTOM
                    WHERE (dbo.WHTITLECUSTOM.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLECUSTOM
                      WHERE (dbo.WHTITLECUSTOM.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHPRINTING
                    WHERE ((dbo.WHPRINTING.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHPRINTING.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHPRINTING
                      WHERE ((dbo.WHPRINTING.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHPRINTING.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHPRINTINGKEYDATES
                    WHERE ((dbo.WHPRINTINGKEYDATES.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHPRINTINGKEYDATES.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHPRINTINGKEYDATES
                      WHERE ((dbo.WHPRINTINGKEYDATES.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHPRINTINGKEYDATES.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  /*  not  implemented on PSS5 as yet */

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHPRINTINGKEYDATES2
                    WHERE ((dbo.WHPRINTINGKEYDATES2.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHPRINTINGKEYDATES2.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHPRINTINGKEYDATES2
                      WHERE ((dbo.WHPRINTINGKEYDATES2.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHPRINTINGKEYDATES2.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHFINALCOSTEST
                    WHERE ((dbo.WHFINALCOSTEST.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHFINALCOSTEST.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHFINALCOSTEST
                      WHERE ((dbo.WHFINALCOSTEST.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHFINALCOSTEST.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE1
                    WHERE ((dbo.WHSCHEDULE1.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE1.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE1
                      WHERE ((dbo.WHSCHEDULE1.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE1.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE2
                    WHERE ((dbo.WHSCHEDULE2.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE2.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE2
                      WHERE ((dbo.WHSCHEDULE2.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE2.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE3
                    WHERE ((dbo.WHSCHEDULE3.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE3.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE3
                      WHERE ((dbo.WHSCHEDULE3.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE3.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE4
                    WHERE ((dbo.WHSCHEDULE4.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE4.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE4
                      WHERE ((dbo.WHSCHEDULE4.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE4.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE5
                    WHERE ((dbo.WHSCHEDULE5.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE5.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE5
                      WHERE ((dbo.WHSCHEDULE5.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE5.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE6
                    WHERE ((dbo.WHSCHEDULE6.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE6.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE6
                      WHERE ((dbo.WHSCHEDULE6.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE6.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE7
                    WHERE ((dbo.WHSCHEDULE7.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE7.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE7
                      WHERE ((dbo.WHSCHEDULE7.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE7.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE8
                    WHERE ((dbo.WHSCHEDULE8.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE8.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE8
                      WHERE ((dbo.WHSCHEDULE8.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE8.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE9
                    WHERE ((dbo.WHSCHEDULE9.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE9.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE9
                      WHERE ((dbo.WHSCHEDULE9.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE9.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE10
                    WHERE ((dbo.WHSCHEDULE10.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE10.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE10
                      WHERE ((dbo.WHSCHEDULE10.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE10.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE11
                    WHERE ((dbo.WHSCHEDULE11.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE11.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE11
                      WHERE ((dbo.WHSCHEDULE11.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE11.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE12
                    WHERE ((dbo.WHSCHEDULE12.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE12.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE12
                      WHERE ((dbo.WHSCHEDULE12.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE12.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE13
                    WHERE ((dbo.WHSCHEDULE13.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE13.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE13
                      WHERE ((dbo.WHSCHEDULE13.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE13.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE14
                    WHERE ((dbo.WHSCHEDULE14.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE14.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE14
                      WHERE ((dbo.WHSCHEDULE14.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE14.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE15
                    WHERE ((dbo.WHSCHEDULE15.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE15.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))



                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE15
                      WHERE ((dbo.WHSCHEDULE15.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE15.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE16
                    WHERE ((dbo.WHSCHEDULE16.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE16.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE16
                      WHERE ((dbo.WHSCHEDULE16.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE16.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE17
                    WHERE ((dbo.WHSCHEDULE17.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE17.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE17
                      WHERE ((dbo.WHSCHEDULE17.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE17.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE18
                    WHERE ((dbo.WHSCHEDULE18.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE18.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE18
                      WHERE ((dbo.WHSCHEDULE18.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE18.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE19
                    WHERE ((dbo.WHSCHEDULE19.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE19.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE19
                      WHERE ((dbo.WHSCHEDULE19.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE19.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE20
                    WHERE ((dbo.WHSCHEDULE20.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE20.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE20
                      WHERE ((dbo.WHSCHEDULE20.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE20.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE21
                    WHERE ((dbo.WHSCHEDULE21.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE21.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE21
                      WHERE ((dbo.WHSCHEDULE21.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE21.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHSCHEDULE22
                    WHERE ((dbo.WHSCHEDULE22.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHSCHEDULE22.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHSCHEDULE22
                      WHERE ((dbo.WHSCHEDULE22.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHSCHEDULE22.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHPRINTINGKEYDATES
                    WHERE ((dbo.WHPRINTINGKEYDATES.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.WHPRINTINGKEYDATES.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHPRINTINGKEYDATES
                      WHERE ((dbo.WHPRINTINGKEYDATES.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                              (dbo.WHPRINTINGKEYDATES.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  /*  1-29-03 added whauthorsalestrack, whcompetitivetitles, whcomparativetitles  */

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHAUTHORSALESTRACK
                    WHERE (dbo.WHAUTHORSALESTRACK.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHAUTHORSALESTRACK
                      WHERE (dbo.WHAUTHORSALESTRACK.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHCOMPETITIVETITLES
                    WHERE (dbo.WHCOMPETITIVETITLES.BOOKKEY = @cursor_row$BOOKKEY$3)

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHCOMPETITIVETITLES
                      WHERE (dbo.WHCOMPETITIVETITLES.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHCOMPARATIVETITLES
                    WHERE (dbo.WHCOMPARATIVETITLES.BOOKKEY = @cursor_row$BOOKKEY$3)

                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHCOMPARATIVETITLES
                      WHERE (dbo.WHCOMPARATIVETITLES.BOOKKEY = @cursor_row$BOOKKEY$3)

                  SET @ware_count2 = 0

                  SELECT @ware_count2 = count( * )
                    FROM dbo.WHTITLEPOSITIONING
                    WHERE (dbo.WHTITLEPOSITIONING.BOOKKEY = @cursor_row$BOOKKEY$3)


                  IF ((@@ROWCOUNT > 0) AND 
                          (@ware_count2 > 0))
                    DELETE FROM dbo.WHTITLEPOSITIONING
                      WHERE (dbo.WHTITLEPOSITIONING.BOOKKEY = @cursor_row$BOOKKEY$3)

                  /* 5-7-02  update datawarehousedeleted indicator to Y */

                  UPDATE dbo.TITLEDELETEAUDIT
                    SET dbo.TITLEDELETEAUDIT.DATAWAREHOUSEDELETED = 'Y'
                    WHERE ((dbo.TITLEDELETEAUDIT.BOOKKEY = @cursor_row$BOOKKEY$3) AND 
                            (dbo.TITLEDELETEAUDIT.PRINTINGKEY = @cursor_row$PRINTINGKEY$2))

                  FETCH NEXT FROM datawarehouse_base2
                    INTO @cursor_row$BOOKKEY$3, @cursor_row$PRINTINGKEY$2

                END

              CLOSE datawarehouse_base2

              DEALLOCATE datawarehouse_base2

            END

            SELECT @ware_system_date = getdate()


            IF (@ware_activeind = 0)
              BEGIN

                /*  delete all errors older than 1 week */

                DELETE FROM dbo.WHERRORLOG
                  WHERE (dbo.WHERRORLOG.LASTMAINTDATE <= (getdate() - 7))

                SELECT @ware_logkey = count( * )
                  FROM dbo.WHERRORLOG



                IF (@ware_logkey > 0)
                  BEGIN

                    SELECT @ware_logkey = max(dbo.WHERRORLOG.LOGKEY)
                      FROM dbo.WHERRORLOG

                    SET @ware_logkey = (@ware_logkey + 1)

                  END
                ELSE 
                  SET @ware_logkey = 1

                SELECT @ware_warehousekey = IsNUll(max(dbo.WHHISTORYINFO.WAREHOUSEKEY), 1)
                  FROM dbo.WHHISTORYINFO


                IF (@@ROWCOUNT = 0)
                  BEGIN

                    SET @ware_warehousekey = @ware_warehousekey + 1

                    INSERT INTO dbo.WHERRORLOG
                      (
                        dbo.WHERRORLOG.LOGKEY, 
                        dbo.WHERRORLOG.WAREHOUSEKEY, 
                        dbo.WHERRORLOG.ERRORDESC, 
                        dbo.WHERRORLOG.ERRORSEVERITY, 
                        dbo.WHERRORLOG.ERRORFUNCTION, 
                        dbo.WHERRORLOG.LASTUSERID, 
                        dbo.WHERRORLOG.LASTMAINTDATE
                      )
                      VALUES 
                        (
                          @ware_logkey, 
                          @ware_newhousekey, 
                          'Unable to access whhistoryinfo- select max(warehousekey)', 
                          'Warning/data error', 
                          'Stored procedure startup', 
                          'WARE_STORED_PROC', 
                          @ware_system_date
                        )

                  END
                ELSE 
                  BEGIN
                    SET @ware_newhousekey = @ware_warehousekey + 1


                    SET @ware_logkey = (@ware_logkey + 1)

                    SELECT @ware_activeind = COUNT( * )
                      FROM dbo.WHHISTORYINFO
                      WHERE (dbo.WHHISTORYINFO.WAREHOUSEKEY = @ware_warehousekey)

                    IF (@ware_activeind > 0)
                      BEGIN

                        SET @ware_activeind = 0

                        SELECT @ware_activeind = isnull(dbo.WHHISTORYINFO.ACTIVERUNIND, 0)
                          FROM dbo.WHHISTORYINFO
                          WHERE (dbo.WHHISTORYINFO.WAREHOUSEKEY = @ware_warehousekey)


                        IF (@@ROWCOUNT = 0)
                          BEGIN
                            INSERT INTO dbo.WHERRORLOG
                              (
                                dbo.WHERRORLOG.LOGKEY, 
                                dbo.WHERRORLOG.WAREHOUSEKEY, 
                                dbo.WHERRORLOG.ERRORDESC, 
                                dbo.WHERRORLOG.ERRORSEVERITY, 
                                dbo.WHERRORLOG.ERRORFUNCTION, 
                                dbo.WHERRORLOG.LASTUSERID, 
                                dbo.WHERRORLOG.LASTMAINTDATE
                              )
                              VALUES 
                                (
                                  @ware_logkey, 
                                  @ware_newhousekey, 
                                  'Unable to access whhistoryinfo - select max(warehousekey)', 
                                  'Warning/data error', 
                                  'Stored procedure startup', 
                                  'WARE_STORED_PROC', 
                                  @ware_system_date
                                )

                          END

                        IF ((@ware_activeind = 0) AND 
                                (@@ROWCOUNT > 0))
                          BEGIN

                            /*  insert row into whhistoryinfo for this build */

                            INSERT INTO dbo.WHHISTORYINFO
                              (
                                dbo.WHHISTORYINFO.WAREHOUSEKEY, 
                                dbo.WHHISTORYINFO.STARTTIME, 
                                dbo.WHHISTORYINFO.ENDTIME, 
                                dbo.WHHISTORYINFO.TYPEOFBUILD, 
                                dbo.WHHISTORYINFO.ACTIVERUNIND
                              )
                              VALUES 
                                (
                                  @ware_newhousekey, 
                                  getdate(), 
                                   NULL, 
                                  'INCREMENTAL', 
                                  1
                                )
                          END
                      END
                  END

                SELECT @ware_total = count( * )
                  FROM dbo.BOOKWHUPDATE

                SELECT @ware_count = count( * )
                  FROM dbo.DEFAULTS


                IF (@ware_count <> 1)
                  BEGIN
                    INSERT INTO dbo.WHERRORLOG
                      (
                        dbo.WHERRORLOG.LOGKEY, 
                        dbo.WHERRORLOG.WAREHOUSEKEY, 
                        dbo.WHERRORLOG.ERRORDESC, 
                        dbo.WHERRORLOG.ERRORSEVERITY, 
                        dbo.WHERRORLOG.ERRORFUNCTION, 
                        dbo.WHERRORLOG.LASTUSERID, 
                        dbo.WHERRORLOG.LASTMAINTDATE
                      )
                      VALUES 
                        (
                          @ware_logkey, 
                          @ware_newhousekey, 
                          'Unable to access defaults table', 
                          'Warning/data error', 
                          'Stored procedure startup', 
                          'WARE_STORED_PROC', 
                          @ware_system_date
                        )
                  END
                ELSE 
                  BEGIN

                    SELECT @ware_illuspapchgcode = dbo.DEFAULTS.TEXTPAPERCHGCODE, @ware_textpapchgcode = dbo.DEFAULTS.ILLUSPAPERCHGCODE
                      FROM dbo.DEFAULTS

                    SET @ware_count = 0

                    IF (@i_titleonly <> 1)
                      BEGIN
                        INSERT INTO dbo.BOOKWHUPDATE
                          (dbo.BOOKWHUPDATE.BOOKKEY, dbo.BOOKWHUPDATE.LASTUSERID, dbo.BOOKWHUPDATE.LASTMAINTDATE)
                          SELECT DISTINCT bu.BOOKKEY, 'qsidba', getdate()
                            FROM dbo.BOOK bu, dbo.BOOKAUTHOR b, dbo.AUTHORPREVIOUSWORKS a
                            WHERE ((b.BOOKKEY = bu.BOOKKEY) AND 
                                    (b.AUTHORKEY = a.AUTHORKEY) AND 
                                    (a.LASTMAINTDATE > (getdate() - 1)) AND 
                                    (bu.STANDARDIND <> 'Y') AND 
                                    (b.BOOKKEY NOT IN
                                        ( 
                                          SELECT bl.BOOKKEY
                                            FROM dbo.BOOKLOCK bl
                                        )) AND 
                                    (b.BOOKKEY NOT IN
                                        ( 
                                          SELECT bl2.BOOKKEY
                                            FROM dbo.BOOKWHUPDATE bl2
                                        )))
                      END

                    BEGIN

                      DECLARE 
                        @cursor_row$BOOKKEY$4 integer,
                        @cursor_row$BOOKKEY1$2 integer                      

                      DECLARE 
                        datawarehouse_base CURSOR LOCAL 
                         FOR 
                          SELECT bu.BOOKKEY, b.BOOKKEY AS BOOKKEY1
                            FROM dbo.BOOKWHUPDATE b, dbo.BOOK bu
                            WHERE ((bu.BOOKKEY = b.BOOKKEY) AND 
                                    (bu.STANDARDIND <> 'Y') AND 
                                    (b.BOOKKEY NOT IN
                                        ( 
                                          SELECT bl.BOOKKEY
                                            FROM dbo.BOOKLOCK bl
                                        )))
                          UNION
                          SELECT DISTINCT bu.BOOKKEY, b.BOOKKEY AS BOOKKEY1
                            FROM dbo.BOOK bu, dbo.BOOKAUTHOR b, dbo.AUTHORPREVIOUSWORKS a
                            WHERE ((b.BOOKKEY = bu.BOOKKEY) AND 
                                    (b.AUTHORKEY = a.AUTHORKEY) AND 
				    convert(varchar(20), a.LASTMAINTDATE, 100) like (IsNull(convert(varchar(20), getdate(), 100), '')) and
                                    (bu.STANDARDIND <> 'Y') AND 
                                    (b.BOOKKEY NOT IN
                                        ( 
                                          SELECT bl.BOOKKEY
                                            FROM dbo.BOOKLOCK bl
                                        )))
                          ORDER BY b.bookkey1 DESC
                      

                      OPEN datawarehouse_base

                      FETCH NEXT FROM datawarehouse_base
                        INTO @cursor_row$BOOKKEY$4, @cursor_row$BOOKKEY1$2

                      WHILE  NOT(@@FETCH_STATUS = -1)
                        BEGIN

                          IF (@ware_activeind = 1)
                            BREAK 

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLEINFO
                            WHERE (dbo.WHTITLEINFO.BOOKKEY = @cursor_row$BOOKKEY$4)


                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLEINFO
                              WHERE (dbo.WHTITLEINFO.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHAUTHOR
                            WHERE (dbo.WHAUTHOR.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHAUTHOR
                              WHERE (dbo.WHAUTHOR.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLECLASS
                            WHERE (dbo.WHTITLECLASS.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLECLASS
                              WHERE (dbo.WHTITLECLASS.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLEDATES
                            WHERE (dbo.WHTITLEDATES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLEDATES
                              WHERE (dbo.WHTITLEDATES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLEFILES
                            WHERE (dbo.WHTITLEFILES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLEFILES
                              WHERE (dbo.WHTITLEFILES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLECOMMENTS
                            WHERE (dbo.WHTITLECOMMENTS.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLECOMMENTS
                              WHERE (dbo.WHTITLECOMMENTS.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLECOMMENTS2
                            WHERE (dbo.WHTITLECOMMENTS2.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLECOMMENTS2
                              WHERE (dbo.WHTITLECOMMENTS2.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLECOMMENTS3
                            WHERE (dbo.WHTITLECOMMENTS3.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLECOMMENTS3
                              WHERE (dbo.WHTITLECOMMENTS3.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLEPERSONNEL
                            WHERE (dbo.WHTITLEPERSONNEL.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLEPERSONNEL
                              WHERE (dbo.WHTITLEPERSONNEL.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLEPREVWORKS
                            WHERE (dbo.WHTITLEPREVWORKS.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLEPREVWORKS
                              WHERE (dbo.WHTITLEPREVWORKS.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHPRINTING
                            WHERE (dbo.WHPRINTING.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHPRINTING
                              WHERE (dbo.WHPRINTING.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHPRINTINGKEYDATES
                            WHERE (dbo.WHPRINTINGKEYDATES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHPRINTINGKEYDATES
                              WHERE (dbo.WHPRINTINGKEYDATES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHPRINTINGKEYDATES2
                            WHERE (dbo.WHPRINTINGKEYDATES2.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHPRINTINGKEYDATES2
                              WHERE (dbo.WHPRINTINGKEYDATES2.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLECUSTOM
                            WHERE (dbo.WHTITLECUSTOM.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLECUSTOM
                              WHERE (dbo.WHTITLECUSTOM.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHFINALCOSTEST
                            WHERE (dbo.WHFINALCOSTEST.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHFINALCOSTEST
                              WHERE (dbo.WHFINALCOSTEST.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE1
                            WHERE (dbo.WHSCHEDULE1.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE1
                              WHERE (dbo.WHSCHEDULE1.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE2
                            WHERE (dbo.WHSCHEDULE2.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE2
                              WHERE (dbo.WHSCHEDULE2.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE3
                            WHERE (dbo.WHSCHEDULE3.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE3
                              WHERE (dbo.WHSCHEDULE3.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE4
                            WHERE (dbo.WHSCHEDULE4.BOOKKEY = @cursor_row$BOOKKEY$4)


                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE4
                              WHERE (dbo.WHSCHEDULE4.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE5
                            WHERE (dbo.WHSCHEDULE5.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE5
                              WHERE (dbo.WHSCHEDULE5.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE6
                            WHERE (dbo.WHSCHEDULE6.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE6
                              WHERE (dbo.WHSCHEDULE6.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE7
                            WHERE (dbo.WHSCHEDULE7.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE7
                              WHERE (dbo.WHSCHEDULE7.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE8
                            WHERE (dbo.WHSCHEDULE8.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE8
                              WHERE (dbo.WHSCHEDULE8.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE9
                            WHERE (dbo.WHSCHEDULE9.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE9
                              WHERE (dbo.WHSCHEDULE9.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE10
                            WHERE (dbo.WHSCHEDULE10.BOOKKEY = @cursor_row$BOOKKEY$4)

                         IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE10
                              WHERE (dbo.WHSCHEDULE10.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE11
                            WHERE (dbo.WHSCHEDULE11.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE11
                              WHERE (dbo.WHSCHEDULE11.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE12
                            WHERE (dbo.WHSCHEDULE12.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE12
                              WHERE (dbo.WHSCHEDULE12.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE13
                            WHERE (dbo.WHSCHEDULE13.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE13
                              WHERE (dbo.WHSCHEDULE13.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE14
                            WHERE (dbo.WHSCHEDULE14.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE14
                              WHERE (dbo.WHSCHEDULE14.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE15
                            WHERE (dbo.WHSCHEDULE15.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE15
                              WHERE (dbo.WHSCHEDULE15.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE16
                            WHERE (dbo.WHSCHEDULE16.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE16
                              WHERE (dbo.WHSCHEDULE16.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE17
                            WHERE (dbo.WHSCHEDULE17.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE17
                              WHERE (dbo.WHSCHEDULE17.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE18
                            WHERE (dbo.WHSCHEDULE18.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE18
                              WHERE (dbo.WHSCHEDULE18.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE19
                            WHERE (dbo.WHSCHEDULE19.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE19
                              WHERE (dbo.WHSCHEDULE19.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE20
                            WHERE (dbo.WHSCHEDULE20.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE20
                              WHERE (dbo.WHSCHEDULE20.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE21
                            WHERE (dbo.WHSCHEDULE21.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE21
                              WHERE (dbo.WHSCHEDULE21.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHSCHEDULE22
                            WHERE (dbo.WHSCHEDULE22.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHSCHEDULE22
                              WHERE (dbo.WHSCHEDULE22.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHPRINTINGKEYDATES
                            WHERE (dbo.WHPRINTINGKEYDATES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHPRINTINGKEYDATES
                              WHERE (dbo.WHPRINTINGKEYDATES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          /*  1-29-03 added whauthorsalestrack, whcompetitivetitles, whcomparativetitles  */

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHAUTHORSALESTRACK
                            WHERE (dbo.WHAUTHORSALESTRACK.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHAUTHORSALESTRACK
                              WHERE (dbo.WHAUTHORSALESTRACK.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHCOMPETITIVETITLES
                            WHERE (dbo.WHCOMPETITIVETITLES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHCOMPETITIVETITLES
                              WHERE (dbo.WHCOMPETITIVETITLES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHCOMPARATIVETITLES
                            WHERE (dbo.WHCOMPARATIVETITLES.BOOKKEY = @cursor_row$BOOKKEY$4)

                           IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHCOMPARATIVETITLES
                              WHERE (dbo.WHCOMPARATIVETITLES.BOOKKEY = @cursor_row$BOOKKEY$4)

                          /*  8/30/04 added titlepositioning   */

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.WHTITLEPOSITIONING
                            WHERE (dbo.WHTITLEPOSITIONING.BOOKKEY = @cursor_row$BOOKKEY$4)

                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            DELETE FROM dbo.WHTITLEPOSITIONING
                              WHERE (dbo.WHTITLEPOSITIONING.BOOKKEY = @cursor_row$BOOKKEY$4)

                          EXEC dbo.DATAWAREHOUSE_AUTHOR @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whauthor */


                          EXEC dbo.DATAWAREHOUSE_BOOKINFO @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitleinfo and whtitleclass */

                          EXEC dbo.DATAWAREHOUSE_BISAC @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitleclass */

                          EXEC dbo.DATAWAREHOUSE_CATEGORY @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitleclass */

                          EXEC dbo.DATAWAREHOUSE_AUDIENCE @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitleclass */

                          EXEC dbo.DATAWAREHOUSE_ORGENTRY @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitleclass */

                          EXEC dbo.DATAWAREHOUSE_BOOKPRICE @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitleinfo */

                          EXEC dbo.DATAWAREHOUSE_BOOKDATES @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitledates */

                          EXEC dbo.DATAWAREHOUSE_BOOKFILES @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitlefiles */

                          EXEC dbo.DATAWAREHOUSE_BOOKROLE @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitlepersonnel */

                          EXEC dbo.DATAWAREHOUSE_BOOKCOMMENT @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitlecomments */

                          EXEC dbo.DATAWAREHOUSE_PREVAUTH @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitleprevworks */

                          EXEC dbo.DATAWAREHOUSE_PRINTING @cursor_row$BOOKKEY$4, @ware_illuspapchgcode, @ware_textpapchgcode, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whprinting */

                          EXEC dbo.DATAWAREHOUSE_BOOKMISC @cursor_row$BOOKKEY$4, 'WARE_STORED_PROC', @ware_system_date 

                          SET @ware_lastbookkey = @cursor_row$BOOKKEY$4

                          EXEC dbo.DATAWAREHOUSE_BOOKQTYBREAKDOWN @cursor_row$BOOKKEY$4, @ware_system_date 

                          EXEC dbo.DATAWAREHOUSE_BOOKCUSTOM @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitlecustom */

                          EXEC dbo.DATAWAREHOUSE_AUDIENCE @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitleclass */

                          EXEC dbo.DATAWAREHOUSE_WHTITLECATALOG @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date 

                          /* whtitlecatalog */

                          SET @ware_associatedtitles_count = 0

                          SET @ware_associationtypecode = 3

                          /*  whauthorsalestrack  */

                          EXEC dbo.DATAWAREHOUSE_TITLEPOSITIONING @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date, @ware_associationtypecode 

                          SET @ware_associationtypecode = 1

                          /*  whcompetitivetitles  */

                          EXEC dbo.DATAWAREHOUSE_TITLEPOSITIONING @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date, @ware_associationtypecode 

                          SET @ware_associationtypecode = 2

                          /*  whcomparativetitles  */

                          EXEC dbo.DATAWAREHOUSE_TITLEPOSITIONING @cursor_row$BOOKKEY$4, @ware_logkey, @ware_newhousekey, @ware_system_date, @ware_associationtypecode 

                          EXEC dbo.dw_whtitlepositioning @cursor_row$BOOKKEY$4, @ware_system_date 

                          /*  whtitlepositioning  */

                          SET @ware_count2 = 0

                          SELECT @ware_count2 = count( * )
                            FROM dbo.BOOKWHUPDATE
                            WHERE (dbo.BOOKWHUPDATE.BOOKKEY = @cursor_row$BOOKKEY$4)


                          IF ((@@ROWCOUNT > 0) AND 
                                  (@ware_count2 > 0))
                            BEGIN
                              DELETE FROM dbo.BOOKWHUPDATE
                                WHERE (dbo.BOOKWHUPDATE.BOOKKEY = @cursor_row$BOOKKEY$4)
                            END

                          SET @ware_count = (@ware_count + 1)

                          FETCH NEXT FROM datawarehouse_base
                            INTO @cursor_row$BOOKKEY$4, @cursor_row$BOOKKEY1$2

                        END

                      CLOSE datawarehouse_base

                      DEALLOCATE datawarehouse_base

                    END

                  END

                /* Processing whtitlepositioning */

                /*
                 -- delete from qsidba.whtitlepositioning;
                 -- COMMIT;
                 -- 
                 -- dw_whtitlepositioning_custom;
                 --*/

                IF (@i_titleonly <> 1)
                  BEGIN

                    /*  8-27-02 only do titles if this =1 otherwise run all  */

                    /*  Processing catalog do before estimates 2-4-03  */

                    DELETE FROM dbo.WHCATALOG
                    DELETE FROM dbo.WHCATALOGTITLE
                    EXEC dbo.DATAWAREHOUSE_CATALOG @ware_logkey, @ware_newhousekey, @ware_system_date 

                    /* whcatalog */

                    EXEC dbo.DATAWAREHOUSE_CATALOGTITLE @ware_logkey, @ware_newhousekey, @ware_system_date 

                    /* whcatalogtitle */

                   -- DELETE FROM dbo.WHEST
                   -- DELETE FROM dbo.WHESTCOST
                    /* Processing Estimates */

                    SELECT @ware_company = upper(dbo.ORGLEVEL.ORGLEVELDESC)
                      FROM dbo.ORGLEVEL
                      WHERE (dbo.ORGLEVEL.ORGLEVELKEY = 1)
                  END

                /*  do only if build complete */

                UPDATE dbo.WHHISTORYINFO
                  SET 
                    dbo.WHHISTORYINFO.ENDTIME = getdate(), 
                    dbo.WHHISTORYINFO.ACTIVERUNIND = 0, 
                    dbo.WHHISTORYINFO.TOTALROWS = @ware_total, 
                    dbo.WHHISTORYINFO.ROWSPROCESSED = @ware_count, 
                    dbo.WHHISTORYINFO.LASTUSERID = 'WARE_STORED_PROC', 
                    dbo.WHHISTORYINFO.LASTMAINTDATE = @ware_system_date, 
                    dbo.WHHISTORYINFO.LASTBOOKKEY = @ware_lastbookkey
                  WHERE (dbo.WHHISTORYINFO.WAREHOUSEKEY = @ware_newhousekey)

              END


      END
go
grant execute on datawarehouse_base_incr  to public
go





