SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[bookdates387]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[bookdates387]
GO



CREATE VIEW bookdates387 AS 
SELECT BOOKKEY,PRINTINGKEY,DATETYPECODE,ACTIVEDATE,
ACTUALIND,RECENTCHANGEIND,LASTUSERID,LASTMAINTDATE,
ESTDATE,SORTORDER,BESTDATE FROM BOOKDATES
   WHERE DATETYPECODE = 387

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

