if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[ALLAUTHDISP_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[ALLAUTHDISP_VIEW]
GO

create view dbo.ALLAUTHDISP_VIEW(BOOKKEY, ALLAUTHDISP)  AS 

  SELECT dbo.BOOK.BOOKKEY, CASE dbo.AUTHALL1_VIEW.DISPLAYNAME WHEN  NULL THEN  NULL ELSE CASE dbo.AUTHALL2_VIEW.DISPLAYNAME WHEN  NULL THEN dbo.AUTHALL1_VIEW.DISPLAYNAME ELSE CASE dbo.AUTHALL3_VIEW.DISPLAYNAME WHEN  NULL THEN (isnull(dbo.AUTHALL1_VIEW.DISPLAYNAME, '') + '; ' + isnull(dbo.AUTHALL2_VIEW.DISPLAYNAME, '')) ELSE CASE dbo.AUTHALL4_VIEW.DISPLAYNAME WHEN  NULL THEN (isnull(dbo.AUTHALL1_VIEW.DISPLAYNAME, '') + '; ' + isnull(dbo.AUTHALL2_VIEW.DISPLAYNAME, '') + '; ' + isnull(dbo.AUTHALL3_VIEW.DISPLAYNAME, '')) ELSE (isnull(dbo.AUTHALL1_VIEW.DISPLAYNAME, '') + '; ' + isnull(dbo.AUTHALL2_VIEW.DISPLAYNAME, '') + '; ' + isnull(dbo.AUTHALL3_VIEW.DISPLAYNAME, '') + '; ' + isnull(dbo.AUTHALL4_VIEW.DISPLAYNAME, '')) END END END END AS ALLAUTHDISP
    FROM dbo.BOOK
       LEFT JOIN dbo.AUTHALL1_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTHALL1_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTHALL2_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTHALL2_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTHALL3_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTHALL3_VIEW.BOOKKEY)
       LEFT JOIN dbo.AUTHALL4_VIEW  ON (dbo.BOOK.BOOKKEY = dbo.AUTHALL4_VIEW.BOOKKEY)
go
GRANT SELECT ON ALLAUTHDISP_VIEW TO public
go