if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BESTSEASONKEY_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BESTSEASONKEY_VIEW]
GO
create view dbo.BESTSEASONKEY_VIEW(BOOKKEY, PRINTINGKEY, BESTSEASONKEY)  AS 
  SELECT dbo.PRINTING.BOOKKEY, dbo.PRINTING.PRINTINGKEY, CASE dbo.PRINTING.SEASONKEY WHEN  NULL THEN dbo.PRINTING.ESTSEASONKEY WHEN 0 THEN dbo.PRINTING.ESTSEASONKEY ELSE dbo.PRINTING.SEASONKEY END AS BESTSEASONKEY
    FROM dbo.PRINTING
    WHERE (dbo.PRINTING.PRINTINGKEY = 1)



go
GRANT SELECT ON BESTSEASONKEY_VIEW TO public
go