if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[BOOKSUBIMPRINT_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[BOOKSUBIMPRINT_VIEW]
GO
create view dbo.BOOKSUBIMPRINT_VIEW(ORGENTRYKEY, ORGLEVELKEY, ORGENTRYDESC, ORGENTRYPARENTKEY, ORGENTRYSHORTDESC, DELETESTATUS, LASTUSERID, LASTMAINTDATE, BOOKKEY)  AS 
  SELECT 
      dbo.ORGENTRY.ORGENTRYKEY, 
      dbo.ORGENTRY.ORGLEVELKEY, 
      dbo.ORGENTRY.ORGENTRYDESC, 
      dbo.ORGENTRY.ORGENTRYPARENTKEY, 
      dbo.ORGENTRY.ORGENTRYSHORTDESC, 
      dbo.ORGENTRY.DELETESTATUS, 
      dbo.ORGENTRY.LASTUSERID, 
      dbo.ORGENTRY.LASTMAINTDATE, 
      dbo.BOOKORGENTRY.BOOKKEY
    FROM dbo.ORGENTRY, dbo.BOOKORGENTRY
    WHERE ((dbo.ORGENTRY.ORGLEVELKEY = 6) AND 
            (dbo.BOOKORGENTRY.ORGENTRYKEY = dbo.ORGENTRY.ORGENTRYKEY))


go
GRANT SELECT ON BOOKSUBIMPRINT_VIEW TO public
go