if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CATALOGTITLES_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[CATALOGTITLES_VIEW]
GO
create view dbo.CATALOGTITLES_VIEW(CATALOGTITLE, CATALOGTYPE, [SECTION], SEASON, BOOKKEY, [POSITION], WEIGHT, CATALOGPAGENUMBER, FINALIZEDIND, CATALOGHEADING)  AS 
  SELECT 
      c.CATALOGTITLE, 
      ct.DATADESC AS CATALOGTYPE, 
      cs.DESCRIPTION AS [SECTION], 
      s.SEASONDESC AS SEASON, 
      bc.BOOKKEY, 
      cp.DATADESC AS [POSITION], 
      cv.DATADESC AS WEIGHT, 
      bc.CATALOGPAGENUMBER, 
      bc.FINALIZEDIND, 
      ch.DATADESC
    FROM dbo.CATALOGSECTION cs, dbo.CATALOGTYPE_VIEW ct, dbo.SEASON s
       LEFT JOIN dbo.[CATALOG] c  ON (s.SEASONKEY = c.SEASONKEY), dbo.BOOKCATALOG bc
       LEFT JOIN dbo.CATWEIGHT_VIEW cv  ON (cv.DATACODE = bc.CATALOGWEIGHTCODE)
       LEFT JOIN dbo.CATPOS_VIEW cp  ON (bc.CATALOGPOSITIONCODE = cp.DATACODE)
       LEFT JOIN dbo.CATALOGHEADING_VIEW ch  ON (bc.CATALOGHEADING = ch.DATACODE)
    WHERE ((c.CATALOGKEY = cs.CATALOGKEY) AND 
            (cs.SECTIONKEY = bc.SECTIONKEY) AND 
            (ct.DATACODE = c.CATALOGTYPECODE))
    GROUP BY c.CATALOGTITLE, cs.DESCRIPTION, s.SEASONDESC, bc.BOOKKEY, cp.DATADESC, cv.DATADESC, bc.CATALOGPAGENUMBER, bc.FINALIZEDIND, ch.DATADESC, ct.DATADESC


go
GRANT SELECT ON CATALOGTITLES_VIEW TO public
go