if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CATALOGPARENTSECTION_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[CATALOGPARENTSECTION_VIEW]
GO
create view dbo.CATALOGPARENTSECTION_VIEW(PARENTSECTIONKEY, SECTIONKEY, DESCRIPTION)  AS 

  SELECT TOP 100 PERCENT a.PARENTSECTIONKEY, b.SECTIONKEY, b.DESCRIPTION
    FROM dbo.CATALOGSECTION a, dbo.CATALOGSECTION b
    WHERE (a.PARENTSECTIONKEY = b.SECTIONKEY)
  ORDER BY b.DESCRIPTION


go
GRANT SELECT ON CATALOGPARENTSECTION_VIEW TO public
go