if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[CONTRACTTYPE_VIEW]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[CONTRACTTYPE_VIEW]
GO
create view dbo.CONTRACTTYPE_VIEW(TABLEID, DATACODE, DATADESC, DELETESTATUS, APPLID, SORTORDER, TABLEMNEMONIC, EXTERNALCODE, DATADESCSHORT, LASTUSERID, LASTMAINTDATE, NUMERICDESC1, NUMERICDESC2)  AS 
  SELECT 
      dbo.GENTABLES.TABLEID, 
      dbo.GENTABLES.DATACODE, 
      dbo.GENTABLES.DATADESC, 
      dbo.GENTABLES.DELETESTATUS, 
      dbo.GENTABLES.APPLID, 
      dbo.GENTABLES.SORTORDER, 
      dbo.GENTABLES.TABLEMNEMONIC, 
      dbo.GENTABLES.EXTERNALCODE, 
      dbo.GENTABLES.DATADESCSHORT, 
      dbo.GENTABLES.LASTUSERID, 
      dbo.GENTABLES.LASTMAINTDATE, 
      dbo.GENTABLES.NUMERICDESC1, 
      dbo.GENTABLES.NUMERICDESC2
    FROM dbo.GENTABLES
    WHERE (dbo.GENTABLES.TABLEID = 418)


go
GRANT SELECT ON CONTRACTTYPE_VIEW TO public
go