if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[EBOOK_LINK]') and OBJECTPROPERTY(id, N'IsView') = 1)
  drop view [dbo].[EBOOK_LINK]
GO
create view dbo.EBOOK_LINK(CHILDBOOKKEY, LASTMAINTDATE, LASTUSERID, PARENTBOOKKEY, QUANTITY, RELATIONCODE, SORTORDER)  AS 

  SELECT 
      dbo.BOOKFAMILY.CHILDBOOKKEY, 
      dbo.BOOKFAMILY.LASTMAINTDATE, 
      dbo.BOOKFAMILY.LASTUSERID, 
      dbo.BOOKFAMILY.PARENTBOOKKEY, 
      dbo.BOOKFAMILY.QUANTITY, 
      dbo.BOOKFAMILY.RELATIONCODE, 
      dbo.BOOKFAMILY.SORTORDER
    FROM dbo.BOOKFAMILY
    WHERE (dbo.BOOKFAMILY.RELATIONCODE = '20005')


go
GRANT SELECT ON EBOOK_LINK TO public
go